### ISSUE TITLE
Refined Storage Tps lag with new recipes

### ISSUE THREAD

**Issue by Dinip12** [FTBTeam/FTB-Revelation-2#100]
* **Modpack Version**: 2.4.0

* **Issue**: On the update to 2.4.0 the solderers from Refined Storage were removed and a new recipe with cutting tool was added. The problem is when people on the server autocraft with this new way of making processors the server goes to 4 tps... I've tested diferent recipes with autocraft on Refined system and none lags the server, only recipes with the cutting tool involved like 16/64k storage disks.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refined Storage

* **Known Fix**: Remove the "new" recipe and add the solderer back...

Here is a printscreen: 
![image](https://user-images.githubusercontent.com/8941012/44399774-aa647380-a540-11e8-8543-7bc1f864a616.png)

**Comment by tfox83** [comment]
This has been optimized in latest RS which is in v2.5.0 of the pack
