### ISSUE TITLE
Inconsistency in Treated Plank recipes. 

### ISSUE THREAD

**Issue by Gunner76th** [FTBTeam/FTB-Revelation-2#101]
* **Modpack Version**:2.3.0

* **Issue**: When crafting Treated Planks in the crafting grid, you use 8 planks and 1 bucket of Creosote to get 8 treated planks. However if you use the Fluid Transposer you put in 1 log and 125mb of creosote and get 1 treated plank. This is inconsistent in that it should be 1 plank + 125mb = 1 treated plank since 1 bucket / 8 planks = 125mb/plank 

Fluid Transposer recipe
https://cdn.discordapp.com/attachments/289539713587609601/481948900249567232/unknown.png
![image](https://user-images.githubusercontent.com/5566872/44493974-0cec6b00-a638-11e8-8f53-80ded4c1e92b.png)

Manual crafting recipe
https://cdn.discordapp.com/attachments/289539713587609601/481948935758413834/unknown.png
![image](https://user-images.githubusercontent.com/5566872/44493980-11188880-a638-11e8-862d-29fbd1df38ea.png)

* **Mod/s Affected**: Immersive Engineering, Thermal Expansion

* **Known Fix**: Change the recipe script for the Treated Planks for the Fluid Transposer to have the inputs be 1 plank + 125mb creosote and the output be 1 treated plank. Simply replace ore:logWood to ore:plankWood

**Comment by Gunner76th** [comment]
Also, I have noticed that currently the ore dict that is being used is minecraft:logWood, however because of the myriad of trees within the pack a more appropriate entry would be ore:logWood instead that way all logs regardless of the mod they come from (IE Forestry, Thaumcraft, Extra Trees, Natura, Twilight Forest) can be used. 

Display of trees listed under ore:logWood vs minecraft:logWood
ore:logWood
![image](https://user-images.githubusercontent.com/5566872/44494523-1ecf0d80-a63a-11e8-83e5-eb28953b24c0.png)
![image](https://user-images.githubusercontent.com/5566872/44494528-2393c180-a63a-11e8-9fd4-990c47477f86.png)
minecraft:logWood
![image](https://user-images.githubusercontent.com/5566872/44494576-4b832500-a63a-11e8-8c39-53ff5c85cbbc.png)

**Comment by Gunner76th** [comment]
In another surprising twist, the recipe shows that you can use Birch Logs in the Fluid Transposer to make Treated Planks with, however when you attempt this in game, it does not allow you to put logs into the Fluid Transposer. 

Recipe lookup from hitting "R" while hovering over Treated Planks: 
![image](https://user-images.githubusercontent.com/5566872/44494910-c567de00-a63b-11e8-87c0-b8fdfba8a6ca.png)

Usage Lookup of Birch Logs when when hitting "U" while hovering over Birch Logs: 
![image](https://user-images.githubusercontent.com/5566872/44494935-dca6cb80-a63b-11e8-82f1-8f51e7c90a17.png)
![image](https://user-images.githubusercontent.com/5566872/44494942-e4667000-a63b-11e8-9541-bb981715d788.png)
![image](https://user-images.githubusercontent.com/5566872/44494945-e8928d80-a63b-11e8-8a0e-839d75579a3e.png)
![image](https://user-images.githubusercontent.com/5566872/44494959-efb99b80-a63b-11e8-9a8f-e206cc888c66.png)
![image](https://user-images.githubusercontent.com/5566872/44494963-f3e5b900-a63b-11e8-9268-6841df74137b.png)

As you can see, there is no "Usage" entry for the logs in the fluid transposer on lookup, even though the planks show there is. This is indicating a possible corrupt recipe entry (recipe removed but not added back in properly or other such error) or a recipe conflict of some nature.

**Comment by tfox83** [comment]
As of now I am going to leave this as this is a default mod pack for the most part and we want the recipes to match the devs wikis.  Thank you for the detailed reports.
