### ISSUE TITLE
Recipes missing for Simply Jetpacks (Ender IO path) tier 2+ Armor Plating

### ISSUE THREAD

**Issue by GunArm** [FTBTeam/FTB-Revelation-2#102]
I'm not sure how to determine the version of the Revelation pack I am using (we set it up 4 days ago).  It's not on the startup screen, and I looked for any kind of readme/changelog text file in the pack root but did not find one.  Perhaps I overlooked something?

The issue is that there doesn't seem to be a way to craft the tier 2+ Armor Plating for the Ender IO path of SimplyJetpacks.  Specifically, while you can craft the Silicon Armor Plating (tier 1) on a crafting table, there is no recipe for: Conductive Iron Armor Plating, Electrical Steel Armor Plating, or Dark Steel Armor Plating.  No recipe is shown in JEI, and also the recipe I am familiar with of putting 10 conductive iron in an Alloy Smelter with the Silicon Armor Plating does not work, in fact the Alloy Smelter will not even accept the Silicon Armor Plating.  Of course it's possible the recipe is different but it's not shown in JEI.

The Thermal Expansion path has recipes and they are what I would expect, putting 10 ingots of material in the Induction Smelter with the previous armor.  These work as expected.

Again, maybe I've overlooked something?

**Comment by Gunner76th** [comment]
Your pack version is located on the Twitch launcher as seen in this screenshot: 
![image](https://user-images.githubusercontent.com/5566872/44559203-57dcb000-a716-11e8-9bff-cb5571b176f1.png)

**Comment by Gunner76th** [comment]
The mod versions can be found by looking at the files as all mod files contain their version in the filename: 
![image](https://user-images.githubusercontent.com/5566872/44559258-b9048380-a716-11e8-8894-3687b1f73ce1.png)

**Comment by GunArm** [comment]
Thanks, although I'm not using the twitch launcher, I did figure it out, it's Revelations 2.4.  And just to be super clear my EnderIO version is 5.0.31 and SimplyJetpacks2 2.2.7.45

**Comment by tfox83** [comment]
I cannot reproduce this in my dev version of the pack (soon to be 2.5.0)

**Comment by bathrobehero** [comment]
These recipes still cannot be crafted in the latest version (2.5.0).
