### ISSUE TITLE
Bug with Thermal Induction Smelter

### ISSUE THREAD

**Issue by Mugiwaxar** [FTBTeam/FTB-Revelation-2#103]
Modpack Version: 2.4.0

Issue: 
Can't put Fuzed Quartz in Thermal Induction Smelter

Is it Repeatable?:  Maybe

Mod Affected:  Thermal Expension

Known Fix: Remove and add the recipe to CraftTweaker

Can't make any Hardened Glass with this induction smelter

**Comment by Gunner76th** [comment]
The recipe for hardened glass in the induction smelter (TE machine) is lead and obsidian. Can you please provide a screenshot of the recipe you are referring to as I am not aware of one requiring fuzed quartz.

**Comment by Mugiwaxar** [comment]
![capture d ecran 4](https://user-images.githubusercontent.com/4124999/44608808-7f567a00-a7f5-11e8-8d59-7c7aef9f132c.png)

**Comment by tfox83** [comment]
I do not see the issue here.  The lead and obsidian recipe works fine.
