### ISSUE TITLE
Personal player inventory screen "breaking" seemingly randomly

### ISSUE THREAD

**Issue by superbrias** [FTBTeam/FTB-Revelation-2#104]
* **Modpack Version**:2.4.0

* **Issue**:Occasionally while playing my inventory will "break", I can keep playing but I will no longer be able to use my personal player inventory. If I open my inventory (default - E) I will see a version of my inventory that will look that same as the last time I had opened it, not showing any items that entered my inventory since. Things that enter the hotbar while I am playing will properly update. Only time I am able to interact with my inventory is if I open it some other way, like when opening a chest or machine, upon doing so it will show the last version of my inventory then quickly update to what it should be, and will allow me to properly interact with my inventory while I have the alternate inventory open. If I do try to change my inventory while it is broken through the inventory button any items that leave my inventory will not drop and "disappear" from my inventory until I get it to update, and trying to move anything, from my hotbar to my inventory or vice versa, or just around, will not work and while visually it will show the changes, if I try to interact with that slot of my hotbar it will "properly" use the item that is actually there. (example, go into inventory to replace some dirt on my hotbar with cobblestone then leave my inventory to place the cobblestone and instead will place dirt, with the hotbar slot suddenly showing that it, in fact, still has the dirt in it)

weird side note:I am still able to shift+click my armor into my inventory.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/fe8d398b note: had been playing for a while after the problem had started and ignored it, if you would like I can try to grab a log that follows the problem starting more closely.

* **Is it Repeatable?**: ????

* **Mod/s Affected**: ??????

* **Known Fix**: Using alternate inventories. example - Iron Backpack, [Forestry]Miner's Backpack, /Dank/Null, Chests, Machines, etc. Save and quiting the world and loading it back up without restarting Minecraft works, restarting Minecraft does also work.

**Comment by Aedrilor** [comment]
I have this exact issue, reproducible by using the Astral Sorcery observatory. Issue starts after using the observatory and persists until reloading the world (or reconnecting to the server).

See here: https://github.com/HellFirePvP/AstralSorcery/issues/842

**Comment by tfox83** [comment]
Will get in once update is avail.

**Comment by tfox83** [comment]
this has been fixed by dev
