### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CaptianBoo** [FTBTeam/FTB-Revelation-2#105]
* **Modpack Version**: 2.3.0

* **Issue**: I did the usual thing with downloading and then clicking play. I should probably note that I have a Windows 7 Lenovo Laptop and I do not know the Intel chip as my keyboard was replaced sometime ago. Java Verson 8 Update 181 (build 1.8.0_181-b13)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9b5332c6
https://paste.feed-the-beast.com/view/b15085ed

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by jjhhgg100123** [comment]
Give the game more ram. It needs (at least) 4gb.

**Comment by CaptianBoo** [comment]
I'm in, but there is heavy lag. 1 or 2 FPS at most

**Comment by jjhhgg100123** [comment]
What are your computer specifications?

**Comment by jjhhgg100123** [comment]
Processor mainly.
