### ISSUE TITLE
get no seeds when harvest plant (leftclick or rightclick)

### ISSUE THREAD

**Issue by Goten87** [FTBTeam/FTB-Revelation-2#106]
* **Modpack Version**: 2.3.0

* **Issue**: i cant get extra seeds when i harvest the plant (wheat - Cotton - Barly)

* **Link to Log or Crash File Paste**: dont have a crash

* **Is it Repeatable?**: i dont know

* **Mod/s Affected**: think all mods with seeds

* **Known Fix**: i dont know a fix yet

**Comment by MorbiusStorm** [comment]
Are you using griefprevention? 652 was doing that. New version 653 fixed it.

**Comment by tfox83** [comment]
I dont support adding mods to the pack.  I can confirm I get seeds in the default pack
