### ISSUE TITLE
FTB Revelations has been broken for months.

### ISSUE THREAD

**Issue by FakeBobbyHill** [FTBTeam/FTB-Revelation-2#107]
* **Modpack Version**: 

* **Is it Repeatable?**: ongoing. It is absolutely repeatable. There is no crashing of the program

* **Mod/s Affected**: entire mod pack seems to be affected

* **Known Fix**: Sorry no luck here.

**Comment by Hojosa** [comment]
My guess is that foamfix is the reason. A friend of mine had the same/similar problem

**Comment by tfox83** [comment]
Cannot look into this with out any logs

**Comment by FakeBobbyHill** [comment]
Yeah, I don’t know anything about that stuff. I guess I’ll just not play that pack any more.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
