### ISSUE TITLE
FTB Revelations wont install off twitch launcher

### ISSUE THREAD

**Issue by Snubbsy** [FTBTeam/FTB-Revelation-2#109]
* **Modpack Version**: 2.4.0

* **Issue**: When i click install for version 2.4.0 off of twitch it gets to where it has to download twitch then it cancels and tells me it failed to download forge.

* **Link to Log or Crash File Paste**: No crash log because it wont even download
* **Is it Repeatable?**: happens every time

* **Mod/s Affected**: Forge

* **Known Fix**: i wish

**Comment by yinnamin** [comment]
[https://i.imgur.com/XZ791nl.png](url)

Same issue. Here's a screenshot. A friend of mine was able to download it with no issues so not sure if this is a forge problem or what.

**Comment by tfox83** [comment]
It was a forge issue, the Beta has been removed from twitch and a fix is going live today
