### ISSUE TITLE
Quark's Wither Ash

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-Revelation-2#11]
Useless in the pack, unless a custom recipe is added. I think on Continuum a recipe was added so you could craft one skeleton skull with 8 wither ash around to make a wither skeleton skull.

**Comment by tfox83** [comment]
added same as continuum recipe

```
#wither ash
recipes.addShaped(<minecraft:skull:1>, [[<quark:black_ash>, <quark:black_ash>, <quark:black_ash>], [<quark:black_ash>, <minecraft:skull>, <quark:black_ash>], [<quark:black_ash>, <quark:black_ash>, <quark:black_ash>]]);
```
