### ISSUE TITLE
ProjectRed Issue

### ISSUE THREAD

**Issue by iimwolf** [FTBTeam/FTB-Revelation-2#110]
* **2.3.0 Modpack Version**:

* **Sometime when i try to break projectred blocks or cables my minecraft crashes.**:

* **https://paste.feed-the-beast.com/view/1419545c Crash Log**:

* **I can repeat the issue, but it's not my fault the crash, depends from mod.**:

* **ProjectRed Mod cause Issue**:

**Comment by tfox83** [comment]
This is fixed in next update
