### ISSUE TITLE
Please add Integration Forging

### ISSUE THREAD

**Issue by Gunner76th** [FTBTeam/FTB-Revelation-2#111]
As mentioned in https://github.com/Buuz135/Industrial-Foregoing/issues/177 issue thread, Integration Forging was developed so that the Industrial Forging machines would properly interact with things from other mods. Currently the plant gather does not harvest hemp, however the planter will plant hemp.  This addon should honestly be part of the pack as it adds compatibility features to allow the machines to work properly will all of the other mods currently in the pack. 

https://minecraft.curseforge.com/projects/integration-foregoing/files

**Comment by tfox83** [comment]
Added to 1.5.0
