### ISSUE TITLE
Draconic Energy Wireless Crystal's and EnderIO Mashines

### ISSUE THREAD

**Issue by TheSim14** [FTBTeam/FTB-Revelation-2#112]
Hey,

EnderIO Mashines don't accept Energy from Draconic Energy Wireless Crystal's that's very sad :(
I hope it's only a Bug and would be fixed with newer Version of both Mod's.

Greetz

P.S.: Pls Add AE2 Stuff to that Pack, i hate "normal" Inscriber for Automation D:

**Comment by FaiThiX** [comment]
AE2 Stuff just get removed with the 2.0.0 Release

**Comment by FaiThiX** [comment]
you can change the version of draconic evolution manually or wait for an update by tfox . when you play smp so you need to wait for an update, if you play ssp you can update it manually. And i dont think that tfox will bring back AE2 Stuff again :/ btw. i loved it too

**Comment by tfox83** [comment]
Fixed in next version, update due out soon!
