### ISSUE TITLE
JEI Inventory Search Function grabs most items

### ISSUE THREAD

**Issue by OibbSwank** [FTBTeam/FTB-Revelation-2#113]
* **Modpack Version**: Revelation 2.3.0

* **Issue**: JEI Inventory search (yellow search bar) highlights most items in my inventories unless I get needlessly specific. Poking around in the configs so far has yielded nothing.

![image](https://user-images.githubusercontent.com/22782732/45047006-752a4c00-b03d-11e8-97ec-e1ea7b6ecdcb.png)

![image](https://user-images.githubusercontent.com/22782732/45047107-bd496e80-b03d-11e8-95f9-78d5155cc22a.png)

* **Is it Repeatable?**: Been consistently doing this through world resets and PC restarts

* **Mod/s Affected**: As far as I know JEI 1.12.2-4.11.0.204

**Comment by FaiThiX** [comment]
Its not JEI its moreoverlays :)

Here is the Issue in there Repo and its already fixed in another version https://github.com/feldim2425/MoreOverlays/issues/46

**Comment by tfox83** [comment]
Fixed in next udpate
