### ISSUE TITLE
Recipe Issue with IC2 Steel Item Casing

### ISSUE THREAD

**Issue by Snowbotx9** [FTBTeam/FTB-Revelation-2#114]
* **2.4.1**: 

* **Cant seem to make steel item casings no matter what i do.**: 

* **Yes?**: 

* **Industialcraft 2**: 

* **none**:

**Comment by tfox83** [comment]
Added recipe using forge hammer in v1.5.0

**Comment by DreamSpawn** [comment]
I'm on pack version 2.7.0 and the recipe only works with a completely unused forge hammer. 
As soon as you use it once and it gets damaged, you can't use it to make anymore steel item casings.
