### ISSUE TITLE
Suggestion: Add World Control mod to the pack.

### ISSUE THREAD

**Issue by JonathanBourassa** [FTBTeam/FTB-Revelation-2#115]
World Control has recently been ported to 1.12
[https://minecraft.curseforge.com/projects/world-control](https://minecraft.curseforge.com/projects/world-control)
Would be helpfull to get it for alarms, combined with Big Reactor.

Thanks,

**Comment by tfox83** [comment]
The mod list is currently locked, thank you for the suggestion though.
