### ISSUE TITLE
Serious FPS issue

### ISSUE THREAD

**Issue by GodOFViolence** [FTBTeam/FTB-Revelation-2#116]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**: 
![2018-09-09_21 03 37](https://user-images.githubusercontent.com/43124102/45272723-2ed55280-b46c-11e8-8923-e6b6ac31a60b.png)

**Comment by GodOFViolence** [comment]
I shouldn't be having issues with FPS, due to the fact that I have a somewhat decent computer. Apparently not to this modpack... Please help.

**Comment by FaiThiX** [comment]
I found out this is an issue i got when my mipmap level is over 0 so please check your mipmap level and lower it

**Comment by tfox83** [comment]
I cannot reproduce this.  Maybe try the suggestion above.  We ship with mipmap to 0 for that reason.
