### ISSUE TITLE
Server Gone missing

### ISSUE THREAD

**Issue by gmanpohl23** [FTBTeam/FTB-Revelation-2#118]
Hello

So i have been playing the pack in 2.2 for a while on a server and it was Welcome to twiddle Town.
I went in to play it but it failed and then i deleted the pack and would try to re download it. Then it was not in the public servers list.

Version 2.2

Server wont let me login, and is gone

i tried it multiple times and the same happened.

Gmanpohl

**Comment by tfox83** [comment]
Sorry we do not support public server lists.  That is not in our control.  The server may be offline, or not public anymore.
