### ISSUE TITLE
Stackoverflow / recursion error when upgrading from 2.3.0 to 2.5.0

### ISSUE THREAD

**Issue by PhillZitt** [FTBTeam/FTB-Revelation-2#119]
* **Modpack Version**: 2.5.0

* **Issue**: StackOverflowError on server start

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ee5b5e06

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Please try a fresh install.  2.7.0 will release later today.
