### ISSUE TITLE
Draconic Evolution - Draconic reactor not outputting power

### ISSUE THREAD

**Issue by pacman1983** [FTBTeam/FTB-Revelation-2#120]
* **Modpack Version**: FTB Revelation 1.12.2 -2.5.0

* **Issue**: The RF isn't coming out of the flux gate for the draconic reactor. This was a know bug was fixed in the draconic evolution update version 2.3.14.307 see patch notes below

- Fixed AOE mining not taking modified player reach distance into account.
**- Fixed reactor not handling IO sides properly when outputting energy.**
- Attempted top fix broken gui's caused by broken mob souls courtesy of Headcrumbs.
- Fixed Advanced Dislocator not working in portal or pedestal.
- Fixed crash when using CTRL-Pick Block on placed items.

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: 

- https://minecraft.curseforge.com/projects/draconic-evolution/files/2619673
- https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2618630
- https://minecraft.curseforge.com/projects/brandons-core/files/2619369

* **Known Fix**:  Update the mods I have listed above. I have tested this on my server in single and multiplayer and this works for both.

**Comment by tfox83** [comment]
Fixed in 2.6.0+
