### ISSUE TITLE
Server Pack Fresh Install Has No Mods

### ISSUE THREAD

**Issue by Zyrotic** [FTBTeam/FTB-Revelation-2#122]
* **Modpack Version**: FTB Revelation 2.4.1 Server Pack

* **Issue**: The server is not launching properly. Even from fresh installs a majority of the mods are not being recognized by both the jar and the startserver.bat.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes. We've tried on three seperate computers.

* **Mod/s Affected**: All. The server does not  start correctly.

Help would be greatly appreciated. Would love to make this our main modpack of choice for the foreseeable future.

**Comment by tfox83** [comment]
I suggest a fresh install, I cannot reproduce this and all the mods are in the provided server zips
