### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by Corey1617** [FTBTeam/FTB-Revelation-2#123]
I just downloaded FTB-Revelation-2 and have been playing for about an hour. The entire time, I would experience frequent lag spikes that would freeze the game anywhere from 1 second, to sometimes 5-10 seconds. I am using the modpack through the Curse Launcher. My video setting are pretty low: fast graphics and clouds, render distance 8, low particles, and the max framerate set to 80.

I have a brand-new Lenovo Legion Y530 with an Intel Core i5-8300H CPU @ 2.3GHz with 8GB of RAM (7.88 usable). My OS is 64-bit. If anyone has any ideas on how to fix this, please share.

Thanks.

**Comment by dotSK** [comment]
How you tried increasing available heap memory for java runtime? For me, the lags were caused by garbage collector running in loop, because the allocated memory was always used to the max.
