### ISSUE TITLE
Game crash when FoamFix is deduplicating models

### ISSUE THREAD

**Issue by secretdataz** [FTBTeam/FTB-Revelation-2#124]
* **Modpack Version**: 2.5.0

* **Issue**: The game crashes when FoamFix is deduplicating models. This issue was not present in 2.4.1. I can play Revelation without modifying any file.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5e02d586

* **Is it Repeatable?**: I can reproduce the crash 3 out of 3 times

* **Mod/s Affected**: FoamFix 0.10.1

* **Known Fix**: Upgrading FoamFix to 0.10.2 have fixed the crash for me.

**Comment by ThwartAbyss54** [comment]
Updated my foamfix and now its saying its Immersive engineering doing it? 
[crash-2018-10-25_14.59.53-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/2516526/crash-2018-10-25_14.59.53-client.txt)

**Comment by tfox83** [comment]
Fixed in next version
