### ISSUE TITLE
Quark Wraiths have a Spawn Weight of 0 in config

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [FTBTeam/FTB-Revelation-2#126]
* **Modpack Version**: Literally all of them

* **Issue**: Quark Wraith Spawn Weight 0 in Config, causes none to spawn. If you want to disable wraiths you could just disable the world feature (I imagine it was set to 0 do to an old bug or a typo)

* **Mod/s Affected**: Quark

* **Known Fix**:  Having a spawn weight

**Comment by tfox83** [comment]
This is intended
