### ISSUE TITLE
Thaumcraft plates

### ISSUE THREAD

**Issue by valveo** [FTBTeam/FTB-Revelation-2#127]
* **Modpack Version**: FTBRevelation 2.5.0 1.12.2

* **Issue**: Thaumcraft plates (thaumium, brass, void metal) requires machine to make. However many plates can be made with ie/ic hammer. Many magic only players are wondering this.

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Add recipes to scripts/01_unification.zs

**Comment by tfox83** [comment]
Hammer to plate recipes have been added for the thaumcraft plates in v2.7.0
