### ISSUE TITLE
Idea for new mod implementation

### ISSUE THREAD

**Issue by marciox25** [FTBTeam/FTB-Revelation-2#128]
* **Modpack Version**: 
Any.
* **Issue**: 
Not really an Issue, rather a Idea?
Is it possible, to make also a quest-progression based idea for this mod? Just like Sky Factory/Skyblock or other kind of modpacks that has a quest-progression systeme?. It could be a nice thing to have. Many people like to play the mods like they were supposed to play, not with alterations on recipes (like skyfactory/skyblock has). And those who dont play that, they usually keep to the known-mods knowledge and never try out new mods. This pack for example. It has so many mods to explore, but I dont really know where to start. And a Quest Book would definitaly help. Also, A good reward randomizer with the completed quest would be great!

* **Link to Log or Crash File Paste**: 
-
* **Is it Repeatable?**: 
no
* **Mod/s Affected**: 
no
* **Known Fix**: 
no

**Comment by marciox25** [comment]
maybe also add a descent randomised reward system? would be fun.

**Comment by tfox83** [comment]
No questing system is planned to be added at this time
