### ISSUE TITLE
Cannot Craft Essence of Scornful Oblivion

### ISSUE THREAD

**Issue by TDY2012** [FTBTeam/FTB-Revelation-2#131]
* **Modpack Version**: 2.5.0-1

* **Issue**: The recipe of essence of scornful oblivion is shown in JEI but cannot be crafted.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Just try to craft it

Note: It seems like other mod packs have this issue too.

**Comment by tfox83** [comment]
Fixed in latest beta
