### ISSUE TITLE
Item duplication bug with Uncrafting Table and Tome of Alkahestry

### ISSUE THREAD

**Issue by Steampunk-Wizard** [FTBTeam/FTB-Revelation-2#132]
* **Modpack Version**: Revelation 2.5.0

* **Issue**: Can dupe various items using the Uncrafting table from Twilight Forest and the Tome of Alkahestry from Reliquary. When uncrafting anything that has an Alkahestry recipe, you receive a fully charged tome. Notable dupable items include Emeralds, Diamonds, Nether Stars, Steel, Redstone, and Wither Skeleton Skulls (by uncrafting the tome with 220 or more charges left)

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Incredibly Repeatable. Can Dupe diamonds x7 or double nether stars for only 2 experience levels.

* **Mod/s Affected**: Twilight Forest, Reliquary

* **Known Fix**: Ban Uncrafting Tables on your server. - Actual solutions may include removing the Alkahestry recipes from the UC Table, or returning a near-empty Tome (as if the player had just enough charges to use the tome recipe in the first place).

**Comment by NHDriver4** [comment]
Do we know if this was resolved in 2.6.0?

**Comment by tfox83** [comment]
This has been fixed
