### ISSUE TITLE
the minecraft closes when loading the modpack

### ISSUE THREAD

**Issue by Panhordo77** [FTBTeam/FTB-Revelation-2#133]
I have a good computer with a 1050ti board and I put the minecraft with 6 of ram but it also closes when loading the mods

**Comment by Didr** [comment]
The following solutions have worked for me:
Reinstalling the modpack
Increasing RAM
Trying again
But the primary soluton has been to keep the Minecraft window in focus as it is loading. That is, not doing anything else while it is loading.
