### ISSUE TITLE
Essence of Scornful Oblivion - Uncraftable

### ISSUE THREAD

**Issue by Av1212xx** [FTBTeam/FTB-Revelation-2#134]
* **Modpack Version**: 2.5.0 (Recommended) and also tried in 2.6.0 

* **Issue**: Recipe for Essence of Scornful Oblivion (MagicBees) does not work. Recipe shows up in the JEI but it cannot be crafted. I've tried using a Crafting Table (Minecraft), Worktable (Forestry), Arcane Workbench (Thaumcraft), and Jungle Fancy Workbench (Bibliocraft) to craft Essence of Scornful Oblivion. It does not work. 

* **Link to Log or Crash File Paste**: There is no crash. Recipe simply does not work.

* **Is it Repeatable?**: Yes, this is repeatable. You can go to either single or multiplayer. Get the ingredients the long way through survival, or simply summon the necessary ingredients through creative mode. The recipe does not work in the Crafting Table and other similar crafting benches. 

* **Mod/s Affected**: MagicBees of FTB Revelations 2.5.0 and 2.6.0

* **Known Fix**: Just add in whatever crafting code-y stuff is missing so that the recipe works. Thanks.

**Comment by tfox83** [comment]
Fixed in 2.7.0
