### ISSUE TITLE
Disconnects upon connection to server

### ISSUE THREAD

**Issue by JosNun** [FTBTeam/FTB-Revelation-2#136]
* **Modpack Version**: 2.5.0

* **Issue**: Whenever I connect to a server, the moment that I get past the loading screen and into the fpv, I get disconnected from the server. Sometimes it says connection timed out, other times it gives me a Java.io.IOException: Connection reset by peer, and other times, it simply says disconnected. So far, in my 20+ attempts at connecting, I've had two successful connections, and after I connect, everything runs fine. 

I'll also note that we were experiencing [this error](https://github.com/TeamJM/journeymap/issues/42), but removing journeymap from the server has stopped those errors from logging.

**EDIT:** I'll also note that the network I was on was ~250Mbps up and ~30Mbps down, so I don't think that's an issue. Also, there's other people that can connect and it works fine for them.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6e7c30f9

* **Is it Repeatable?**: yes

* **Known Fix**: Add the mod "[RandomPatches](https://minecraft.curseforge.com/projects/randompatches)" as @Zoidey mentioned in [their comment](https://github.com/FTBTeam/FTB-Revelation-2/issues/136#issuecomment-441870237)

Thanks in advance!

**EDIT:** Added known fix

**Comment by Zoidey** [comment]
Have you tried adding the mod "RandomPatches"? It might help with the login to the server. Give it a try and see if it helps or not.

**Comment by JosNun** [comment]
Thanks for the suggestion! Since I've added that mod, both times I've tried to connect have been successful. I haven't had the chance to do any more thorough testing, but so far, so good. :+1:

**Comment by TheMikey616** [comment]
how do we download mods to a mudpack on twitch

**Comment by TheMikey616** [comment]
I'm playing on 2.6.0
