### ISSUE TITLE
Crash apparently involving Oil Generator

### ISSUE THREAD

**Issue by TheFrostSeraph** [FTBTeam/FTB-Revelation-2#138]
* **Modpack Version**: Both 2.5.0 and 2.6.0

* **Issue**: While i was working on a canola energy generation system, the game crashed when i right clicked an EnderIO redstone conduit (although i had previously clicked), and actually, that doesnt seem to be the cause, it seems that its actually the Actually Aditions Oil Generator (look at the crash report).
I hope for some help in order to fix this bug.

* **Link to Log or Crash File Paste**:   https://paste.feed-the-beast.com/view/50cf3c32

* **Is it Repeatable?**: Since it first crashed it has happened every time i open the world, having tried the twich app "fix minecraft" tool and updating the pack and still isnt working.

* **Mod/s Affected**: Actually Additions

* **Known Fix**:

**Comment by tfox83** [comment]
This have been fixed in latest beta 2.7.0
