### ISSUE TITLE
Diamond Gears

### ISSUE THREAD

**Issue by Sketchsm** [FTBTeam/FTB-Revelation-2#139]
* **Modpack Version**: 2.5.0

* **Issue**: Diamond gear recipe is disabled by default. (assuming unintentionally) 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes. Recipes involving the diamond gear disabled in single player and multiplayer worlds. 

* **Mod/s Affected**: Industrial Foregoing. Laser Drill and Base as well as the recipe for the new Ore Meat processing machine are unavailable. 

* **Known Fix**: Enabling diamond gear recipe in teslacorelib.cfg.

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/50931457-77e7e400-1417-11e9-8d50-024032798505.png)
Works fine for me
