### ISSUE TITLE
Magic Bees some dont work

### ISSUE THREAD

**Issue by Fousicek** [FTBTeam/FTB-Revelation-2#140]
* **Modpack Version**: 2.5.0

* **Issue**: These bees dont have breeding pairs in JEI. Also you cant breed them just by knowing the pairs. And dont show the drops as well.

Gnawing
Galvanized - extict cant be bred
Impregnable - Cant br bred - GregTech4 bee ?
Invincible - Cant be bred - GregTech4 bee ?
Sodalite - Cant be bred - GregTech4 bee ?
Pyrite - Cant be bred - GregTech4 bee ?
Bauxite - Cant be bred - GregTech4 bee ?
Cinnabar - Cant be bred - GregTech4 bee ?
Sphalerite - Cant be bred - GregTech4 bee ?
Ruby
Sapphire
Resinous
Refined
Elastic
Caffeinated
Embitered - doesn show from which hive it drops
Tropical - doesnt show from which hive it drops
Ender - doesnt show from which hive it drops
Monastick - i think this one can be obtained only by trading with the villagers
Sorcerous - doesnt show from which hive it drops
Oblivion - doesnt show from which hive it drops
Osmium - not sure here, beacuse there is no Mekanism in modpack 
Silicon
Certus
Fluix
Botanic - doesnt show how to make one
Alfheim

* **Link to Log or Crash File Paste**: No log or crash file

* **Is it Repeatable?**: Yes it is

* **Mod/s Affected**: MagicBees

* **Known Fix**: Maybe ID clash ? Dont know. It is adding Gre

**Comment by Fousicek** [comment]
Oke found out that it is probably bug in MagicBees 
[https://github.com/ForestryMC/MagicBees/issues/69](url)

**Comment by Fousicek** [comment]
Can someone please try to fix the issue with magic bees ? As it seems there is no response. Thx

**Comment by tfox83** [comment]
Due to the complexity of NBT data I will need to wait on the dev to fix.
