### ISSUE TITLE
disconnected from server

### ISSUE THREAD

**Issue by minimin1122** [FTBTeam/FTB-Revelation-2#142]
* **Modpack Version**: 

* **I was breeding bees in industrial apiary automated with the card into draconic chest. At first while I was setting it up and seeing it go, it was fine. but after actual day passed by, the server gets disconnected.
I can still go to single player, and select the map and go into it with menu of esc showing, but as soon as I close the menu, it gets disconnected.
**: 

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/7ff40222

* **Is it Repeatable?**: 
yes. everytime

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
I will need the server logs in order to help.

**Comment by minimin1122** [comment]
I fixed the problem.

I think it was from actual addition mod that blocks the explosion within certain radius that crashes the server every time.
I have backup saves and when I loaded on without the block built yet, everything ran fine




________________________________
