### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by 08Shmelly80** [FTBTeam/FTB-Revelation-2#143]
* **Modpack Version**: 2.5.0

* **Issue**: Whenever I try to load the modpack it loads really slowly. Then when it eventually loads, I can't start playing because it just immediately crashes. This issue of the crashing has also hapened when I am even trying to load the pack. It may suddenly crash halfway through, 

* **Link to Log or Crash File Paste**: I'll put this on soon 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ?

* **Known Fix**: ?

**Comment by NHDriver4** [comment]
How much memory do you have allocated to your client? Paste your logs as well.

**Comment by tfox83** [comment]
Please assign at least 4GB to JAVA
