### ISSUE TITLE
Can't add fluid to Universal Wireless Terminal from WirelessCrafting Terminal

### ISSUE THREAD

**Issue by L0RIEN** [FTBTeam/FTB-Revelation-2#145]
* **Modpack Version**: 2.6

* **Issue**: the fluid upgrade only work with Extracell mod version that can;t be crafted anymore

* **Link to Log or Crash File Paste**: No crash occuring

* **Is it Repeatable?**: Everytime you use the AE2 fluid terminal won't work

* **Mod/s Affected**: Wireless Crafting Terminal, Applied Energistics 2

* **Known Fix**: Use one of your Extracell fluid terminal already existing to add fluid mode.

**Comment by tfox83** [comment]
Fixed in latest update
