### ISSUE TITLE
Crashing during load

### ISSUE THREAD

**Issue by Starhaven** [FTBTeam/FTB-Revelation-2#147]
* **Modpack Version**: 2.6.0

* **Issue**: the in window forge loader crashes on step 6/7 while it attempts to load jei log reports it runs out of ram my system has 8GB and your site recommends 4GB

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ec8389cc

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Just enough items

* **Known Fix**: I am unable to fix it myself

**Comment by AnEvasivePotato** [comment]
I am having the same issue

**Comment by Timetheos** [comment]
It seems like I can get by it by upping setting -Xmx5120m but then it runs like crap.

**Comment by XxThreshHookxX** [comment]
I have the same exact issue I have 16gb ram and this happens to me as well so hardly doubt its a ram issue but either a mod pack or setting issue. (kinda preffered the old FTB launcher vs this twitch app launcher BS.)

**Comment by Sunekaer** [comment]
@Starhaven it says you only have 3gb of ram assigned you need a minimum of 4 GB but ideally  5 or 6 GB:

**Comment by Starhaven** [comment]
@sunekaer how would I assign more then because I have plenty I can easily afford 6 GB

**Comment by Sunekaer** [comment]
Go to Twitch settings 
![image](https://user-images.githubusercontent.com/18720460/50693460-48ac2e00-1037-11e9-9ebf-8d512b7265b1.png)
