### ISSUE TITLE
Recipe Conflict with Thut's Elevator's manual

### ISSUE THREAD

**Issue by JakeCWolf** [FTBTeam/FTB-Revelation-2#148]
* **Modpack Version**: 2.6.0-1.12.2

* **Issue**: Recipe conflict

* **Link to Log or Crash File Paste**: No crash log.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thut's Elevators and mod that added "book to 2 paper" shapeless crafting recipe

* **Known Fix**: Creative mode seems to be the only thing that works, I tried the worktable from Forestry, but for some reason the book is listed as being from Minecraft and not ThutTech, so I can't switch recipes with the worktable.

**Comment by JakeCWolf** [comment]
It turns out JEI is displaying the recipe wrong, it's suppose to be the Linker and a book, which does work and gives you the manual, this is still an issue though so I won't be closing this.

**Comment by tfox83** [comment]
Ok its been reported, for some reason I cannot override this.  So hopefully one of the devs will get it sorted over time.
