### ISSUE TITLE
Lag Spikes after playing for an hour or so on a 1 gig server hosted in the UK (I'm East Coast US)

### ISSUE THREAD

**Issue by JakeCWolf** [FTBTeam/FTB-Revelation-2#149]
* **Modpack Version**: 2.6.0-1.12.2

* **Issue**: After hour-ish of playing game lags for 10ish seconds every 30 seconds to a minute, caused by various errors, possibly related to "entity spawning packets".

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9da6184f

* **Is it Repeatable?**: Yes and no. It happens to me and me alone, despite the fact that three others regularly play and don't have this issue at all.

* **Mod/s Affected**: I was told that "some mod (probably through coremodding) is messing up entity spawning packets" by a modpack dev on Discord, it's all the information I have on the specfics.

* **Known Fix**: Logging out and restarting my Minecraft (I use MultiMC). Logging out and back into the server alone doesn't fix it.

**Comment by tfox83** [comment]
I suggest at least a 3GB min server for this modpack.
