### ISSUE TITLE
Sponge Forge Compatibility

### ISSUE THREAD

**Issue by ShiftDed** [FTBTeam/FTB-Revelation-2#150]
* **Modpack Version**: 
2.6.0 Revelations
* **Issue**: 
Im having problems with the installation of sponge forge onto my server i was aware that that this was a issue with Revelations 2.5.0 But has it been fixed with the new 2.6.0 update?
* **Link to Log or Crash File Paste**: <!-- please use http://paste.feed-the-beast.com/ to paste the text of

**Comment by tfox83** [comment]
Sorry we are not able to support sponge since not all the mods we use support them.
