### ISSUE TITLE
Extra Trees leaves never ripe, no drops (2.6.0)

### ISSUE THREAD

**Issue by werybigmonk** [FTBTeam/FTB-Revelation-2#152]
Pack version: 2.6.0

Forestry Extra Trees grow normally, but leaves never ripe and no drops when trees are harvested by hand or by farms. 
Waila -style overlay shows some leaves as Unripe, some as Ripe. Bonemealing has an effect of changing that text and bonemeal stops working. Texture doesn't change and no drops come off if harvest is attempted.
If tree is planted on a multiblock farm, or arboretum, "products" harvest is attempted by the farm. This uses resources and energy and makes sound, but nothing is produced.
Trees native to Forestry mod (apple oak, hill cherry, common walnut, etc) work as expected.

First noted on server I host, tested on fresh install SP 

Log: Nothing related found, no crashes, errors or warnings.

Repeatable with freshly installed pack.

Mod affected: Binnie's Extra Trees / Forestry

**Comment by werybigmonk** [comment]
Updating Binnie's Mods to 2.5.1.x (and due to dependency, Forestry to 5.8.2.x) fixes this issue.

**Comment by tfox83** [comment]
THis is fixed in latest beta of the pack
