### ISSUE TITLE
Unable to start game, when launching it crashes at startup loading screen

### ISSUE THREAD

**Issue by VoreQor** [FTBTeam/FTB-Revelation-2#153]
Modpack Version: 2.6.0

Game does not launch and crashes after almost finishing the mod loading screen.

Crash Log: https://pastebin.com/GhrQRhcV

The issue has occurred every time i tried to launch the game, I have never launched it and always met with the same problem even in the previous version.

Reading the crash log I think NEI is the mod causing the issue.

**Comment by XxThreshHookxX** [comment]
I am having the same issue it stops of Loading - finishing up 6/7 on the Ender IO section. have you found a solution or work around as of yet? 
[crash-2019-01-03_10.18.57-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/2724748/crash-2019-01-03_10.18.57-client.txt)

**Comment by tfox83** [comment]
Please try a fresh install
