### ISSUE TITLE
ae2 fluix crystal creation

### ISSUE THREAD

**Issue by Panterh3art** [FTBTeam/FTB-Revelation-2#154]
with ae2 ur unable to automate the fluix crystal creation when using a dropper

when the items go trough a dropper

charged certus quartz + redstone + nether quartz 
then they don't work but when u throw them by hand they do work plz fix this because it's unable to play for me like this

**Comment by MarcJose** [comment]
It works still when using Formation/Annihilation Planes

**Comment by bahaynes** [comment]
In particular this issue: SonarSonic/Flux-Networks#239

That thread does mention disabling the flux via fire generation recipe should solve the problem.

**Comment by tfox83** [comment]
This has been fixed in latest beta 2.7.0 by disabling Redstone into lava recipe in Flux Networks.  I have also increased the drop rate of flux from mining redstone to offset this change.
