### ISSUE TITLE
Randomly stops responding during gameplay

### ISSUE THREAD

**Issue by Hard64** [FTBTeam/FTB-Revelation-2#155]
* **Modpack Version**: FTB Revelations 2.6.0

* **Issue**: The game keeps on freezing and stop responding during gameplay. Like, that comes with no warning, not because I did something wicked like spawning a lot of mobs. Happens out of nothing, the game just freezes, and that is it. Doesn't close by itself, I have to do it on the task manager or until Windows get tired and tells me to shut the process down. After that the whole pc gets slower, Twitch app stop working, explorer.exe resets. I think that got to do with the modpack, cause that doesn't happen with Infinity Evolved.
I already tried to increase RAM, it's up to 6 GB now, and that's the max safe for me (I got 8 GB total). CPU and GPU are not the problem, the game drops sometimes to 0 FPS, but it is usually at 200-300. I do think my old 2TB HD may be a cause of the problem, though.

* **Link to Log or Crash File Paste**: There is none, the game just freezes, no report.

* **Is it Repeatable?**: Yes. It can happen after 1 minute, or 2 hours, but always happens.

* **Known Fix**: Increasing the RAM usage may help you. Helped with the frame rates droping for me, but not the freezing.

**Comment by tfox83** [comment]
I will need a log file pastebin to look into this further

**Comment by PhilippCl** [comment]
Me + the 5 Players of my Server have this issue as well. The Problem really is: There is no log file as far as I can see it. The Server also shows no Signs of error. Seems to be a client only issue. I'm playing on 2.7.0-1 currently.

Edit:
The only evidence of the crash I could find(In the launcher_log.txt):
[0114/222523:INFO:GameCallbacks.cpp(199)] launcher/monitor (Process Monitor) fatal Process crashed with exit code -805306369

**Comment by Blucid** [comment]
I have a Private Server setup for 3-4 people, and the Client Hick-up / Stutter happens to all of us. We believe its the how the game handles RAM. On my personal computer I am almost up to 10GB of Ram allocated for FTB Revelation 2.6.0 and the stuttering doesn't happen right away, it takes a bit. After about an hour of gameplay the stutter starts to happen, small ones at the beginning and then the bigger ones where it freezes MC Sometimes.

If you hit F3, and check the RAM usage in the top right, we believe its the ram limit that's being hit by the MODS and MC, once it gets to 95-100% the stutter happens and then it clears the ram and keeps going. The less ram the sooner the stutter happens and more often, only way around this at the moment is to restart your client every hour or so depending on system specs.

**Comment by dabutant** [comment]
Having the same issue here, it started on a server so I moved it to singleplayer but it persists, totally locking up and is unplayable. Using 6gb RAM + GC args does nothing to stop it eventually. Only thing that works is restarting and hoping you'll get some play time in before it hits again. I haven't experienced this issue with a modpack that has over 100+ more mods.

**Comment by adveres** [comment]
Can confirm it appears to be garbage collection.  I had allocated 6GB, and with the `F3` menu up, you can observe it freezes right near the max RAM, right before that goes back down (due to a GC).

I'm not sure how to fix this besides having a less memory-intensive pack, or throwing more RAM at it.
