### ISSUE TITLE
Refined Storage/Reborn Storage ignores Thermal Foundation liquid buckets

### ISSUE THREAD

**Issue by LazarusCore** [FTBTeam/FTB-Revelation-2#156]
* **Modpack Version**: <2.6.0>

* **Issue**: <Refined Storage/ Reborn Storage auto crafting does not recognise Thermal Foundation liquid buckets when present as patterns or as items within the storage system.  Forces manual crafting of the steps that have these liquid buckets.

This bug is present when using RS Crafters and Reborn multiblock crafters

![glowstone_bucket](https://user-images.githubusercontent.com/2916839/50544655-96edb580-0c62-11e9-8d21-25a1b31e6fb3.JPG)
![rstc_interaction](https://user-images.githubusercontent.com/2916839/50544656-96edb580-0c62-11e9-8eb4-f7becac45965.JPG)
>

* **Is it Repeatable?**: < Yes: Repeated by multiple people on this server>

* **Mod/s Affected**: <Refined Storage, Reborn Storage, Thermal Foundation. Nil pack modifications>

* **Known Fix**: <Nil>

**Comment by tfox83** [comment]
This is fixed in latest
