### ISSUE TITLE
Morbs/Florbs Recipe missing from JEI and Creative inventory

### ISSUE THREAD

**Issue by SamuelGTurner** [FTBTeam/FTB-Revelation-2#157]
* **Modpack Version**: 2.6.0

* **Issue**: When searching in the JEI for the COFH Morbs or Florbs, the item does not show. The recipe still works from the one listed on the COFH website but this was the only way to find the recipe. The Morbs and Florbs also aren't accessible through the creative inventory.

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: Yes, search "morbs" in JEI

* **Mod/s Affected**: Thermal Expansion (COFH)

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 2.7.0 by showing empty florb/morb
