### ISSUE TITLE
Crash on Mod Load

### ISSUE THREAD

**Issue by XxThreshHookxX** [FTBTeam/FTB-Revelation-2#158]
* **Modpack Version**: 2.6.0
* **Issue**: Crashes while loading mod packs on start up always crashes at loading 6/7

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d975e815
* **Is it Repeatable?**: Happens on every launch have done multiple uninstall re-installs still no fix

**Comment by dvyd98** [comment]
You need to allocate more RAM, if im reading right you only allocated 2,7GB, that's nowhere near as the minimum needed.

**Comment by tfox83** [comment]
As the user above stated, you need at least 4GB of RAM allocated to JAVA
