### ISSUE TITLE
[Refined storage] Crafting monitor disconnecting player when autocrafting

### ISSUE THREAD

**Issue by tonalom** [FTBTeam/FTB-Revelation-2#159]
* **Modpack Version**: 2.6.0

* **Issue**: Whenever a refined storage system is performing an autocrafting task, and a player opens up the crafting monitor at the same time. It seems that the player simply gets disconnected from the server they are on. I was able to recreate the issue multiple times in a row.

* **Link to Log or Crash File Paste**: 
[Client log for rs disconnect.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/2725627/Client.log.for.rs.disconnect.txt) Apologies for not making it a link. The log is long, therefore pastebin did not allow it to be posted in it's entierity.

* **Is it Repeatable?**: Yes, the issue is repeatable

* **Mod/s Affected**: Refined storage and any other mod that it is autocrafting an item from.

* **Known Fix**: For this one, I do not know of a solution.

**Comment by tfox83** [comment]
Fixed in next update
