### ISSUE TITLE
Crash when searching up "Thermal Expansion" on JEI or going past page 122

### ISSUE THREAD

**Issue by TrickyHeart** [FTBTeam/FTB-Revelation-2#160]
* **Modpack Version**: 2.6.0

* **Issue**: JEI crashes when searching up @ ThermalDynamics or going past page 122 on JEI

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/abbbea14
* **Is it Repeatable?**: I was able to repeat the searching issue 3 times, third time I actually had to reinstall the modpack. I've only tested going past page 122 once. edit: twice. it happened twice when going to page 123.

* **Mod/s Affected**: Likely Thermal Dynamics and JEI, Extra utilities?

Edit: Still occurs even after reinstalling.
Edit 2: Others have had the same issue on a server I play on.

**Comment by Shybella** [comment]
That's because either you or the server you're on disabled Extrautils2 Cursed Earth in the EU2 config.

**Comment by tfox83** [comment]
The server will need to do a fresh install or revert any changes
