### ISSUE TITLE
Updated World 2.6.0 with 2.7.0 and cannot produce "Flux" (item)

### ISSUE THREAD

**Issue by Vintschente** [FTBTeam/FTB-Revelation-2#166]
* **Modpack Version**: 2.7.0

* **Issue**:  When throwing redstone into fire it should give back flux but instead it just burns the redstone.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Flux Networks

Can anyone confirm?

**Comment by xordac** [comment]
This is in the changelog, doesnt mean I like the change but it is there to fix a different issue:
Changes:
-Hid all but Stone AE Facades from JEI
-Empty Morb/Florb now visible in JEI; closes #157
-Disabled Flux from dropping redstone into lava; closes #154
-Increased drop rate of flux from mining redstone to 32
-Fixed recipe for Essence of Scornful Oblivion; closes #134
-Added Hammer recipes for Thaumcraft plates; closes #127

**Comment by Vintschente** [comment]
I am sorry I thought the lava doesn't include fire. I even read the changelog before...

**Comment by Karmalefique** [comment]
so we just need to mining redstone to get some flux ?

**Comment by InfinitiesLoop** [comment]
Unfortunately increasing the drop rate doesn't do much to mitigate turning it off. That drop rate doesn't seem to come into play when using a builder to quarry, for example. You essentially could exchange redstone for flux 1:1 before. The mod requires tons and tons of flux for its recipes. So this problem pretty much cripples the mod -- it basically may as well not be in the pack.
