### ISSUE TITLE
My server is lagging horribly after update

### ISSUE THREAD

**Issue by TheGodJobless** [FTBTeam/FTB-Revelation-2#17]
* **Ftb-Revelation-2.0.0**

*FTB Server lagging after update ****: 

* **https://paste.feed-the-beast.com/view/adbf7354**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 
* **Known Fix**:

**Comment by 016Nojr** [comment]
Is pregen enabled?
'07.06 13:59:36 [Server] Server thread/INFO [net.minecraft.server.dedicated.DedicatedServer]: /chpregen current|dimID xDiameter zDiameter xStartChunk zStartChunk [chunksPerTick, default 5] [preventJoin, default true]'

**Comment by TheGodJobless** [comment]
I have the chunk generator mod and i try using pregen to fix it but all it does is crash the server or times me out

**Comment by 016Nojr** [comment]
I would try without that chunk generator
