### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by HostileBlimp** [FTBTeam/FTB-Revelation-2#170]
* **Modpack Version**: 2.6.0

* **Issue**: Server crashes randomly while in Twilight Forest

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/dc28526e

* **Is it Repeatable?**: It has occurred multiple times but is not due to one action as far as i can tell

* **Mod/s Affected**: I believe Twilight Forest

* **Known Fix**:

**Comment by rune-san** [comment]
This is a strange bug that's still undergoing investigation to determine what exactly is going on where. At this current point, it appears to be an issue with Forge, and OpenJ9. See TeamTwilight/twilightforest#660 and MinecraftForge/MinecraftForge#5254

Java 8 is still widely deployed, built on, and supported. My recommendation would be to move back to the latest OpenJRE 8 release until the situation around Java 11 and modded Minecraft is better sorted.
