### ISSUE TITLE
Iron Backpacks mod in the Revelation modpack not working.

### ISSUE THREAD

**Issue by Velojun** [FTBTeam/FTB-Revelation-2#172]
* **Modpack Version**: <FTBRevelation-2.7.0-1.12.2>

* **Issue**: <The Iron Backpacks mod is not properly working, its missing the key feature of being able to use the backpack upgrades,    also not all items from this mod appear in the revelation mudpack,  missing most of the backpack upgrades/addons   and those few that do show up in NEI dont work...
(Like for example the "nesting upgrade" to be able to put backpacks into each other)>

* **Is it Repeatable?**: <yes its an issue in every new world in this mod pack>

* **Mod/s Affected**: <Iron Backpacks mod is not fully functional and misses key features>

* **Known Fix**: <it seems like its not properly being installed by the mod pack>

**Comment by mcilhargey** [comment]
This is likely because the mod itself isn't fully updated to 1.12 yet per https://minecraft.curseforge.com/projects/iron-backpacks . You should look to https://github.com/gr8pefish/IronBackpacks for statuses there
