### ISSUE TITLE
FTB Revelation 2.7.0 flux/quarry issue

### ISSUE THREAD

**Issue by repka3** [FTBTeam/FTB-Revelation-2#173]
* **Modpack Version**: FTB Revelation 2.7.0 (release)

* **Issue**: RFTool quarry doesn't mine flux while mining redstone. Redstone ores don't drop flux via quarry.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: rftools-1.12-7.59
fluxnetworks-1.12.2-3.0.19-21

* **Known Fix**:  The only way to get flux is manually mining the redstone ore. So for automate flux you need silk touch quarry, late game. I think the balance is a little bit off in this way.

**Comment by Karmalefique** [comment]
Are you sure about that ? Beacause i'm mining redstone for one hour and i didn't get it...

**Comment by sniperagent1** [comment]
I am also having the same issue, however I think the bigger issue here is that the tooltip for flux (that being that you obtain flux by throwing redstone into fire or lava) is a lie as throwing redstone into fire or lava just results in the loss of said redstone. Have to resort to using administrative powers to spawn in the flux after throwing said redstone into fire/lava, not ideal.

**Comment by Adrian-Turjak** [comment]
This is affecting me, and I've even tried having a mechnical miner or user (with a pickaxe) mine/place the block, but that doesn't trigger a drop either...

I've also opened: https://github.com/SonarSonic/Flux-Networks/issues/283

As this has been broken for a long time and as useful as this mod is, it really needs a better recipe for flux generation that doesn't cause as much pain or bugs, and can be automated.

**Comment by Adrian-Turjak** [comment]
@tfox83 would it be possible to add a recipe for flux without changes to the mod itself? Like maybe redstone and coal or something. Or even maybe add flux as a byproduct when pulverising redstone ore?

Plus at the very least, you should probably change the modpack defaults for drop rate to be much much more often. I've tweak them to 2 (every second block), but with a min drop of 1, and a max of 3. That would make the amounts you get smaller, but more consistent than the current 32, and 4-14.

**Comment by 1pandora234** [comment]
So I experimented and a stone ax, diamond, or regular pick ax, no flux drops with over 50 blocks of Redstone. The Fluxbore or Wyvern ax no flux drops. The only way I can get flux so far is by like said above mining with a tinkers construct pick ax.
