### ISSUE TITLE
Client cant connect / times out most of the time

### ISSUE THREAD

**Issue by Maxus1998** [FTBTeam/FTB-Revelation-2#175]
* **Modpack Version**: 2.7.0

* **Issue**:
Client times out when connecting to the Server

I Play together with 2 to 3 Friends. Two of them don't have much trouble when connecting (the usually have to join two times because it only works the second time), Situation for me is the same, altough I am hosting the server on the same machine I am playing on it.
My third friend has continuous problems when connecting to the server. The Log Always says

Netty SERVER IO #X/ERROR [FML] NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[Server thread/INFO] [minecraft/NetHandlerPlayServer]: playerName lost Connection: Timed out

Most of us use 16GB of RAM, but my friend unfortunately has only 8GB. But in my opinion that should be enough as I am Hosting the server + playing the game, what also worked when just assigning 6GB to the game itself.
Is there any fix for this problem? It is really annoying and we already tend to stop playing because after 3 days he spent more time trying to connect + starting the game than playing on the server...

**Comment by Dodowido** [comment]
I had the same problem. This server-side mod fixed it for me: https://minecraft.curseforge.com/projects/random patches
It increases the time the client has to connect to the server.

**Comment by realvictorprm** [comment]
I can confirm both the problem and the solution for this. Again FTB Revelation badly needs performance patches. However I don't know yet where the bottleneck lies.

**Comment by Sheldor5** [comment]
Can confirm the problem.
Login only works on second attempt.

**Comment by the-rogue** [comment]
Can confirm the solution works, however for anyone who can't get the random patches mod put onto the server, and can't login after more than 2 attempts, try adding this to your java arguments: 
-Dfml.readTimeout=90
