### ISSUE TITLE
Large performance dip when updating from 2.6 to 2.7

### ISSUE THREAD

**Issue by Steampunk-Wizard** [FTBTeam/FTB-Revelation-2#176]
* **Modpack Version**: Revelation 2.6 and 2.7

* **Issue**: Very large hit to framerate when updating the pack from version 2.6 to 2.7. My group of friends noticed this when some of us with worse computers were suddenly unable to play on our Revelation server. Narrowed the issue down to the updated pack, and tested it across multiple computers with varying specs.

Testing Methodology: Created a new single player world in Revelation 2.6, and recorded the average FPS when the world loaded in. Moved the save of that same world to the 2.7 version and recorded the average FPS once more.
Note: (Everyone is running 64bit Windows 10)

Case 1: (Same Graphics settings)
FPS on 2.6: ~370
FPS on 2.7: ~280
Specs:
Intel i7 7700k 4.5ghz
Nvidia GTX 960(4GB)
480GB SSD
16GB DDR4(6GB allocated to modpack)
-
Case 2: (Same Graphics settings)
FPS on 2.6: ~220
FPS on 2.7: ~170
Specs:
Intel i5 7600k 4.7ghz
Nvidia GTX 1070
1TB SSD
16GB DDR4(8GB allocated to modpack)
-
Case 3: (Same Graphics settings)
FPS on 2.6: ~120
FPS on 2.7: ~50
Specs:
Intel i7 3770
AMD Radeon RX 480(4GB)
256GB SSD
16GB DDR3 (8GB allocated to modpack)
-
Case 4:
FPS on 2.6: ~100 ("max" Graphics at 12 chunks)
FPS on 2.7: ~10 ("min" Graphics at 8 chunks)
Specs:
Intel i5 3570
AMD Radeon RX 480(8GB)
1TB HDD
8GB DDR3(6GB allocated to modpack)
-
Case 5: (Same Graphics settings)
FPS on 2.6: ~25
FPS on 2.7: ~3
Specs:
AMD A10-6800K
AMD Radeon HD 5700
120GB SSD
16GB DDR3(8GB allocated to modpack)
-
* **Is it Repeatable?**: Every computer suffered a rather large hit to performance when updating.

* **Mod/s Affected**: Completely Unknown

**Comment by realvictorprm** [comment]
That doesn't look good.
Moreover I think the overall performance of the FTB Revelation Modpack for older PC's needs improvement.

Is someone familiar with increasing FPS for Modpacks? I would love to get a crasp of where the bottlenecks are.
