### ISSUE TITLE
OV/OD scanner from IE2 doesn't work

### ISSUE THREAD

**Issue by firestormone** [FTBTeam/FTB-Revelation-2#178]
* **Modpack Version**: 2.7.0-1.12.2

* **Issue**: OV/OD scanner from IE2 show no results, and when put into a mining machine crashes the game. I have looked into it and it is conflicting with AsteralSorcery

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d2ff51bc

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Craft2, AsteralSorcery

* **Known Fix**: Switching off AsteralSorceryfixes it

**Comment by PetNoire** [comment]
known fix 2: updating ic2.
