### ISSUE TITLE
Forge Issue

### ISSUE THREAD

**Issue by Keaton1188** [FTBTeam/FTB-Revelation-2#18]
* **Modpack Version**:  2.0.0

* **Issue**:  We are having some issues with getting the server booting up with the latest forge that was included with the server+files pack.

* **Link to Log or Crash File Paste**:   https://imgur.com/a/N8ieTK9

* **Is it Repeatable?**:  Yes 

![untitled](https://user-images.githubusercontent.com/24898745/41132164-648411ea-6ab7-11e8-9965-b255ce425fab.png)

**Comment by 016Nojr** [comment]
Can you post it to gist.github.com or pastebin.com?

**Comment by Hojosa** [comment]
Update the library folder with the one, that was included in the update zip.
