### ISSUE TITLE
Game crashes during loading screen

### ISSUE THREAD

**Issue by Fyrexia** [FTBTeam/FTB-Revelation-2#183]
* **Modpack Version**: FTBRevelation-2.7.0-1.12.2

* **Issue**: During the loading of the modpack, it crashes on crazypants.enderio.base.intergration, ender IO - Dark Steel Upgrades
With this error, "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)"

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/1b18484b

* **Is it Repeatable?**: Yes it happens everytime, on the same part

* **Mod/s Affected**: crazypants.enderio.base.intergration, ender IO - Dark Steel Upgrades
![image](https://user-images.githubusercontent.com/47077661/51799706-25b20b80-21ea-11e9-8cca-18bfc0bbb025.png)

* **Known Fix**:

**Comment by M0rtale** [comment]
Navigate to your launch options and allocate more memory to Xmx and Xms.
