### ISSUE TITLE
2.7.0 AstralSorcery GetProgress Exception

### ISSUE THREAD

**Issue by M0rtale** [FTBTeam/FTB-Revelation-2#184]
* **Modpack Version**: "forgeVersion": "2796", "mcVersion": "1.12.2", "packVersion": "2.7.0", "packID": "FTBRevelation", "xml": "modpacks"

* **Issue**: One of my players in the server placed a [luminator](https://wiki.industrial-craft.net/index.php/Luminator) on the floor, The server then proceeds to crash with Exception 

`java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?`

That the stack trace points to the function getProgress getProgress in Astral Sorcery by TileEntityLuminator.checkPlacement(which somehow invokes ic2.getplayer). More details can be seen in the log.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d84c3ea1

* **Is it Repeatable?**: The server can no longer function properly as everytime the chunk that contains the laminator is loaded(that player joins and stands next to it), the server crashes with the same exception with the same stack trace.

* **Mod/s Affected**: IC2, Astral Sorcery

* **Known Fix**: Not that I know of as I can delete neither of the mod packs(they are extensively used)

**Comment by M0rtale** [comment]
I have tried to download the world and remove the luminator locally but it proceeded to crash my game whenever I get close to the luminator(chunk load)

**Comment by PetNoire** [comment]
I'm getting the same exception on my server. Not sure if an illuminator is involved as I haven't personally used AS, but perhaps someone else has it. There is a new version of as out, hopefully the lack gets updates with it soon

**Comment by M0rtale** [comment]
> I'm getting the same exception on my server. Not sure if an illuminator is involved as I haven't personally used AS, but perhaps someone else has it. There is a new version of as out, hopefully the lack gets updates with it soon

By updating IC2 to the latest version I was able to solve it, but the mods have to changed.

**Comment by PetNoire** [comment]
If you update it and solve the problem, can you roll it back to at least run the server until it is updated?

**Comment by M0rtale** [comment]
I am not sure what you mean by that.

> If you update it and solve the problem, can you roll it back to at least run the server until it is updated?

**Comment by PetNoire** [comment]
i just tested what i meant.
you can update ic2 and run it, then, in my case, i had to disable a miner with an OV scanner. after that, i could restore the ic2 version so the clients didnt need to be updated so we can at least play until the pack updates
