### ISSUE TITLE
Extreme Reactors Recipes Missing

### ISSUE THREAD

**Issue by Akua89** [FTBTeam/FTB-Revelation-2#187]
Modpack Version: 2.7.0

Issue: Recipes missing for Yellorium Ingot (Yellorium Ore is there though), the only way to make it is by putting a Yellorium Block in a crafting grid (which also cannot be made, save by 9 ingots). The alternate fuel, Uranium Ingots, also missing its recipe (Uranium Ore drops itself and does not smelt, even when crushed). This is the second modpack I've seen this issue in (it's also present in ATM3). The game doesn't crash, so there's no crash log file to submit.

Is it Repeatable?: Yes.

Mod/s Affected: Extreme Reactors

**Comment by FiveEYZ** [comment]
Had no problem to crush the Uranium/Yellorium Ore using a SAG Mill from ender io dont use a Macerator, the SAG Mill made it to Uranium Grit and could be smelted down to Refined Uranium.

Refined Uranium can be used just like Yellorium Ingots, 

hope this helps, gl
