### ISSUE TITLE
Shift-Clicking Polished Stone Into Resonator Crashes Game

### ISSUE THREAD

**Issue by rjrobertson** [FTBTeam/FTB-Revelation-2#189]
* **Modpack Version**: 2.7.0

* **Issue**: When shift clicking Polished Stone into a Resonator, the game will crash (seemingly from the SE Binary from crashing, as this is the error that everyone in our server got when recreating this.)

* **Is it Repeatable?**: Very. Any time anyone in our server did this, it happened.

* **Known Fix**:  Not so much or a fix, but if you click the stone in, it doesn't cause issues.

**Comment by cryobane** [comment]
Still an issue in any Extra Utilities machine in Revelation. Fixed by manually updating to the latest Extra Utilities release.
