### ISSUE TITLE
RFTools tablet + remote storage module = hang

### ISSUE THREAD

**Issue by dm8mydog** [FTBTeam/FTB-Revelation-2#19]
* **Modpack Version**: 2.0.0

* **Issue**: RFTools Tablets when used with remote storage modules -always- hang/kill the game session when attempting to add/remove items.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes, in old world and in fresh world

* **Mod/s Affected**: RFtools

* **Known Fix**:  none yet

**Comment by tfox83** [comment]
How much RAM do you have assigned?  I dont seem to have this issues in the test/dev world

**Comment by dm8mydog** [comment]
8gb
