### ISSUE TITLE
Massive Lag spikes 

### ISSUE THREAD

**Issue by bobthecow111** [FTBTeam/FTB-Revelation-2#193]
* **Modpack Version**: 2.7

* **Issue**: Massive lag spikes they happen out of no where and have little to no reason to start i am allocating over 6gb of ram and have monitored my ram usage and it never goes above 80%. Most of the lag spikes come completely out of nowhere as just walking aroun my base or some times when opening up a UI. The Lag spikes cause the game to freeze from about a mere 2 secs at minimum up to never as they go until i give up waiting. I cant find a way to repeat it as ill do the same thing i did before it crashed and it will work just fine. I have good hardware on my Laptop and that shouldnt be a problem. if it is i have a Alienware 17 R3
Specs:
 GTX 975M
8 GB of ram 
Intel Core i7 6700HQ Cpu thats 4 core and is 2.60 GHz

* **Link to Log or Crash File Paste**:there is normaly never a crash but it did happen once as here i do have more than one report thou since i normaly end the freezing with taskmanager and it considers it a crash... here is the most recent one... 
https://pastebin.com/zexfq79K

* **Is it Repeatable?**:No i cannot as it is random.

* **Mod/s Affected**:Idk if any mods are the direct cause i havent added any mods nor removed any.

* **Known Fix**:only if...

and a pre thanks to who ever helps.

**Comment by TheDerpyMinekraftUtuber** [comment]
When loading up the game and going into a world, How long does it take until the Lag Spikes happen?
