### ISSUE TITLE
Unstable and Unplayable

### ISSUE THREAD

**Issue by Shady-Milkman88** [FTBTeam/FTB-Revelation-2#195]
Have been playing on Revelation 2.7 for a few weeks. Lately I have been unable to play due to the game going at 1FPS and massive Lag. I have uninstalled and reinstalled the modpack as well as Java multiple times with multiple machine restarts. I have attempted dedicating 6GBs, 10GBs and 12GBs to Minecraft and still unable to have any work on any configuration. When pressing F3 to monitor, it is only utilizing 40%-67% depending on how long I let it sit, but never fully renders environment or gets away from the 1FPS issue. Plus load times have been appearing to be excruciatingly longer it appears.  
Computer Specs:
AMD Ryzen Threadripper 1950X
32GBs RAM
Radeon RX Vega
Windows 10 64bit

* **Modpack Version**: 2.7

* **Issue**: Was working but lately all old saves and new worlds run at 1FPS.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/33c29b9b

* **Is it Repeatable?**: Yes unable to play or access so happens every time I boot the game

* **Mod/s Affected**: all

* **Known Fix**: if you know of a fix please let me know! Thanks

**Comment by Hojosa** [comment]
Could be foamfix/mipmap settings. 
Try setting MipMap to 0 in your Video Settings->Quality.
