### ISSUE TITLE
Tinker construct tank don't form

### ISSUE THREAD

**Issue by CorwinCZ** [FTBTeam/FTB-Revelation-2#200]
* **Modpack Version**: 2.7.0

* **Issue**: Tinker construct tank formed by template from manual doesn't work. This is known issue in Tiker construct, already fixed on their side - [their bug](https://github.com/SlimeKnights/TinkersConstruct/issues/3719). This bug is affesting other FTB modpacks - [FTB Continuum bug](https://github.com/FTBTeam/FTB-Continuum/issues/528)
Please see attached screenshots of my set-up at the end of bug report.

* **Link to Log or Crash File Paste**: No crash-log

* **Is it Repeatable?**: yes - build tinkers tank by description in manual

* **Mod/s Affected**: Tinkers construct in version 2.12.0.113, please see [original bug in their repo](https://github.com/SlimeKnights/TinkersConstruct/issues/3719)

* **Known Fix**: upgrade Tinkers construct to version 2.12.0.115

![tinkerbug1](https://user-images.githubusercontent.com/2243025/53503265-055ac280-3ab0-11e9-87aa-81445e91737a.png)
![tinkers2](https://user-images.githubusercontent.com/2243025/53503266-05f35900-3ab0-11e9-86d3-671ad8057650.png)
![tinkers3](https://user-images.githubusercontent.com/2243025/53503267-05f35900-3ab0-11e9-9bdb-b0c922b6da73.png)

**Comment by Raidobw2** [comment]
Same bug on FTB Revelation 2.7.0. (TConstruct v113). Upgrading TConstruct to version 2.12.0.115 fixes this issue.
