### ISSUE TITLE
Placing a vanilla water bottle in potion brewer (industrial foregoing) crashes and breaks world

### ISSUE THREAD

**Issue by Flinkyflonky** [FTBTeam/FTB-Revelation-2#201]
* **Modpack Version**: 
2.7.0
* **Issue**: 
Placing a vanilla water bottle in potion brewer (industrial foregoing) crashes and breaks world
There appears to have been another issue with the potion brewer but it was apparently fixed in 2,7.0 maybe relatable

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/77e521a1

* **Is it Repeatable?**: 
Step 1. Place Potion Brewer(Industrial Foregoing) in world connected to power so it charges up
Step 2. Place stack of Netherwart in potion brewer (probably not important)
Step 3. Place vanilla water bottle in Potion brewer trying to fill its internal tank 
=*Crash*=

* **Mod/s Affected**:  
====
Industrial Foregoing
particularly this issue https://github.com/Buuz135/Industrial-Foregoing/issues/413 is probably of some use to you guys
The industrial foregoing dev says some other mod is making this possible as it's not supposed to be possible to place a water bottle in the machine
======
* **Known Fix**:

**Comment by panenw** [comment]
this bug is not fixed in latest versions, update to teslacore ver>=1.0.16  is needed
