### ISSUE TITLE
Flux not Dropped from Redstone Ore 

### ISSUE THREAD

**Issue by HarleBlue** [FTBTeam/FTB-Revelation-2#207]
Me and a friend are playing on an FTB Revelations server and Flux does not drop from Redstone Ore when mined by hand. There is no other way I currently know how to aquire Flux. Is there a config that we have missed or is Flux not available on servers?

Mod Pack: FTB Revelations 2.7.0
Mod: Flux Networks

**Comment by Adrian-Turjak** [comment]
The default config does allow it to drop from redstone, but something like every 32 blocks mined. It's a terrible default considering how easy it is to make when you can throw it in fire.

It has come up before multiple times: #173 

For my personal server I have my deployment tools alter the config for flux networks (`flux_networks.cfg`):
```
flux_recipe {
    # the chance of a drop occurring (random, but roughly every 50 blocks) [range: 1 ~ 5000, default: 50]
    I:"Chance of Flux Drop (from Redstone Ore)"=3

    # enables Redstone being turned into Flux when dropped in fire [default: true]
    B:"Disables Flux Recipe (from fire)"=false

    # enables Redstone Ore to drop Flux with normal redstone drops [default: true]
    B:"Enable Flux Drop (from Redstone Ore)"=true

    # the maximum Flux dropped from Redstone Ore if a drop occurs [range: 1 ~ 64, default: 16]
    I:"Maximum Flux Drop (from Redstone Ore)"=4

    # the minimum Flux dropped from Redstone ore if a drop occurs [range: 1 ~ 64, default: 4]
    I:"Minimum Flux Drop (from Redstone Ore)"=1
}
```

I've set it to drop every 3 blocks when mined by hand (quarries don't work...), but to drop between 1-4 when it drops. You may want to tweak those numbers yourself.
