### ISSUE TITLE
IC2 cables reverting and recipes disappearing

### ISSUE THREAD

**Issue by Shyhog** [FTBTeam/FTB-Revelation-2#209]
* **Modpack Version**: <Revelations 2.7.0 -->

* **Issue**: all of the cable types for IC2 have reverted to older versions (ie tin is a 5 eu/t copper is at 32 eu/t) and several recipes are missing such as that of the CESU, insulated tin cable, and smelting crushed tin ore into ingots. This issue happened suddenly with no obvious error messages or causes.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes this happened on both my server and singleplayer
* **Mod/s Affected**: IC2 version 2.8.73 -ex112

**Comment by momochone** [comment]
Seeing the same issue, all of a sudden happened today. Mostly to do with IC2, Thermal Centrifuge recipe missing

**Comment by momochone** [comment]
Create a thread in FTB fourm, another person seems to be having same issue.

https://forum.feed-the-beast.com/forum/ftb-revelation.274/
