### ISSUE TITLE
EnderIO fluid tanks GUI does not working Multiplayer Servers

### ISSUE THREAD

**Issue by Tempus-Dominus** [FTBTeam/FTB-Revelation-2#21]
* **Modpack Version**: FTBRevelation-2.0.0-1.12.2 

* **Issue**: EnderIO fluid tanks (also pressurized ones) will not show there GUI on multiplayer servers 

* **Link to Log or Crash File Paste**: Timestamp for first issue is 00:40:46 near the very bottom of the logs.
Debug Log - [debug.log](https://github.com/FTBTeam/FTB-Revelation-2/files/2089126/debug.log)
Server Log - [latest.log](https://github.com/FTBTeam/FTB-Revelation-2/files/2089123/latest.log) 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: EnderIO

* **Known Fix**: A server restart (apparently).

**Comment by tfox83** [comment]
Fixed in next update
