### ISSUE TITLE
Crash on JourneyMap 5.5.3 => update to 5.5.4

### ISSUE THREAD

**Issue by simchanu29** [FTBTeam/FTB-Revelation-2#216]
* **Modpack Version**: `2.7.0`

* **Issue**: the player is locked out of server after a crash involving a change of dimension. On the logs (unfortunately I restarted the server without the mod since) I've noticed a synchronization issue on the mod JourneyMap between server and client with the same trigger : a player moved from one dimension to another, client crash and after that cannot connect anymore. 

* **Link to Log or Crash File Paste**: (working on it)

* **Is it Repeatable?**: It happens when a player change dimension. It's hard to reproduce now since as a quick fix I have deleted the mod from the server to prevent a player to stay locked out of server. 

* **Mod/s Affected**: JourneyMap

* **Known Fix**: Pass JourneyMap to 5.5.4 or delete mod JourneyMap serverside.
https://github.com/TeamJM/journeymap/issues/42

**Comment by rickdgray** [comment]
This bug is so bad. Can we please get this update added?
