### ISSUE TITLE
It's time for another update

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Revelation-2#218]
Basic mod update is near required now.

**Comment by DanCo1** [comment]
We desperately need an update to this pack so badly.

**Comment by TitanTheOriginal** [comment]
There are major updates for many of the larger mods as well as fixes for issues that are desperately needed for this pack.

**Comment by Crueldog** [comment]
I definitely agree, we need an update please!

**Comment by tfox83** [comment]
3.0.0 is avail as beta, but will require a world reset.

**Comment by Shybella** [comment]
tfox83 you are gold, these are great changes

thank you so much
