### ISSUE TITLE
Redstone Dupe AE2

### ISSUE THREAD

**Issue by endemie** [FTBTeam/FTB-Revelation-2#22]
* **Modpack Version**: 2.0.0

* **Issue**: If i transfere Redstone from one Interface to another, for the production of Fluix Crystals (AE2), there is a Redstone in the second interface, that duplicates if pulled to the Formation plane. 

* **Link to Log or Crash File Paste**: there is no crash... i just have billions and billions of Redstone everyhere...

* **Is it Repeatable?**: yes... i've build the whole system many times with new parts and on other places... always more redstone...

* **Mod/s Affected**: AE2 (Applied Energistics 2) and maybe FluxNetworks

* **Known Fix**: not really... i found that https://github.com/SonarSonic/Flux-Networks/issues/155

and this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3105/

and this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2175

**Comment by tfox83** [comment]
Its been reported multiple time on the devs, if they produce a fix ill get it in, if not then I cant do anything about it.
