### ISSUE TITLE
I seem unable to find any iron ore

### ISSUE THREAD

**Issue by DeeDoubleYous** [FTBTeam/FTB-Revelation-2#221]
3.0.0

When I generate a world I am unable to find any iron ore in the world. Similarly I can't find any gold ore. I could find modded ores fine such as tin, copper, aluminium, iridium, poor ores as well as redstone, lapis and coal.

I gened multiple worlds and seemed unable to find any ore.

**Comment by Secretony** [comment]
Same problem here.

**Comment by thomasd1979** [comment]
Ditto. Tried mining vast areas. Nothing.

**Comment by punkathet** [comment]
same here multiple worlds no iron or gold but have come across some railcraft poor iron ore

**Comment by digi-tal-it** [comment]
Can confirm, same problem here. No iron, no gold!

**Comment by GrumpyChunks** [comment]
It is generating, but the chances are very low. Refresh JER by running the /profile command, and after reloading the game, iron seems to peak at 0.035% chance of spawning, which is way too low. Gamemode 3 (and night vision) confirms it is generating, just at a really low rate.

**Comment by DeeDoubleYous** [comment]
That still feels like a bug. If I am unable to find iron or gold, then I can't use them, because I can't find them.

**Comment by ImStabby** [comment]
Iron and gold being rare looks like due to railcraft by default disabling uniform ore gen and using veins for those ores. Got normal ore gen after changing line 585 of the railcraft config to "I:vanillaOreGenChance=100" which going by the config I assume is default iron and gold settings.

**Comment by Secretony** [comment]
> Iron and gold being rare looks like due to railcraft by default disabling uniform ore gen and using veins for those ores. Got normal ore gen after changing line 585 of the railcraft config to "I:vanillaOreGenChance=100" which going by the config I assume is default iron and gold settings.

Made this change then went to a new chuck and can confirm Iron reappeared. thanks!

**Comment by tfox83** [comment]
This is fixed in 3.0.1 releasing later today

**Comment by stephanrenggli** [comment]
This seems to be only fixed in the client configs, not in the latest server.
So servers still won't be generating iron.
