### ISSUE TITLE
Server startup is taking forever due to a repeated warning of duplicated recipes.

### ISSUE THREAD

**Issue by Velineste** [FTBTeam/FTB-Revelation-2#222]
2.7.0

Server startup is taking forever due to a repeated warning of duplicated recipes.

When the server starts, a lot of warns like this appears, making the server really slow to start.

The supplied recipe BasicManyToOneRecipe [output=3xitem.item_alloy_ingot@9, recipe=Recipe [input=[RecipeInput [input=1xitem.tier9_items@5, useMeta=true], RecipeInput [input=1xitem.ingotIron@0, useMeta=true], RecipeInput [input=1xitem.thermalfoundation.material@134, useMeta=true]], output=[crazypants.enderio.base.recipe.RecipeOutput@63731f2a], energyRequired=10000]] for Alloy Smelter may be a duplicate to: BasicManyToOneRecipe [output=3xitem.item_alloy_ingot@9, recipe=Recipe [input=[RecipeInput [input=1xitem.thermalfoundation.material@134, useMeta=true], RecipeInput [input=1xitem.ingotIron@0, useMeta=true], RecipeInput [input=1xitem.tier9_items@5, useMeta=true]], output=[crazypants.enderio.base.recipe.RecipeOutput@63731f2a], energyRequired=10000]]

The server takes around 20-30 minutes to start, which should normally never take more than 10.

**Comment by tfox83** [comment]
That should not affect the speed of boot, I am able to boot in under 3 minutes on multiple test servers.  Please try a different server or a fresh install.
