### ISSUE TITLE
Quark GUI Highlight Not Showing in Correct Locations

### ISSUE THREAD

**Issue by GrumpyChunks** [FTBTeam/FTB-Revelation-2#223]
* **Modpack Version**: 3.0.0

* **Issue**: The new Quark feature that highlights GUI containers that items can't be placed in, is sometimes located in the wrong location. With a tinker's crafting station, hovering over an item, it appears in the correct location (i.e. over the craft output slot), but when you pick up an item from the inventory, the red box moves to the wrong location (see screenshot)

* **Link to Log or Crash File Paste**: There's no crash, it's a cosmetic issue.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Quart (version shipped with 3.0.0 of FTB Revelation)

* **Known Fix**: Disable this new feature in quark? (it is quite annoying too)

* **Additional Info**: I'm using MacOS Mojave using a retina display (if that makes a difference)

![2019-05-15_13 51 34](https://user-images.githubusercontent.com/1747010/57777067-dc45e780-7718-11e9-8519-5e160a924d91.png)

**Comment by tfox83** [comment]
Changed this in 3.0.1 to only show when holding shift
