### ISSUE TITLE
Crash: Extra Utilities 2 causing client crashes when shift-clicking upgrades

### ISSUE THREAD

**Issue by Thanpren** [FTBTeam/FTB-Revelation-2#224]
* **Modpack Version**: 2.7.0

* **Issue**: Shift-clicking upgrades in _any_ Extra Utilities devices causes game to freeze and forces me to kill the game. For instance: I have 4 speed upgrades in my inventory. There is 1 in the node already. If I try to shit-click those in my inventory in the item node, my game will try to put all 4 in the node, which doesn't work as you can only put 4 at max. Same with 2 stack upgrades in a node. Tried on a server, doesn't crash the server, but causes heavy freeze. My PC might be the "issue": what I mean is that a stronger PC might just freeze but not until the end of times. 

* **Link to Log or Crash File Paste**: https://pastebin.com/Pt7RRdsi In multiplayer, the server doesn't crash. There is no auto-restart to my knowledge. (I installed the server myself on a VPS). But the crash has been done in singleplayer.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra utilities 2

* **Known Fix**: None to my knowledge.

**Comment by GrumpyChunks** [comment]
I've also seen this problem with StoneBlock 2, there's a number of bug reports detailing similar behaviour on the EU2 issue tracker.

https://github.com/rwtema/Extra-Utilities-2-Source/issues/294
https://github.com/rwtema/Extra-Utilities-2-Source/issues/260
https://github.com/rwtema/Extra-Utilities-2-Source/issues/232
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226
https://github.com/rwtema/Extra-Utilities-2-Source/issues/155

**Comment by Thanpren** [comment]
I haven't notice this on other maintained and recent modpacks, but I may
have not encounter this situation at all. That's why I was thinking this
was a modpacks' problem for some reason.
Sorry for spamming then, next time I'll check both modpack and mod
respective issue trackers.
Thanks for the quick reply.

Le mer. 15 mai 2019 20:46, BinaryCrafter <notifications@github.com> a
écrit :

**Comment by GrumpyChunks** [comment]
It might be down to the modpack @Thanpren, just posting an observation I've made with a similar issue in other modpacks. I'm no expert, so I could well be wrong. :)

**Comment by tfox83** [comment]
Will get this fix in if ever fixed by EXU, its present in other packs as well.

**Comment by tfox83** [comment]
closing as its likely to never be fixed
