### ISSUE TITLE
Quark trashcan duplicates the one already present in FTB Utilities

### ISSUE THREAD

**Issue by GrumpyChunks** [FTBTeam/FTB-Revelation-2#225]
* **Modpack Version**: 3.0.0

* **Issue**: The quark trashcan feature recently added to quark, is redundant in FTB Revelation, as the same feature already exists in FTB Utilities.

* **Link to Log or Crash File Paste**: No crash, cosmetic issue

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Quark, version as installed with FTB Revelation 3.0.0

* **Known Fix**: Disable this feature in Quark, as the Quark trashcan can conflict with GUIs and JEI. The FTB Utilities one doesn't seem to interfere with anything.

**Comment by tfox83** [comment]
disabled in 3.0.1
