### ISSUE TITLE
Please do not remove OpenComputers

### ISSUE THREAD

**Issue by twothe** [FTBTeam/FTB-Revelation-2#228]
I have noticed that in the upcoming 3.0 version of Revelation OpenComputers is removed. As a server owner I like OpenComputers much more compared to ComputerCraft. Aside from some personal design favorites, OpenComputers is significantly more friendly on server resources and can be configured to the last detail in case you have issues. On the other hand ComputerCraft is well known to cause all sorts of issues and malicious scripts can easily take down the entire server.

So please stick with OpenComputers instead of ComputerCraft.

**Comment by Moondarker** [comment]
I agree on this one. Just updating OC to latest version to solve HDD caching issue from 2.7.0 would be the best solution, I believe

**Comment by Alchemichai** [comment]
I really love OC as it has way more depth than CC. I love the geolyzer, and hologram projector and those components are necessary for my latest build. From everything i've heard, OC is easier on servers... So I don't understand replacing it entirely... Can CC and OC not coexist?

**Comment by twothe** [comment]
They can easily co-exist.

**Comment by Warhawker** [comment]
Let's just remove some core mods and add some other ones while we "update" this pack
Pretty poor decision making.

**Comment by tfox83** [comment]
OC was causing alot of issues in previous versions on servers thus CC:tweaked was suggested.  You may add OC back in yourself if you wish but I cannot support it, sorry
