### ISSUE TITLE
Random Server Crash

### ISSUE THREAD

**Issue by lays24mc** [FTBTeam/FTB-Revelation-2#232]
Hi,

the server crashed random, but not often. 

* **Modpack Version**: 3.0.1

* **Link to Log or Crash File Paste**: https://pastebin.com/LaGGRMVH

* **Is it Repeatable?**: no, its random

* **Mod/s Affected**: I think Thaumcraft Aura (see crashlog)

**Comment by rune-san** [comment]
It may not be Thaumcraft, or at least the crash log there isn't necessarily confirmation. Finding the process that causes the time-out can often require Profiling.

That stated, you have a *lot* of RAM assigned to the Java instance. Perhaps too much. I don't know how many players you have on your system. Once you get so high in memory allocation you get to the point that Garbage Collection itself can stall out your processes for too long.

Can you try a more reasonable amount of RAM, such as 6GB assigned, and see if the behavior continues?

**Comment by tfox83** [comment]
Correct, decrease RAM to 6-8GB and try profiling to find the issue if its still crashing
