### ISSUE TITLE
A Chunk kills my server every time I load it.

### ISSUE THREAD

**Issue by Jared2350** [FTBTeam/FTB-Revelation-2#233]
* **We are using FTB revelation 3.0.1 release version**: 

* **Here is the server crash I watch live:
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [99, -76] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [100, -74] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [99, -74] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [100, -75] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [99, -75] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN - FML :: MrTJPCore loaded a new chunk [100, -77] in dimension 0 (overworld) while populating chunk [98, -74], causing cascading worldgen lag.
Server thread/WARN - FML :: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server Watchdog/FATAL - minecraft/ServerHangWatchdog :: A single server tick took 60.00 seconds (should be max 0.05)
Server Watchdog/FATAL - minecraft/ServerHangWatchdog :: Considering it to be crashed, server will forcibly shutdown.
Server Watchdog/ERROR - minecraft/ServerHangWatchdog :: This crash report has been saved to: /home/mc58802/bin/Minecraft/./crash-reports/crash-2019-05-23_21.21.07-server.txt
Server Shutdown Thread/INFO - minecraft/MinecraftServer :: Stopping server
Server Shutdown Thread/INFO - minecraft/MinecraftServer :: Saving players
main/INFO - FML :: Searching /home/mc58802/bin/Minecraft/./mods for modsp
**: 

* **Link to Log or Crash File Paste**: 

* **It is very much repeatable**: 

* **All of them?**: 

* **Not loading the chunk.**:

**Comment by twothe** [comment]
Sounds like a volcano to my. Try setting volcano generation in Project-Red Core config to `false`

Honestly this should be disabled by default as volcano generation is an insane lag-spike for servers.
