### ISSUE TITLE
Uranium, Yellorite, Zinc not spawning

### ISSUE THREAD

**Issue by Maltish** [FTBTeam/FTB-Revelation-2#234]
* **Modpack Version**: 3.0.1

* **Issue**: After swapping to 3.0.1 my friends and I have noticed that uranium, yellorite and Zinc are not spawning. I have done the yellorite fix found in a previous issue however Zinc still have no spawn rate. (Zinc is from railcraft and is needed to craft multiple items from that mod including an electrice locomotive). Just wondering if a fix is on the way or if there is a way I can increase the spawn rate of uranium and yellorite.
* **Mod/s Affected**: IndustrialCraft 2 and Railcraft

**Comment by poulhp** [comment]
Read what i wrote near the buttom about changeing how much spawns on regards to yellorium/uranium.
https://github.com/FTBTeam/FTB-Revelation-2/issues/227

The fix for zinc sould be pretty easy just add the info to cofh config file since that govens the world/oregen.

**Comment by Maltish** [comment]
Thanks, for the reply :)
Just looked at the thing you wrote and fixed up the spawns. However I can't figure out how to add zinc. Is the zinc info for the cofh config available anywhere? As I don't really know what to write.

Again, thanks for the reply :)

**Comment by poulhp** [comment]
No since zinc is just added in the newest railcraft edition there isnt any info online about it. And if you dont know how to find that info ingame its pretty hard to explain. 
Are you sure that the thing cant be build with another type of ore?

I know i can fix it but i wont have time until monday.

**Comment by Maltish** [comment]
Unfortunately brass is required to build it, which can only be made using zinc and copper so there doesn't seem to be a way to craft it otherwise. But it's not the end of the world as my friends and I are happily working on our reactor now that we have uranium again :)

Thanks so much for the help, thank you for your hard work

**Comment by poulhp** [comment]
Can you check for me if zinc isnt a by product from grinding down tin?

**Comment by poulhp** [comment]
},
		"resonating": {
			"distribution": "uniform",
			"generator": {
				"block": "deepresonance:resonating_ore",
				"material": "stone",
				"cluster-size": 2
			},
			"cluster-count": 2,
			"min-height": 16,
			"max-height": 32,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
	        "Zinc": {
			"distribution": "uniform",
			"generator": {
				"block": {
					"name": "railcraft:ore_metal",
					"metadata": 5
				},
				"material": "stone",
				"cluster-size": 8
			},
			"cluster-count": 4,
			"min-height": 10,
			"max-height": 35,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}
    }
}

This sould spawn in the zinc ore, i have tested it and it works.
I set the spawn rate the same as lead.
I included the other ore type cuse I wrote it in at the buttom so you dont have to change all the }/{ if you just copy the entire thing in and paste it on top of the exsisting text.
If it dont work you didt copy it correct, remeber to backup before changeing the file.
Its the 04_overworld_ores in the config\cofh\world folder.

**Comment by Maltish** [comment]
Just finally got around to trying it, at first I thought it didn't work but nope I was wrong! Zinc is spawning and working :) Thank you so much for your help and work. I'll be back on business to building my locomotive now!

**Comment by poulhp** [comment]
You are very welcome

**Comment by tfox83** [comment]
this is fixed in 3.1.0, also zinc is avail in world gen now to make RC more early game

**Comment by sllllllp** [comment]
> ```
> 	},
> 	"resonating": {
> 		"distribution": "uniform",
> 		"generator": {
> 			"block": "deepresonance:resonating_ore",
> 			"material": "stone",
> 			"cluster-size": 2
> 		},
> 		"cluster-count": 2,
> 		"min-height": 16,
> 		"max-height": 32,
> 		"retrogen": "true",
> 		"biome": "all",
> 		"dimension": {
> 			"restriction": "blacklist",
> 			"value": [
> 				-1,
> 				1
> 			]
> 		}
> 	},
>         "Zinc": {
> 		"distribution": "uniform",
> 		"generator": {
> 			"block": {
> 				"name": "railcraft:ore_metal",
> 				"metadata": 5
> 			},
> 			"material": "stone",
> 			"cluster-size": 8
> 		},
> 		"cluster-count": 4,
> 		"min-height": 10,
> 		"max-height": 35,
> 		"retrogen": "true",
> 		"biome": "all",
> 		"dimension": {
> 			"restriction": "blacklist",
> 			"value": [
> 				-1,
> 				1
> 			]
> 		}
> 	}
> }
> ```
> 
> }
> 
> This sould spawn in the zinc ore, i have tested it and it works.
> I set the spawn rate the same as lead.
> I included the other ore type cuse I wrote it in at the buttom so you dont have to change all the }/{ if you just copy the entire thing in and paste it on top of the exsisting text.
> If it dont work you didt copy it correct, remeber to backup before changeing the file.
> Its the 04_overworld_ores in the config\cofh\world folder.

what if you dont have the file called "04_overworld_ores" in cofh world folder? Currently i'v only got these files
![image](https://user-images.githubusercontent.com/51764009/130387859-3ac03eb2-09ec-4a24-9223-22e0d0a70a38.png)
