### ISSUE TITLE
Blood Magic Mod Update

### ISSUE THREAD

**Issue by julianubico** [FTBTeam/FTB-Revelation-2#238]
* **Modpack Version**: 3.0.1 

* **Issue**: https://github.com/WayofTime/BloodMagic/issues/1544

* **Link to Log or Crash File Paste**: N/A 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Blood Magic 

* **Known Fix**: Update Blood Magic to the latest version, [Download Link](https://minecraft.curseforge.com/projects/blood-magic/files/2713291)

**Comment by tfox83** [comment]
Will be updated in next pack update, 3.1.0
