### ISSUE TITLE
Red Rock from Cobblestone not Stone with Inductive Furnace

### ISSUE THREAD

**Issue by FaiThiX** [FTBTeam/FTB-Revelation-2#24]
* **Modpack Version**: 2.0.0

* **Issue**: When smelting Cobblestone in a "Inductive Furnace" from ProjectRed-Exüamsion you will get "Red Rock" from "Traverse" and not "Stone".

![57bb3d35-0f6c-4e68-806b-bd6786024684](https://user-images.githubusercontent.com/22944855/41289193-4655d678-6e49-11e8-9c86-e1e280db0531.png)

* **Link to Log or Crash File Paste**: no crashlog

* **Is it Repeatable?**: Yes, place a Inductive Furnace and put Cobblestone in it

* **Mod/s Affected**: ProjectRed-Expansion, Traverse

* **Known Fix**: Dont know

**Comment by tfox83** [comment]
Submitted to moddev

**Comment by tfox83** [comment]
Fixed in 2.1.0
