### ISSUE TITLE
Game Crashing after teleport from another world

### ISSUE THREAD

**Issue by pikizin** [FTBTeam/FTB-Revelation-2#240]
* **Modpack Version**: 
3.0.1

* **Issue**: 
every time i teleport from another world games crashes. but some times dont crash... is random...

* **Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/2e7fe53d

* **Is it Repeatable?**:  yeah , every time i teleport from another world games crashes.

* **Mod/s Affected**:

**Comment by tfox83** [comment]
Seems to be a one off, you may need to regen that world that is crashing
