### ISSUE TITLE
Red Hover 

### ISSUE THREAD

**Issue by Jakooobus** [FTBTeam/FTB-Revelation-2#241]
* **Modpack Version**: 3.0.1

* **Issue**: if you hover over an item with while you shift click , every item in a chest/me/etc. has a red backround and it tilts me really hard . if you know how to disable it i would be rly thankfull .

* **Link to Log or Crash File Paste**: no need

* **Is it Repeatable?**: -

* **Mod/s Affected**:- 

* **Known Fix**: -

**Comment by tfox83** [comment]
you can disable in the quark config if you would like
