### ISSUE TITLE
RFTools Spawner and Matter Beamer not fully functional/working

### ISSUE THREAD

**Issue by xWaller19** [FTBTeam/FTB-Revelation-2#242]
* **Modpack Version**: 
3.0.1

* **Issue**:
RFTools Spawner and matter beamers are not transfering "Live Matter" from the matter beamer to the spawner. Both "Key Matter" and "Bulk Matter" work but the Live matter doesn't seem to want to be injected/put into the spawner. And yes, the beamers ARE linked to the spawner and it DOES have a syringe in it (Endermen in this case).

![Desktop Screenshot 2019 06 01 - 10 58 15 64](https://user-images.githubusercontent.com/26192302/58751478-3dc9be00-845c-11e9-8e48-7124f7799590.png)

* **Link to Log or Crash File Paste**: 
Playing on a multiplayer server. This is a pack issue because I tested it on singleplayer.

* **Is it Repeatable?**:
There's only one issue. (so far)

* **Mod/s Affected**:
Mods being used:
RFTools

* **Known Fix**:
No idea. Thats why I came here.

**Comment by SpencerGFord** [comment]
Im having the same issue. Let me know if you find a solution, thanks!

**Comment by cjfreeze** [comment]
I have this same issue

**Comment by Mesqi** [comment]
Having this exact same issue.

**Comment by VADemon** [comment]
FTB Revelation 3.2.0, default configs: same problem.
**Fix: Delete the config and let it regenerate.**

Looks like the config had minor changes to other unrelated values e.g. `D:dimensionCostFactor=5.0 → S:dimensionCostFactor=5.0` but it breaks the Matter Beamer's ability to transfer living matter...

Both configs, the fixed one has values adapted from the modpack (only `storageconfig` has been modified compared to mod's defaults): https://gist.github.com/VADemon/7844e8bed26b9d9ab581dad796034942

Same issue in RFTools bug tracker: https://github.com/McJtyMods/RFTools/issues/1943

**Comment by 016Nojr** [comment]
Config regenerated in a pack update coming in a few days
