### ISSUE TITLE
Railcraft rock crusher doesn't connect to any power source

### ISSUE THREAD

**Issue by spaceshooter** [FTBTeam/FTB-Revelation-2#243]
* **Modpack Version**: 3.0.1

* **Issue**: Railcraft rock crusher doesn't connect to any power source. Tried Buildcraft, Thermal expansion, Industrial Craft

**Comment by xWaller19** [comment]
This might help you,

![300px-Rock_crusher_screenshot](https://user-images.githubusercontent.com/26192302/58753400-cc016c80-847b-11e9-96d0-e4206f565bf7.jpg)

If you search Kinesis in the JEI menu, it should give you the conductive pipes you need powered via BuildCraft

**Comment by spaceshooter** [comment]
Reply to deleted @xWaller19's comment. None of energy pipes or wires connect to Rock crusher, tried almost anything.
![2019-06-02_18 43 02](https://user-images.githubusercontent.com/49607410/58761554-69859a80-8567-11e9-9060-606e0a5053a6.png)

P.S. Found on the Internet that Railcraft uses it's own energy called Railcraft Charge from 9.3.0.0, but Railcraft's steam turbine still generating RF in 12.0.0.
![2019-06-02_18 58 26](https://user-images.githubusercontent.com/49607410/58761875-a2733e80-856a-11e9-9995-1ee235fcf6da.png)

Moreover, "Official Railcraft Wiki!"(railcraft.info) says that in 9.4.0.0 Rock Crusher has been converted to RF power
![Screenshot_14](https://user-images.githubusercontent.com/49607410/58761905-f9791380-856a-11e9-868f-c37a2af027de.png)

**Comment by tfox83** [comment]
Seems to work in testing for me with RC
