### ISSUE TITLE
[Mod Suggestion] Add AE2 Stuff back

### ISSUE THREAD

**Issue by triffman33** [FTBTeam/FTB-Revelation-2#244]
## Why add it back?

It is an extremely helpful and powerful addon to AE2, enhancing the player experience. Despite it not having an update for some time now, does not mean it is a broken mod. I've not had any issues with it personally but if there is an actual issue that arises due to it being outdated, then, at least I tried.

**Comment by poulhp** [comment]
Why not just add it yourself?

**Comment by triffman33** [comment]
Adding a mod to your client doesn't do anything if its not on the server as well.

**Comment by poulhp** [comment]
So ask the person running the server if they can add it?

**Comment by triffman33** [comment]
The no one will be able to connect unless they also manually install the mod which will drastically decrease the amount of people playing on it since many will not be willing to do an extra step just to play on that specific server.

**Comment by poulhp** [comment]
So? Not sure I see the problem, the server im running have no problems with me adding extra stuff that people ask for. They get a msg when trying to connect if they are missing a mod, they add it and join again, or dont add it and dont play on my server anymore.

**Comment by triffman33** [comment]
As I said previously, it would drastically decrease the amount of players who will play, I am not the server owner or in any position to ask the network owners to add a mod that will mean many players having issues trying to connect when every other pack we have doesn't require any manual editing. Not every server is run by someone who can just be pm'd when an issue arises. 

Please stop creating an issue out of nothing, there was and still is no reason for you to be replying, your server is completely separate from the suggestion to the pack devs to add a mod back into the pack.

**Comment by poulhp** [comment]
Fine, just trying to help you by giving you some advice on what you could do, wont happen again.
