### ISSUE TITLE
Duplicated recipe. Computer Craft / Chisel (futura block)

### ISSUE THREAD

**Issue by pikizin** [FTBTeam/FTB-Revelation-2#246]
* **Modpack Version**: 
3.0.1
* **Issue**: 
Duplicated Recipe.

* **Link to Log or Crash File Paste**: 
![Screenshot_4](https://user-images.githubusercontent.com/51034518/58768302-8faf3880-856f-11e9-9ec7-a3018d4b6f1f.png)
![Screenshot_2](https://user-images.githubusercontent.com/51034518/58768303-8faf3880-856f-11e9-8344-a481c19d88f1.png)

* **Is it Repeatable?**: 

* **Mod/s Affected**: 
Computer Craft
Chisel
Applied Energistics

* **Known Fix**:

**Comment by xWaller19** [comment]
I had this problem aswell just to second this issue. If anyone has a fix, post it! :D

**Comment by krakah** [comment]
I'l third this.

**Comment by Minecr4ck** [comment]
Since its been a month and no reply from the FTB team, I would recommend just changing it in the scripts. 
OR use a forestry worktable!
![2019-07-09_07 12 00](https://user-images.githubusercontent.com/26249745/60887133-3646c300-a219-11e9-83fe-42cbaadd338e.png)

**Comment by tfox83** [comment]
fixed in 3.1.0
