### ISSUE TITLE
RFtools:Builder cant be Infused in Machine Infuser

### ISSUE THREAD

**Issue by Silverrain2004** [FTBTeam/FTB-Revelation-2#25]
* **Modpack Version**: FTBRevelation-2.0.0-1.12.2

* **Issue**: 

I tried to put RFtools:Builder in Machine Infuser, 
but nothing happens.. but other RF Machines are working (to infuse)

* **Is it Repeatable?**:  

just try to put a Builder in Machine Infuser.

* **Mod/s Affected**: 

RFtools

**Comment by GWSheridan** [comment]
This has been fixed in an upcoming update v2.1.0
