### ISSUE TITLE
Modpack missing ProjectRed Compat (Causing Computercraft Issue)

### ISSUE THREAD

**Issue by DaMrZ** [FTBTeam/FTB-Revelation-2#250]
* **Modpack Version**: Latest Version: 3.0.1

* **Issue**: The ProjectrRed Bundle Cables do not connect to the ComputerCraft computers due to ProjectRed Compat not being installed

* **Link to Log or Crash File Paste**:  This issue does not cause the client to crash it just does not connect

* **Is it Repeatable?**: Yes try placing it next to a computer

* **Mod/s Affected**: 
CC:Tweaked Any version (Including latest)
Project Red

* **Known Fix**: The known fix from Squid (Dev of CC:Tweaked) is to install ProjectRed compat.
I have provided a screenshot of the convo

![image](https://user-images.githubusercontent.com/4590454/59163556-99e6af00-8afa-11e9-97c3-0d3b9ce8571d.png)

![image](https://user-images.githubusercontent.com/4590454/59163564-a7039e00-8afa-11e9-9588-fbb12a05ea98.png)

**Comment by Neil-HD** [comment]
Can confirm am having the same issue with being unable to connect bundled cables to computercraft computers and spent several hours troubleshooting  before i figured out it was this

**Comment by tfox83** [comment]
PR Compact has been added in next update
