### ISSUE TITLE
Server Version Railcraft Config Ore-generation Setting

### ISSUE THREAD

**Issue by DwarfsLord** [FTBTeam/FTB-Revelation-2#252]
This problem has been solved in 3.0.1 for clients, but not for servers.

"This seems to be only fixed in the client configs, not in the latest server.
So servers still won't be generating iron."

_Originally posted by @stephanrenggli in https://github.com/FTBTeam/FTB-Revelation-2/issues/221#issuecomment-497133548_

**Comment by tfox83** [comment]
fixed in 3.1.0
