### ISSUE TITLE
Game crash, An unexpected issue occurred and the game has crashed.

### ISSUE THREAD

**Issue by msxd** [FTBTeam/FTB-Revelation-2#253]
* **Modpack Version**: 3.0.1

* **Issue**: game crashed due to unexpected error

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/26ed47f4

* **Is it Repeatable?**: Every time

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by fguillod** [comment]
I had the same crash when I opened a world created with a version prior to 3.0
The issue did not occur with a brand new 3.0.1 world.

**Comment by msxd** [comment]
> I had the same crash when I opened a world created with a version prior to 3.0
> The issue did not occur with a brand new 3.0.1 world.

Minecraft does not start. I click "play" in the launcher and after few second has error "Game crash, An unexpected issue occurred and the game has crashed."
 
Screenshot: http://prntscr.com/o37wg8

**Comment by rune-san** [comment]
According to the log, it's not seeing a proper installation.

`[14:35:38] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[14:35:38] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.`

It appears that one way or the other your installation is broken. On a fresh installation from Twitch, it should download the pack, then once you select to play the first time and launch it should download all the Vanilla bits from Minecraft's repositories. From the log above, it does not appear that is happening correctly. Have you attempted another clean install?

**Comment by msxd** [comment]
> It appears that one way or the other your installation is broken. On a fresh installation from Twitch, it should download the pack, then once you select to play the first time and launch it should download all the Vanilla bits from Minecraft's repositories. From the log above, it does not appear that is happening correctly. Have you attempted another clean install?


i was remove all minecraft files, reinstall twitch app, and install minecraft again, and now it's work, thank you
