### ISSUE TITLE
Crash when looking at leadstone fluxduct with thermal dynamics cover in hand, every time.

### ISSUE THREAD

**Issue by Realmm** [FTBTeam/FTB-Revelation-2#254]
* **Modpack Version**: 3.0.1

* **Issue**: Every time I look at a leadstone fluxduct with a thermal dynamics cover (made with structuralducts and the block you want it to look like) in my hand, the game crashes, every time. In fact, because it made me crash, I can't log into the game anymore, because I crashed while holding the cover in my hand and looking at the leadstone fluxduct.

* **Link to Log or Crash File Paste**: https://pastebin.com/tQ6k8UJV

* **Is it Repeatable?**: Yes, just look at a leadstone fluxduct with a cover in your hand.

* **Mod/s Affected**: Thermal Dynamics presumably

* **Known Fix**: Not a clue

**Comment by triffman33** [comment]
Whenever there's a crash that includes rendering while optifine is installed, its usually optifines fault. Try removing the mod to see if it fixes it since optifine and forge dont like eachother very much.

**Comment by tfox83** [comment]
This is a Optifine issue, please remove
