### ISSUE TITLE
Can't cast Soul Shards molten corruption from Tinker's Construct smeltery

### ISSUE THREAD

**Issue by LockTheCollector** [FTBTeam/FTB-Revelation-2#255]
Version 3.0.1

I smelted some corrupted ingots from Soul Shards Respawn in the TConstruct smeltery hoping to cast a sword blade, and found that there was no way to actually cast the molten corruption, I then saw that the tinkers parts added by soul shards didn't have any of the casting recipes that the other tinker's tool parts do.

**Comment by tfox83** [comment]
I have blocked them in next version

**Comment by executionByFork** [comment]
I just ran into this same issue, and I was wondering why these items are blocked?
