### ISSUE TITLE
Reliquary charm bug, srever crash.

### ISSUE THREAD

**Issue by tetriesidva** [FTBTeam/FTB-Revelation-2#257]
* **Modpack Version**: feed the beat revelations 3.0.1.

* **Issue**:reliquary mob , while having zombie charm equiped , the server will crash after you hit another type of zombie mob ( villager zombie , husk etc.= -->

* **Link to Log or Crash File Paste**: don t really know how to find it on my server 

* **Is it Repeatable?**: yes 
* **Mod/s Affected**: reliquary i guess
* **Known Fix**:  don t know

**Comment by rune-san** [comment]
This issue is referenced in the Reliquary issue tracker:
P3pp3rF1y/Reliquary#355

It does not look as if cause has been concretely determined. It could be a Forge issue, as it appears in reading the thread that at least one other mod out there has similar problems. Could be a while for this one.

**Comment by tetriesidva** [comment]
well i wanted to point it out , to give you guys heads up. I don t really know much about it , only the mod is really great and me and my friends are liking it a lot. So keep up the good work, and hopefully this will get fixed. That baubles belt is such a good items , shame it doesn t work. Thanks for fast response , gl.

**Comment by tfox83** [comment]
Looks to be fixed by the dev.  I have the latest version in the next update due out in a couple days
