### ISSUE TITLE
Feral Lamp causes Botania particles to multiply too much

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Revelation-2#258]
* **Modpack Version**: FTB Revelation 3.0.1

* **Issue**: When the additional lights created by the feral lamp when it spreads reach any botania block that generates particles, it generates even more particles causing some people near these blocks to lag

* **Link to Log or Crash File Paste**: No crash, just lag

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: TorchMaster and Botania

* **Known Fix**: Destroy the feral lamp, use the frozen pearl to remove remaining lights, then relog to refresh your client (no need to restart the game)

* **Images**:
![image](https://user-images.githubusercontent.com/8612968/59931550-cb0a9c00-9477-11e9-84c8-09b7613ec950.png)

![image](https://user-images.githubusercontent.com/8612968/59931513-af9f9100-9477-11e9-83fd-95591b9979b8.png)
![image](https://user-images.githubusercontent.com/8612968/59931525-b9c18f80-9477-11e9-9551-18439438b49b.png)

**Comment by tfox83** [comment]
Disable particle effects in options
