### ISSUE TITLE
im confused and i want to play this pack

### ISSUE THREAD

**Issue by Kirbyception** [FTBTeam/FTB-Revelation-2#259]
the mod is ftb revelation

* **Modpack Version**: 3.0.1

* **Issue**: i want to allocate more ram but went i try to click view profile to do so the button doesnt work. but it works with my other pack

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Known Fix**: n/a

**Comment by rune-san** [comment]
You should probably post a screenshot of what you're seeing. This sounds more like a Twitch issue than a Pack issue.

**Comment by 3216100** [comment]
I had the same problem while following a tutorial. Instead of right-clicking the modpack icon, just click the text below the image. That will take you to the same screen that "View Profile" is supposed to. Then, click the gear in the top right, and choose "Profile Options." Hope that helps!
