### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by WheelieInNeutral** [FTBTeam/FTB-Revelation-2#260]
Revalations 3.0.1

The is absolutely no audio. Not in the main screen, single player, or multi player.

Ive tried reinstalling, F3+s, Audio still works in vanilla.

Seems to be a common issue with the older packs but i cant find a fix for this version.

**Comment by tfox83** [comment]
I have no way of reproducing this, seems to be an issue with your system/java not the modpack
