### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by polishpower** [FTBTeam/FTB-Revelation-2#265]
hi,

Ive just downloaded the revelations modpack but when i try to start it up it always crashes at the same point(see image below)
![](https://i.gyazo.com/d40d63d697b3a5a0014c1425347d0dc0.png)
and i get this crash report:
### **_**The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)**_**

how can i fix this?

**Comment by rune-san** [comment]
At the top you show your total Memory is "2869MB". this is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

Increase your RAM allocation in Twitch to between 4 and 6GB and try again.
