### ISSUE TITLE
Railcraft Steel Shovel is not craftable..

### ISSUE THREAD

**Issue by gbartz** [FTBTeam/FTB-Revelation-2#266]
* **Modpack Version**: 3.01

* **Issue**: Steel Shovel (Railcraft) is not craftable - The Steel Shovel required for Adv. Item Loader and Adv. Item Unloader.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Railcraft

* **Known Fix**: Add the recipe.

**Comment by CitiesXL2815** [comment]
steel shovel is disabled in Railcraft due to another steel shovel from Thermal Expansion

**Comment by tfox83** [comment]
@CitiesXL2815 is correct
