### ISSUE TITLE
FTB Relevation server error HELP

### ISSUE THREAD

**Issue by NotBev** [FTBTeam/FTB-Revelation-2#267]
* **Modpack Version**: FTB Relevation 3.0.1

* **Issue**: Cant load in server

* **Link to Log or Crash File Paste**:none as of now

* **Is it Repeatable?**: yes every time i try

* **Mod/s Affected**: the error says enderio but idk what the texts means

* **Known Fix**: idk how to fix it
here are the SS of the errors
![2019-07-01_20 39 39](https://user-images.githubusercontent.com/52434056/60478395-94d7d400-9c50-11e9-9653-d6bc1e140704.png)
![2019-07-01_20 39 33](https://user-images.githubusercontent.com/52434056/60478396-94d7d400-9c50-11e9-8c3f-0a45ee0b69ec.png)

**Comment by rune-san** [comment]
This place is mostly for tracking issues with FTB Revelation itself, vs. assisting with general usage. That said, have you checked the version of the server? I see this sometimes when people are trying to connect a client that is running a different Forge or Pack version than the server.

**Comment by NotBev** [comment]
yeah it says there the same as far as i can tell, anyway you could screen share or something?
