### ISSUE TITLE
Yellorite and Uranium not spawning 3.0.1

### ISSUE THREAD

**Issue by Frolist** [FTBTeam/FTB-Revelation-2#268]
* **Modpack Version**: 3.0.1

* **Issue**:  yellorite and uranium not spawning 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**:  Extreme Reactors 0.1.5.66 industrial craft 2-2.8  

* **Known Fix**:

**Comment by GrumpyChunks** [comment]
Duplicate of #227

**Comment by tfox83** [comment]
Fixed in 3.1.0
