### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Mooreaoth** [FTBTeam/FTB-Revelation-2#269]
* **FTBRevelation-3.0.1-1.12.2
**: 
* **Issue**: 

* **
[crash-2019-07-03_09.41.37-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/3353649/crash-2019-07-03_09.41.37-server.txt)
**:

**Comment by Mooreaoth** [comment]
server not opening

**Comment by rune-san** [comment]
You should always fill out the entirety of the issue template when creating issues.

Your log shows your total Minecraft assigned memory is 1,979MB.
`Memory: 430637624 bytes (410 MB) / 1152196608 bytes (1098 MB) up to 2075918336 bytes (1979 MB)`
This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

Increase your RAM allocation in Twitch to between 4 and 6GB and try again.

**Comment by Mooreaoth** [comment]
how will i give ram

**Comment by Mooreaoth** [comment]
[crash-2019-07-03_09.41.37-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/3355529/crash-2019-07-03_09.41.37-server.txt)
aynı sıkıntı

**Comment by Mooreaoth** [comment]
can you connect to the server and install ?
