### ISSUE TITLE
Sub Server crashes sporadically

### ISSUE THREAD

**Issue by TGSRagnarok** [FTBTeam/FTB-Revelation-2#27]
* **Modpack Version**: 2.0
* **Issue**: Server Crashes sproadically

* **Link to Log or Crash File Paste**:https://paste.feed-the-beast.com/view/532f929f
* **Is it Repeatable?**: starting to happen more often
* **Mod/s Affected**: unknown

* **Known Fix**: <none

**Comment by Boomflex** [comment]
This is a Forge Multipart CBE crash.

This mod has been updated in an upcoming version v2.1.0

This will stop this interaction issue.
