### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by ryousuke-kuwabara** [FTBTeam/FTB-Revelation-2#271]
https://pastebin.com/WKwKw0TN
Server crash randomly, please someone help me ;_;
FTB Revelation - 3.0.1 - 1.12.2

**Comment by rune-san** [comment]
You should always fill out the entirety of the issue template when creating issues.

Your log shows your total Minecraft assigned memory is 3093MB.
`Memory: 232665928 bytes (221 MB) / 1336520704 bytes (1274 MB) up to 3243638784 bytes (3093 MB)`
This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

If you are using the dedicated server version of Minecraft, increase your RAM configuration in the settings file in the main directory of your Minecraft Instance to between 4G and 6G and try again.
