### ISSUE TITLE
[Feature Request] Allow buildcraft fuels to be used in IC2 semifluid generator

### ISSUE THREAD

**Issue by Neil-HD** [FTBTeam/FTB-Revelation-2#272]
With the overhaul of how buildcraft fuels work and the addition of the new types of fuel it is no longer possible to use buildcraft fuels in semifluid generators due to an oversight / mod interaction that has not been fixed yet. This is an issue that should be temp fixed at the pack level since there was no balance reason for it  to be removed

**Comment by CitiesXL2815** [comment]
report that request to Industrialcraft 2 and buildcraft

**Comment by tfox83** [comment]
I am going to close this as its not something I can add, will have to have the devs do it

**Comment by furtabs** [comment]
Bump https://www.curseforge.com/minecraft/mc-mods/buildcraft-fuels-for-ic2
