### ISSUE TITLE
End crystal not craftable

### ISSUE THREAD

**Issue by brainshead** [FTBTeam/FTB-Revelation-2#273]
* **Modpack Version**: _3.0.1_

* **Issue**: _End crystal not craftable. 
Error/Issue:

Try to craft this in a reborn storage doesnt't show the end crystal in the craftable window (output) .
Craft in normal workbench also doesnt show the end crystal in craft window (Output)
Craft in a TC workbench shows the end crystal but cant pick up the item (items revert back to to the table and no output in your characters inventory  ). So there is no way to summon the end dragon in this pack becasue DE disabled his way of summoning (Charged Draconium block is disabled by mod )_

* **Link to Log or Crash File Paste**: _No crash /or log of this_

* **Is it Repeatable?**: _yes_

* **Mod/s Affected**: _Draconic Evolution (recipe changed)_

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 3.1.0
