### ISSUE TITLE
Missing "Genetic Template" in JEI

### ISSUE THREAD

**Issue by CypherHyena** [FTBTeam/FTB-Revelation-2#275]
* **Modpack Version**: 3.0.1 - Minecraft 1.12.2 - MultiMC Version

* **Issue**: Item "Genetic Template" from GenDustry mod is missing from JEI. You can still craft it if you know the recipe, but you can't find it upon searching for mod or item name. 

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: GenDustry, JEI, Maybe JEI_Bees

* **Known Fix**: None

**Comment by tfox83** [comment]
fixed in 3.1.0
