### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by Firehead94** [FTBTeam/FTB-Revelation-2#276]
* **Modpack Version**: 3.0.1
* **Issue**: Item Duplication
[Video](https://plays.tv/video/5d350a29b411a19281/dupe-glitch-ftb)

* **Link to Log or Crash File Paste**: 
[latest log](https://paste.feed-the-beast.com/view/7ca26e5c) 
[debug log](https://paste.feed-the-beast.com/view/c15dbf23)
20:27 until the end is where the duping occurred

* **Is it Repeatable?**: yes

**Comment by DoragonKeiyou** [comment]
This is an issue with a bug in FastWorkbench. #262 
Modpack users and server owners can fix it by changing a config option on line 8 from "true" to "false" in the fastbench.cfg file, or by updating to a more recent version of FastWorkbench.

**Comment by tfox83** [comment]
Latest version is in 3.1.0 which is due out soon.
