### ISSUE TITLE
Thaumcraft aspects missing on some items

### ISSUE THREAD

**Issue by tterrag1098** [FTBTeam/FTB-Revelation-2#277]
This issue affects multiple packs. Most notably by gelum being missing from snowballs, making it quite a chore to acquire. 

Root cause: https://github.com/Azanor/thaumcraft-beta/issues/1619

Fix: http://assets.tterrag.com/ThaumcraftRecipeFix-1.12.2-1.0.0.0.jar

This is a mod I made that does a single line patch to the Thaumcraft recipe scanning to prevent it from registering empty aspect lists, as described in the linked thread. 

I'll have source available soon.

**Comment by tfox83** [comment]
Will get this included in next regular update when I get back from vacation in August.  Thanks

**Comment by tfox83** [comment]
Seems the mod has been removed due to issues.  IF you get this fixed again please let me know, thanks :)

**Comment by tterrag1098** [comment]
I will, just been away from home for a while. I'll post it here when I do.

**Comment by xJon** [comment]
@tterrag1098 Could you upload the fix to CurseForge? Thank you!
