### ISSUE TITLE
ProjectRed barrels have a one stack capacity.

### ISSUE THREAD

**Issue by fridibs** [FTBTeam/FTB-Revelation-2#278]
* **Modpack Version**: FTB Revelation 2, Minecraft 1.12.2, forge 14.23.5.2768

* **Issue**: I placed a ProjectRed barrel down and it can only contain a single stack and is suppose to hava a 128 stack capacity (I think). There is also no image on the sides.

* **Is it Repeatable?**: Yes. Everytime it is placed down it happens.

* **Mod/s Affected**: ProjectRed. Don't know if there are others.

* **Known Fix**: Unknown.

**Comment by tfox83** [comment]
Its a known issue, please use Yabba barrels instead.
