### ISSUE TITLE
Fluid Transposer from TE cant be Upgraded with a Kit

### ISSUE THREAD

**Issue by Silverrain2004** [FTBTeam/FTB-Revelation-2#28]
* **Modpack Version**: FTBRevelation-2.0.0-1.12.2 

* **Issue**: You cant Upgrade it with a Kit, it remains Basic.

* **Is it Repeatable?**: Just try to do the same.

* **Mod/s Affected**: Thermal Expansion

**Comment by GWSheridan** [comment]
This has been fixed in an upcoming update v2.1.0
