### ISSUE TITLE
Game Crash Before Tittle Screen

### ISSUE THREAD

**Issue by jeremymkurtz** [FTBTeam/FTB-Revelation-2#280]
* **Modpack Version**: <1.12.2>

* **Issue**: <Game Crashes during load up (First time downloading modpack>

* **Link to Log or Crash File Paste**: <https://paste.feed-the-beast.com/view/0997e8e2>

* **Is it Repeatable?**: <I have tried loading up the mod pack FTB Revelation 1.12.2 Release three-times and has not yet full download>

**Comment by jeremymkurtz** [comment]
Freezes at 'Finishing Up 6/7'

**Comment by jeremymkurtz** [comment]
Consistently crashes at "crazypants.enderio.base.integration.jei.(couldn't see last characters)"

**Comment by rune-san** [comment]
In the crash report it still shows your total Memory assigned is "2869MB". This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

Increase your RAM allocation in Twitch for either this Minecraft Profile, or universally to between 4 and 6GB and test again. :)

**Comment by jeremymkurtz** [comment]
Thank you. This has helped I didn't realize I would be needing to adjust on the twitch application. 👍
