### ISSUE TITLE
Yellorite, Uranium and Zinc not spawning in a multiplayer server 

### ISSUE THREAD

**Issue by Mesqi** [FTBTeam/FTB-Revelation-2#281]
* **Modpack Version**: FTB Revelation 3.0.1 

* **Issue**: Zinc, yellorite and uranium not spawning in a multiplayer server, even after trying the fix in the "known fix" below (I changed it on the server files, I don't know if I have to change it on my client and on each one of my friends playing in the server). 

* **Link to Log or Crash File Paste**: There isn't one. 

* **Is it Repeatable?**: Yes. 

* **Mod/s Affected**: Railcraft, ExtremeReactors and Industrial Craft 2.

* **Known Fix**: #227

**Comment by rune-san** [comment]
You do not have to apply the fix to client systems. The fix only works in newly generated chunks, and some of the numbers in that thread won't make it super common.

The fixes are rolled into FTB Revelation 3.1.

**Comment by Mesqi** [comment]
In that case, should I delete the aroma mining dimension and start a new one to get yellorite? And which folder is the aroma dimension's folder?

> You do not have to apply the fix to client systems. The fix only works in newly generated chunks, and some of the numbers in that thread won't make it super common.
> 
> The fixes are rolled into FTB Revelation 3.1.

**Comment by rune-san** [comment]
It should work that way yes. With the server instance stopped, and your config changes made, delete DIM-6 from your world folder and it should rebuild the mining dimension when you enter it again. It's based off the same seed, so everything should be in roughly the same place, but ore population should contain Yellorite and other metals now.

**Comment by Mesqi** [comment]
There's no DIM-6 in the world folder, also, is the chance of the ore spawning correct in this version?

> It should work that way yes. With the server instance stopped, and your config changes made, delete DIM-6 from your world folder and it should rebuild the mining dimension when you enter it again. It's based off the same seed, so everything should be in roughly the same place, but ore population should contain Yellorite and other metals now.

**Comment by Tician90** [comment]
I thought this was intended to balance ExtremeReactors (you know, way too much RF for early game). 
You can still get Uranium and Zinc with the Laser-Mining from Environmental Tech. And to get Uranium Ingots from the Ores (instead of the radiating things from another mod), you need to melt the Ore in the smeltery from Tinker Construct and fill it into an ingot-cast.
That was my way around it :)
