### ISSUE TITLE
Can not install the new version, missing addon

### ISSUE THREAD

**Issue by Andom325** [FTBTeam/FTB-Revelation-2#282]
* **Modpack Version**: FTBRevelation-3.1.0-1.12.2.zip

* **Issue**:This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 225104

* **Link to Log or Crash File Paste**: 
never installs, so no crash report
* **Is it Repeatable?**: every time we try to download

Yep, day later it works fine. thanks!

**Comment by rune-san** [comment]
This is not an issue with the pack. That Mod ID is for Sonar Sonic's Calculator mod in Curseforge. That mod is still on Curseforge and can be downloaded, so this is probably your Twitch app simply being twitchy. Make sure you manually delete any downloaded files for that pack from your instances folder, completely exit and restart your twitch app, and give it some more tries. It should work eventually.
