### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by silent** [FTBTeam/FTB-Revelation-2#285]
* **Modpack Version**:  FTBRevelation-3.1.0-1.12.2

* **Issue**: Server seems to crash every 20 minutes or so. I am not really sure what's causing it to happen.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d046f2b0

* **Is it Repeatable?**: Yes

**Comment by tril0byte** [comment]
quark mod, yellow flower pot-  you have a bunch of them and there appears to be code in the flower pot that exhausts the stack, probably you made more flowers than the mod author ever tried, possibly one flower has to go and notify all the other ones or something. I'd disable quark, go into the world and destroy all the flower pots, and re-enable quark, or find an editor that lets you do so without entering game, and then check code for flower pot and see what it is doing.

**Comment by silent** [comment]
It's a brand new world generation, so that's strange.
