### ISSUE TITLE
Crashing in Dimensions

### ISSUE THREAD

**Issue by dragonkid828** [FTBTeam/FTB-Revelation-2#287]
* **Modpack Version**: 3.0.1

* **Issue**: Constant crashing in other dimensions, thus far on the Twilight Forest and the Nether

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2fb447b8

* **Is it Repeatable?**: Yes, it happened several times in a row, near constantly in the Twilight Forest, and forced us to us a backup of the world in order to get out of the Nether.

* **Mod/s Affected**: Twilight Forest, all Nether mods, etc

* **Known Fix**: n/a

**Comment by rune-san** [comment]
Your log shows your total Minecraft assigned memory is 1979MB.
`Java Version: 1.8.0_221, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 194295040 bytes (185 MB) / 1319632896 bytes (1258 MB) up to 2075918336 bytes (1979 MB)
JVM Flags: 8 total; -Xmx2048M -XX:PermSize= -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10`

This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

If you are using the dedicated server version of Minecraft, increase your RAM configuration in the settings file in the main directory of your Minecraft Instance to between 4G and 6G and try again.
