### ISSUE TITLE
Uncrafting Table Problem

### ISSUE THREAD

**Issue by adosikas** [FTBTeam/FTB-Revelation-2#288]
* **Modpack Version**: 3.1.0

* **Issue**: Item generation with Uncrafting Table:  
The Uncrafting Table apparently cannot distinguish iron backpacks tiers from another, so it is possible to insert a backpack, select the recipe for the diamond backpack and thus convert 9 levels into 6 diamonds and a golden backpack to repeat the procedure with.  
I didn't test other items but there are probably other affected recipes.

* **Link to Log or Crash File Paste**: Not applicable

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Twilight Forest and at least Iron Backpacks, probably more

* **Known Fix**: Disable uncrafting table

**Comment by tfox83** [comment]
This was supposed to be disabled a while ago, it must of reverted at some point.  It will be disabled again in next version due out in a couple days.
