### ISSUE TITLE
Railcraft metal posts have no recipe

### ISSUE THREAD

**Issue by mbwarn** [FTBTeam/FTB-Revelation-2#289]
* **Modpack Version**: 3.01

* **Issue**: None of the metal posts for Railcraft has a recipe. Nothing shows in JEI and they aren't craftable using the default recipes.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Railcraft

**Comment by mbwarn** [comment]
So after some further investigation, you ARE able to craft BLACK metal posts using the rolling machine and iron ingots in an "I" formation. Typically brown are (were?) the default, but black is at least craftable.

But you're not able to dye them another color (by placing a dye in the center of the 3x3 grid and surrounding it with metal posts. That recipe isn't present in JEI for Revelations.

**Comment by CitiesXL2815** [comment]
Railcraft problem report it to Railcraft
