### ISSUE TITLE
Traveler Sack from AA Dupe

### ISSUE THREAD

**Issue by ChosenArchitect** [FTBTeam/FTB-Revelation-2#29]
* **Modpack Version**: 2.0

* **Issue**: You can dupe in the TC smeltery with this item.

Here some more information
Auto inserts off, default filter configuration.
Shift right click into the furnace controller to emptying the content of the sack.
The furnace is fully loaded but only one item leaves the sack.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tinkers construct & Actually Additions

* **Known Fix**: Remove the Traveler Sack https://github.com/Ellpeck/ActuallyAdditions/issues/1092

**Comment by GWSheridan** [comment]
Will remove recipe until fixed by mod author

**Comment by tfox83** [comment]
Will close this as its resolved for now, if the bug is fixed ill re enable the item.
