### ISSUE TITLE
DankNull items disappearing

### ISSUE THREAD

**Issue by Tician90** [FTBTeam/FTB-Revelation-2#290]
* **Modpack Version**: 3.0.1 / 3.1.0

* **Issue**: items in the items dank/null disappearing

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes, as soon as a slightly larger number of a single items automatically enters the dank/null (player picking it up), the stack of this items gets deleted a split of a second after the dank/null will be opened.

* **Mod/s Affected**: DankNull < Juli 2019

* **Known Fix**: Newest version of DankNull should have it fixed, but the latest version isn't included in the newest Revelation beta-version (3.1.0)

https://github.com/p455w0rd/DankNull/issues/156

**Comment by tfox83** [comment]
This is fixed in next version, due out in a couple days

**Comment by pixelblob** [comment]
I think its still happening
