### ISSUE TITLE
Unable to craft Railcraft advanced item Loader/unloader

### ISSUE THREAD

**Issue by Hynisel** [FTBTeam/FTB-Revelation-2#291]
* **Modpack Version**: 3.0.1

* **Issue**: Unable to craft steel shovel from railcraft (as it's disabled from what i have read) and thermal foundation one is not accepted to craft the advanced item unloader (railcraft)

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: Railcraft 12.0.0

* **Known Fix**: Thermal foundation shovel should be added as acceptable replacement for the railcraft one for the craft of the advanced item unload and loader (Railcraft)

![1](https://user-images.githubusercontent.com/53999494/62835281-ec595e80-bc56-11e9-8109-f545900419f7.JPG)

![2](https://user-images.githubusercontent.com/53999494/62835284-ef544f00-bc56-11e9-9906-2e62ff99f7de.JPG)

**Comment by CitiesXL2815** [comment]
FTB Revelation your using is outdated 
new version 3.1.0 try see if works in that version

**Comment by Hynisel** [comment]
I have tested it this evening on the 3.1.0, I confirm that the problem persist also with the new version

**Comment by CitiesXL2815** [comment]
then it's railcraft bug then report to them and integration with TF

**Comment by tfox83** [comment]
I will add support for the TF steel shovel in the recipe in the next update
