### ISSUE TITLE
Iridium Ore unobtainable

### ISSUE THREAD

**Issue by Quadrum1** [FTBTeam/FTB-Revelation-2#292]
* **Modpack Version**: 3.1 Beta

* **Issue**: The item "Iridum Ore" from IndustrialCraft 2 is unoptainable without getting lucky in a dungeon chest! There is no recipe to craft the item altough it is needed in a lot of recipes

* **Link to Log or Crash File Paste**: No Log

* **Is it Repeatable?**: Its a game functionality, so yes

* **Mod/s Affected**: Item is from IndustrialCraft 2

* **Known Fix**: Add a recipe for Iridium Ore

**Comment by CitiesXL2815** [comment]
it recipe in compresser from IC2 you can't craft it also sometimes rare dungeons and villages

**Comment by ZiemlichUndead** [comment]
![grafik](https://user-images.githubusercontent.com/19202897/65631257-770fd600-dfd7-11e9-89f0-c3dc70ac6e45.png)
Whats this then?
