### ISSUE TITLE
[Trivial to Fix] IC2 macerator won't macerate quartz

### ISSUE THREAD

**Issue by john01dav** [FTBTeam/FTB-Revelation-2#294]
I'm currently trying to do a play through on a server with minimal RF, so a (prompt) fix for this would be great!

* **Modpack Version**: I tested in 3.0.1 and 3.1.0

* **Issue**: If I put nether or certus quartz in an IC2 macerator, it won't macerate

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IndustrialCraft 2, Applied Energistics 2

* **Known Fix**: I assume that this is easy to fix in craft tweaker, although I don't know how it works exactly so I can't give specifics. It should be noted that the yields of dust with EnderIO's sag mill are quite good, and that IC2 should match that in order to make it viable as this pack seems to be trying to do based on the presence of several IC2 addons.

**Comment by john01dav** [comment]
I found a fix that worked on the server that I'm playing on, I still think that it would be good to add to the pack, however. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3807#issuecomment-493706760

EDIT: it should be noted that Fluix crystals are missing from the above fix, but that is trivial to fix

**Comment by CrossVas** [comment]
https://forum.industrial-craft.net/thread/15719-the-macerator-does-not-crush-quartz-from-ae2/?postID=217333#post217333

EDIT: Added an external source ([MediaFire](http://www.mediafire.com/file/0yw94ejpohcma13/ic2.zip/file))

**Comment by tfox83** [comment]
All have been added to the macerator in the next update:
`; certus quartz dust
OreDict:crystalCertusQuartz = appliedenergistics2:material@2
; nether quartz dust
OreDict:gemQuartz = appliedenergistics2:material@3
; fluix dust
OreDict:crystalFluix = appliedenergistics2:material@8`
