### ISSUE TITLE
UU-matter no recipes

### ISSUE THREAD

**Issue by tails11** [FTBTeam/FTB-Revelation-2#296]
* **Modpack Version**: 3.1.0 (BETA)

* **Issue**: UU-matter cannot be used in any way. There's no recipes for it.

* **Is it Repeatable?**: 
1)Launch FTB Revelation world
2)Obtain UU-matter 
3)Try to craft anything with it

* **Mod/s Affected**: IC2?

**Comment by tfox83** [comment]
You use the liquid UU matter in new versions of IC2, please check their wiki for more info.
