### ISSUE TITLE
Not able to boot up FTB 3.0.1 due to Ender.IO

### ISSUE THREAD

**Issue by Dawncaller** [FTBTeam/FTB-Revelation-2#297]
* **Modpack Version**: Minecraft 1.12.2, Mod 3.0.1

* **Issue**: Game crashes for initial loading. Crashed on my Macbook running OSX El Capitan, and my 2 friends running windows 10.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/dc76dd7c
* **Is it Repeatable?**: I have attempted to boot 4 times myself, and both of my friends tried once

* **Mod/s Affected**: crazypants.enderio.base.handler.darksteel.DarkSteelRecipeManager.getRecipes(DarkSteelRecipeManager.java:200)
I think it was that one, as it always got to 6/7 and crashed at about 2510/2700

* **Known Fix**: None

**Comment by rune-san** [comment]
In the crash report it still shows your total Memory assigned is "2869MB". This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

Increase your RAM allocation in Twitch for either this Minecraft Profile, or universally to between 4 and 6GB and test again. :)

**Comment by Dawncaller** [comment]
That did it! I even wondered if it was RAM, but when I looked for answers it said Mac automatically assigns the needed ram so I wouldn't need to. Thank you very much!!
