### ISSUE TITLE
Rustic Rope Craft Conflict

### ISSUE THREAD

**Issue by afroJezuz** [FTBTeam/FTB-Revelation-2#298]
* **Modpack Version**: 3.1.0

* **Issue**: String is a shapeless craft that makes string into 2. (thereby deleting 1/3 string.)
This also overwrites the Rope recipe.
![Screenshot_1](https://user-images.githubusercontent.com/54462308/63631887-1a895780-c5e2-11e9-9ebb-9c4a6c1847f2.png)

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: I have recreated this 12 times regardless of Craft Table UI or world condition.

* **Mod/s Affected**: Rustic

* **Known Fix**: Remove the destructive shapeless craft?
![Screenshot_2](https://user-images.githubusercontent.com/54462308/63631897-4573ab80-c5e2-11e9-9ba3-6b45ba574fe7.png)

**Comment by tfox83** [comment]
It is due to Pams Harvestcraft adding some oreDict entries.  It will be safer to change the rope recipe, I will do so in the next update, due out in a couple days.

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/64281174-6b188300-cf07-11e9-962e-c026d369647e.png)
This will be the new recipe, double the string but double the rope, and fixes the conflict
