### ISSUE TITLE
Twitch launcher missing mods

### ISSUE THREAD

**Issue by InvIncabl3** [FTBTeam/FTB-Revelation-2#299]
I downloaded the modpack on the twitch app, and when i loaded up minecraft it said it was missing **8 mods,** even though i'm pretty sure it should have downloaded all the mods i needed to play. But it didn't! I have no idea how this happened so i retried and when i got back into minecraft it said i was missing **14 mods**. I got no clue what is happening but i am most upset that i cannot play this mod :(

**Comment by rune-san** [comment]
This is a Twitch issue, not a pack issue. It sounds like you're trying to join a server. If you're trying to join a server, you need to make sure that in the the FTB Profile you downloaded in Twitch, that you're running the version that the server is running.
