### ISSUE TITLE
Mod Suggestion - Constructs Armory

### ISSUE THREAD

**Issue by TotalHamman** [FTBTeam/FTB-Revelation-2#3]
This mod was posted the other day on Reddit and looks to be a good fit for this pack.  It adds an armor station / armor forge to Tinkers as well as modular armor similar to the tools.  

[Constructs Armory](https://minecraft.curseforge.com/projects/constructs-armory)

**Comment by tfox83** [comment]
good suggestion, thanks, added in dev
