### ISSUE TITLE
Crashing again

### ISSUE THREAD

**Issue by Dawncaller** [FTBTeam/FTB-Revelation-2#300]
* **Modpack Version**: FTB Revaltions 3.0.1, with a MCPro Hosting server

* **Issue**: Frequent crashes after attempting to use a texture pack

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8bbe377e

* **Is it Repeatable?**: It has happened several times

* **Mod/s Affected**: 

I'm so terribly sorry to be bothering you all again with this, I'm not sure why this is happening :c

P.s. If I shouldn't post these here, feel free to let me know!

**Comment by Dawncaller** [comment]
It appears as though this happens when changing texture packs, as it was just able to boot perfectly

**Comment by tfox83** [comment]
Sorry I cannot support texture packs.  I do suggest not loading TPs when in game, do so from the menu as it uses alot of resources.
