### ISSUE TITLE
DE Spawners Causing Client Crashes

### ISSUE THREAD

**Issue by amurphy4** [FTBTeam/FTB-Revelation-2#301]
* **Modpack Version**: 3.1.0 

* **Issue**: Client occasionally crashes when loading chunks containing Draconic Evolution Stabilised Spawners (Wyvern tier.) This most commonly happens when teleporting using the /home commands. The chunks containing the spawners are chunk loaded using the FTB Utils chunk loading, crashes only occur on the client when the client loads the chunks. The server does not crash. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ea249f8e 

* **Is it Repeatable?**: Yes, however it is not consistent (i.e. the client does not always crash when loading the chunk with the spawner. I believe the crash is related to the phase of spawning, and only occurs if the chunk is loaded while the spawner is in a specific phase) 

* **Mod/s Affected**: Draconic Evolution (1.12.2-2.3.23.345)

* **Known Fix**:

**Comment by amurphy4** [comment]
I have just experienced the same client crash, after switching my draconic evolution spawners for enderio powered spawners, and switching the draconic evolution mob grinders for industrial foregoing mob crushers.

New crash report: https://paste.feed-the-beast.com/view/e1829c6a

**Comment by rune-san** [comment]
This is caused by the p455w0rdsLib mod, which has its own shader stuff going on. Unfortunately, there are numerous compatibility issues from a number of mods. I would recommend simply going into p455w0rdsLib.cfg and disabling the shader bits.

```
"colored light shader options" {
    # Enables shader support in dependant mods [default: true]
    B:EnableShaders=false
	
    # If true, then colored lighting effects will be added to vanilla items, blocks, and tile entities. [default: true]
    B:EnableVanillaLightingEffects=false

    # Maximum Number of lights to be rendered on the screen at once [range: 4 ~ 256, default: 64]
    I:MaxLights=64

    # Maximum Distance to render a colored light [range: 4.0 ~ 128.0, default: 128.0]
    S:MaxRenderDist=128.0

    # Skips sending light updates to the card some frames. This can speed up fps greatly when bandwidth is a problem. 0 always sends data. [range: 0 ~ 160, default: 10]
    I:NumFramesToSkipWhenRenderingShaders=10
}
```

**Comment by amurphy4** [comment]
I have changed the config file to match the settings you have given and it appeared to be working fine, however I have just experienced the same crash again with the same error message in the log file. 

Crash log: https://paste.feed-the-beast.com/view/6f4cd197

p455w0rdsLib.cfg paste: https://paste.feed-the-beast.com/view/f2aee18f

**Comment by amurphy4** [comment]
I have fixed the issue now. I was being silly and changed the config file on the server instead of the client.
