### ISSUE TITLE
[Adding Mods Request] 3 (maybe 4) Quality-Of-Life Mods

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Revelation-2#302]
I was watching this youtube vid here: https://youtu.be/MFwVA5DIY3M

And it got me thinking on some of the mods; besides some other mods that dealt with making minecraft sounds more realistic and echoes in underground caverns, I like 3 of these mods in this video (one mod is needed to complement the other)

FoamFix: https://www.curseforge.com/minecraft/mc-mods/foamfix-for-minecraft
RandomPatches: https://www.curseforge.com/minecraft/mc-mods/randompatches
Cosmetic Armor Reworked: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
BetterFPS: https://www.curseforge.com/minecraft/mc-mods/betterfps

The first 2 are mods that optimize minecraft much like the other optimization mods out there, but the randompatches mod claims to solve some problems I experience on the mc complex ftb revelations server I play, and the 3rd one could be nice to use if only for purely cosmetic reasons. The **ONLY** caveat with FoamFix is that it needs BetterFPS to get the areas FoamFix can't reach, otherwise it gets a bit buggy from what I can understand

I request these 4 mods be considered for the next future revelations modpack release, if not the next, then at least put it on the back-burner until they get added

**Comment by tfox83** [comment]
Foam Fix and Random Patches are already present in the pack.  Phosphor has been added in 3.2.0 beta, due out in a few days, that address lighting issues with greatly improves performance. 
At this time we are not adding content to this pack.
BetterFPS caused issues on some systems thus making it to risky for us to ship in such a large modpack.  If if works for you feel free to add to your client as it does not need to be on the server to connect.  If you have any issues please test with that mod removed before submitting issues here in the future.  Thanks
