### ISSUE TITLE
[Fix Dupe Bug/Add Alt Recipe] Fluxed Phyto-Gro

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Revelation-2#304]
* **Modpack Version**: 3.01 to 3.10

* **Issue**: dupe bug with the energetic infuser

* **Link to Log or Crash File Paste**: none that I can find useful

* **Is it Repeatable?**: If it got banned in the server I played in, then quite possibly

* **Mod/s Affected**: just thermal expansion and foundation (I.E getting locked out of one of the best IF garden cloche growth resources)

* **Known Fix**: n/a

I don't know when exactly they banned it, but I play in the MC-Complex revelations server because my former teammate recommended it to me. Now when there's garden cloches from industrial foregoing, I try to make sure I got fluxed phyto-gro on hand because its the best to use hands down, and the only way of getting fluxed phyto-gro is to put rich phyto-gro in an energetic infuser. Going off of an old explanation one of the server admins gave me, they had to ban it because it caused a dupe bug with items that could be used in it, either to charge them with power, or repair them with that repair specialization augment.

this was months ago, and I don't know if this is even still duping in 3.1.0 still since I cant test it on the server; maybe I could try in a single player world, but idk if it would translate the same on the complex server as well. My request is that if such a bug exists, please fix it by the next modpack update, because bubba needs his phyto-gro. Maybe adding an alternate recipe by using an Ender IO wired charger or enhanced wired charger

**Comment by tfox83** [comment]
Sorry at this time we are leaving the recipe default as we cannot reproduce any duping from it.  I suggest talking to a server admin about it or finding a new server to play on.
