### ISSUE TITLE
Drawer Controller, Slave Controller, compacting drawer and drawer upgrades only accept oak drawers

### ISSUE THREAD

**Issue by MathijsdeBoer** [FTBTeam/FTB-Revelation-2#305]
* **Modpack Version**: 3.1.0

* **Issue**: To craft a Drawer Controller, Slave Controller, Compacting Drawer and/or Upgrade Template, you need to supply an oak drawer. Other types of wood are not accepted. This is especially annoying as I am sitting in a large Fir forest with no regular oak nearby.

* **Is it Repeatable?**: Yes. Attempt to craft any of the mentioned items with a non-oak drawer.

* **Mod/s Affected**: Storage Drawers 5.3.8, Storage Drawers Extras 3.1.0

**Comment by tfox83** [comment]
This is intended by the dev, if you would like you could suggest this change directly to the dev on his tracker.
