### ISSUE TITLE
AE2 Energy cells + Flux Networks Flux plug crash the game singleplayer and multi

### ISSUE THREAD

**Issue by DPilat-Dev** [FTBTeam/FTB-Revelation-2#306]
-   Modpack Version:  
3.1.0

-     Issue: 
using the AE2 Energy cell or the AE2 Dense Energy cell with Flux Networks flux point directly it crashes the server (with a null pointer exception) or in single player where it crashes the whole game.
![image](https://user-images.githubusercontent.com/12778616/64480843-804e1580-d184-11e9-93a5-de0fe9f03950.png)

-     Link to Log or Crash File Paste: 
Singleplayer crash:(The game crashed whilst exception in server tick loop Error: java.lang.NullPointerException: Exception in server tick loop) https://pastebin.com/Eu9pneLb

Multiplayer crash: https://pastebin.com/Ff1Cha86

-     Is it Repeatable?: 
Yes, almost everytime you add a flux plug and a AE2 Energy Cell.

-     Mod/s Affected: 
AE2

-     Mods being used: 
AE2, Flux Networks

-     Known Fix: 
No idea

**Comment by CitiesXL2815** [comment]
report it to both mod developers of AE2 and Flux networks

**Comment by 016Nojr** [comment]
Pack update coming in a few days that hopefully will have fixed this.
