### ISSUE TITLE
Compact Machines missing in action

### ISSUE THREAD

**Issue by xSkyripper** [FTBTeam/FTB-Revelation-2#307]
* **Modpack Version**: 3.1.0

* **Issue**: Compact Machines mod has been removed in FTB Revelations 3.0.0 major update (https://www.feed-the-beast.com/projects/ftb-revelation/files/2711066). Is there any reason for it being removed? The changelog does not state any impact/bug/issue its removal fixes. Do you have a plan to bring it back?

**Comment by Patchuu** [comment]
I'm looking for this too. There is any way to add this on the next version?

**Comment by tfox83** [comment]
At this time there is no plans to bring it back.
