### ISSUE TITLE
Zinc Grains not craftable into zinc ingots

### ISSUE THREAD

**Issue by Emerald-Chicken** [FTBTeam/FTB-Revelation-2#310]
* **Modpack Version**: 3.2

* **Issue**: Although Zinc Grains are perfectly obtainable through legitimate bee breeding, they don't convert to their metal counterpart in the way for instance iron, platinum or copper do. The main issue is probably that there isn't a dust version of zinc, as there is for most other ores.

* **Link to Log or Crash File Paste**: non applicable

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Binnie's Extra Bees, Railcraft

* **Known Fix**: Add a recipe for the ingot via CraftTweaker, which is already in the pack.

**Comment by 016Nojr** [comment]
Added a recipe to convert grains to ingots in a pack update coming in a few days
