### ISSUE TITLE
IC2 Iridium Ore recipe

### ISSUE THREAD

**Issue by ZiemlichUndead** [FTBTeam/FTB-Revelation-2#312]
* **Modpack Version**: 3.2.0

* **Issue**: 

In the previous version of this modpack the only way to obtain IC2 Iridium ore was to find it in Dungeon chests with a chance of 1%. You changed that now so you can get it the IC2 intended way by Compressing Iridium shards in compressor and then replicate it using UU Matter. 

My issue is now the IC2 Iridium ore is still strangely linked to the Thermal Foundation recipe and while processing the IC2 ore in almost any machine will result in TF Ore, the Crushers from Immersive Engineering and Actually Additions can convert TF Iridium to IC2 iridium. There is also the recipe of "melting" TF iridium ore with TF Petrotheum dust in a crafting table.

I can only imagine that these ways to get IC2 iridium are not intended cause in the one hand recipes like melting or universally converting the ore dont exist and in the other hand I myself think IC2 Iridium would be way to easy to obtain if it can be converted from TF Iridium.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IndustrialCraft2, AdvancedSolarPanals, AdvancedMachines (etc.), Thermal Foundation.

* **Known Fix**: Either remove those strange way of conversion or fully add it and regulate the ore spawnrate

**Comment by brewgolding** [comment]
I had this issue with `ic2:crafting:37` the jetpack attachment plate and `ic2:crafting:4` iridium reinforced plate. You can use crafttweaker to update the recipe from iridium shards to iridium nuggets. For example;

```zs
val nuggetIridium = <ore:nuggetIridium>;
nuggetIridium.add(<ic2:misc_resource:2>);
nuggetIridium.add(<thermalfoundation:material:199>);

val ingotIridium = <ore:ingotIridium>;
ingotIridium.add(<ic2:misc_resource:1>);
ingotIridium.add(<thermalfoundation:material:135>);

# Jetpack Attachment
recipes.remove(<ic2:crafting:37>);
recipes.addShaped(<ic2:crafting:37>,
[[<ore:nuggetIridium>, <ore:plateAdvancedAlloy>, <ore:nuggetIridium>],
[<ore:plateCarbon>, <ore:plateSteel>, <ore:plateCarbon>],
[<ore:nuggetIridium>, <ore:plateAdvancedAlloy>, <ore:nuggetIridium>]]);

# Iridium Reinforced Plate

recipes.remove(<ic2:crafting:4>);
recipes.addShaped(<ic2:crafting:4>,
[[<ore:ingotIridium>, <ore:plateAdvancedAlloy>, <ore:ingotIridium>],
[<ore:plateAdvancedAlloy>, <ore:gemDiamond>, <ore:plateAdvancedAlloy>],
[<ore:ingotIridium>, <ore:plateAdvancedAlloy>, <ore:ingotIridium>]]);
```

Save it to a new file with a `.zs` extension under `MODPACK/scripts/` or if you only want it to apply to a single world `WORLDSAVE/scripts/`. 

Crafttweaker scripts are server side too, so you don't need to update client modpacks.

Hope that helps.

![javaw_2019-10-30_09-23-04](https://user-images.githubusercontent.com/45622850/67814264-b6aa7000-faf7-11e9-8bda-f06977796a7f.png)
![javaw_2019-10-30_09-23-21](https://user-images.githubusercontent.com/45622850/67814265-b6aa7000-faf7-11e9-99ee-fab77fdbf871.png)

**Comment by 016Nojr** [comment]
As far as I know we dont need IC2 Iridium Ore?
