### ISSUE TITLE
Pink slime unobtainable (?)

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Revelation-2#313]
* **Modpack Version**: 3.2.0

* **Issue**: There is no way to obtain pink slime according to NEI. The wiki (https://ftbwiki.org/Pink_Slime_(Item)) states that a slaughterhouse is needed to produce pink slime as a bi-product, but there is no slaughterhouse in the game.  

* **Mod/s Affected**: Integration Foregoing, Tinkers' Construct, (MineFactory Reloaded)

* **Known Fix**: Remove the pink slime(?), or add a way to obtain it. Rare flying slime islands with pink slime instead of blue would be nice, but that's probably to much work for the mod pack and would probably be a suggestion for the mod itself.

**Comment by karikusa** [comment]
When MOB is processed by a device called Mob Slaughter Factory
You can get liquid meat and liquid pink slime!

**Comment by ghost** [comment]
You're right.
