### ISSUE TITLE
Pipes disconnecting

### ISSUE THREAD

**Issue by carthe** [FTBTeam/FTB-Revelation-2#314]
* **Modpack Version**: 3.2.0

* **Issue**: Immersive Engineering pipes regurally disconnects itself from Railcraft output machines. Sometimes Railcraft multiblock also disassembles. 

I don't know if this is connected, but sometimes snow falls on the pipes.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Immersive Engineering/Railcraft

* **Known Fix**: Destroying and placing affected blocks fixes the issue.

![image](https://user-images.githubusercontent.com/32596055/65238014-16b2fd00-dadc-11e9-8c21-442a274ea9a8.png)

**Comment by ghost** [comment]
You could try chunk loading the chunks with multiblocks and pipes inside (with the chunk claim interface for example). But this should only be a temporary fix.

Also what Texturepack is that if I may ask?

**Comment by carthe** [comment]
You might be right, as this happens when I am not looking at them. Chunk loader might be a thing. Will try it later.

Texture pack is John Smith (https://www.johnsmithlegacy.co.uk/john_smith_modded.php).

**Comment by tfox83** [comment]
This is a known issue with chunk boundaries, force chunk loading that area should fix the rendering issues
