### ISSUE TITLE
Tinker's Smeltery Fuel

### ISSUE THREAD

**Issue by MalakaiMoros** [FTBTeam/FTB-Revelation-2#317]
* **Modpack Version**: 
FTBRevelation-3.2.0-1.12.2

* **Issue**: Tinker's Tools Smeltery will not accept Blazing Pyrotheum as a fuel source, leaving certain items eg Dark Boots unable to be smelted down

* **Is it Repeatable?**: yes

**Comment by CitiesXL2815** [comment]
blazing pyrotheum can't be used as fuel for the tinkers smeltery and is dark boot empowered and durability if they are then can't be smelted down again

**Comment by leabut** [comment]
Possible fix for you guys if anyone is still interested (since this has been marked as "wontfix")

Create file: /installdir/FTBRevelation/minecraft/scripts/TinkersConstruct.zs
Add the follwing lines:
```
#modloaded tconstruct

print("--- loading TinkersConstruct.zs ---");

// mods.tconstruct.Fuel.registerFuel(ILiquidStack fuel, int duration);
mods.tconstruct.Fuel.registerFuel(<liquid:pyrotheum> * 25, 400);
```

**Comment by blairwilson** [comment]
Does enabling this fuel in the smetlery break progression in some way? I want to enable it, but worried you have a proper reason for not adding it @tfox83

**Comment by leabut** [comment]
@HHServers could not identify anything not to work with pyrotheum as fuel. Quite the opposite, some mods using different alloys, still require liquid pyrotheum as fuel, as some alloys require higher melting temperatures (only possible to melt when using higher tier fuels, e.g. pyrotheum). One could adopt the melting temperature of the added alloy by any mod, but IMHO that's way more costly than re-enableing pyrotheum as fuel for TinkersConstruct.
One could also modify the melting temperature of other fuels, e.g. lava or the like, but I currently do not know if that's easily changable.

**Comment by blairwilson** [comment]
@leabut This was also the issue we were running in to as some recipes actually require it - but unsure if the devs want these to be inaccessible for whatever reason
