### ISSUE TITLE
Game crashing seemingly randomly

### ISSUE THREAD

**Issue by twofoldAnnihilation** [FTBTeam/FTB-Revelation-2#319]
* **Modpack Version**: FTB Revelation 3.2.0

* **Issue**: Crash seems to happen at random. Will be walking along in game and suddenly the game will freeze briefly and crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1c270218

* **Is it Repeatable?**: It's happened several times now but I can't pinpoint what's causing it

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by rune-san** [comment]
Check #301 for a similar issue. The p455w0rdsLib mod's renderer doesn't get along well with a lot of mods. I recommend going into your client config where the mod's p455w0rdsLib.cfg config file is located, and disabling it's renderer by changing the shaders and lighting effects to false.

```
"colored light shader options" {
    # Enables shader support in dependant mods [default: true]
    B:EnableShaders=false
	
    # If true, then colored lighting effects will be added to vanilla items, blocks, and tile entities. [default: true]
    B:EnableVanillaLightingEffects=false

    # Maximum Number of lights to be rendered on the screen at once [range: 4 ~ 256, default: 64]
    I:MaxLights=64

    # Maximum Distance to render a colored light [range: 4.0 ~ 128.0, default: 128.0]
    S:MaxRenderDist=128.0

    # Skips sending light updates to the card some frames. This can speed up fps greatly when bandwidth is a problem. 0 always sends data. [range: 0 ~ 160, default: 10]
    I:NumFramesToSkipWhenRenderingShaders=10
}
```
