### ISSUE TITLE
DankNull not voiding items

### ISSUE THREAD

**Issue by 0xicl33n** [FTBTeam/FTB-Revelation-2#320]
* **Modpack Version**: FTBRevelation-3.2.0-1.12.2

* **Issue**:  /dank/null will not void items that are picked up after being full

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: DankNull-1.12.2-1.6.77.jar

* **Known Fix**:  Fixed in newest release (https://github.com/p455w0rd/DankNull/issues/202)

![image](https://user-images.githubusercontent.com/2192160/66165649-12153b00-e5ea-11e9-8bf5-f66b1dddf8b1.png)

**Comment by nickalbrecht** [comment]
Any idea when the next release of Revelation will be out to include updates like this?

**Comment by keenan-v1** [comment]
Hello from 2020! Wondering when the next version is coming out as well. :)

**Comment by valyrie97** [comment]
Updating only DankNull to `1.6.79` causes a multiplayer only issue (tested myself in both) [#p455w0rds-MC-Mods/DankNull/332](https://github.com/p455w0rds-MC-Mods/DankNull/issues/332)

FTB version: 3.3.0
