### ISSUE TITLE
Modpack Crashes

### ISSUE THREAD

**Issue by K3rold** [FTBTeam/FTB-Revelation-2#321]
* **Modpack Version**: 3.2.0

* **Issue**: The pack crashes instantly when entering the game or after a couple of minutes.

* **Link to Log or Crash File Paste**: [Crash Log](https://paste.feed-the-beast.com/view/1bfe7601)

* **Is it Repeatable?**: Yes, simply enter the game.

* **Mod/s Affected**: Unknown

* **Known Fix**: Unknown

**Comment by rune-san** [comment]
See #319 and #301 for similar issues. My hope is that the modpack author will perhaps disable this functionality in the next release, as it does seem to cause a number of issues for users. The p455w0rdsLib mod's renderer doesn't get along well with a lot of mods. I recommend going into your client config where the mod's p455w0rdsLib.cfg config file is located, and disabling it's renderer by changing the shaders and lighting effects to false.

```
"colored light shader options" {
    # Enables shader support in dependant mods [default: true]
    B:EnableShaders=false
	
    # If true, then colored lighting effects will be added to vanilla items, blocks, and tile entities. [default: true]
    B:EnableVanillaLightingEffects=false

    # Maximum Number of lights to be rendered on the screen at once [range: 4 ~ 256, default: 64]
    I:MaxLights=64

    # Maximum Distance to render a colored light [range: 4.0 ~ 128.0, default: 128.0]
    S:MaxRenderDist=128.0

    # Skips sending light updates to the card some frames. This can speed up fps greatly when bandwidth is a problem. 0 always sends data. [range: 0 ~ 160, default: 10]
    I:NumFramesToSkipWhenRenderingShaders=10
}
```

**Comment by K3rold** [comment]
Yes, this seems to fix the crash problems. I have played the pack for a couple of hours and it haven't crashed.
