### ISSUE TITLE
Add Plethora Peripherals

### ISSUE THREAD

**Issue by bonnedav** [FTBTeam/FTB-Revelation-2#322]
Please add the Plethora Peripherals mod so I can read form powercells and reactors and stuff with Computer Craft. Thanks

**Comment by l3dotdev** [comment]
I agree, Plethora would be a great addition to the pack, allowing for people who use computercraft to do more with it!

**Comment by tfox83** [comment]
Will look into this next version in a few weeks.

**Comment by bonnedav** [comment]
How's it coming?

**Comment by MacChuck** [comment]
Love this idea, if possible. I just tried to do some stuff with computers and was sad that it doesn't talk to much.

**Comment by MitchH10** [comment]
Any update on this? I'd love to see it too

**Comment by 016Nojr** [comment]
Added in a new pack update coming in a few days
