### ISSUE TITLE
FTB Utilities

### ISSUE THREAD

**Issue by BenoronTv** [FTBTeam/FTB-Revelation-2#323]
Hello i have the problem that all ftbUtilities commands wont work in multiplayer but they work in the singleplayer and when i claim chunks in singleplayer the same are claimed in the multiplayer map but in the multiplayer i cant claim anything or unclaim it and yes i am an Operator

please help me  i play with some friends on a private server

**Comment by CitiesXL2815** [comment]
Need more information and versions of the mods affected and FTBRev version as well

**Comment by 016Nojr** [comment]
Mod versions needs to be provided along with logs. Please resubmit the issue to the new issue tracker that can be found in the pinned issue.
