### ISSUE TITLE
Buildcraft Builders Quarry doesn't connect with ANY thermal expansion/dynamics ducts

### ISSUE THREAD

**Issue by Jwguy** [FTBTeam/FTB-Revelation-2#324]
* **Modpack Version**: 3.2.0

* **Issue**:  Buildcraft Builders Quarry is completely incompatible with Thermal Expansion 5 and Thermal Dynamics' various ducts, whether it be item, flux, or otherwise. This was previously not the case in earlier versions of the modpack.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Buildcraft Builders, Thermal Expansion 5, Thermal Dynamics

**Comment by Feikovandijk** [comment]
Check out this comment from a developer: https://www.reddit.com/r/feedthebeast/comments/7ezn3t/buildcraft_1122_alpha_released/dq8ia6f/
Basically BC uses MJ, not RF and will never accept it. It used to accept RF in older versions but doesn't anymore.

**Comment by Jwguy** [comment]
Oh, geez, that's really lame. I hadn't realized this had gone down.

I've seen people mention power Converters mods... any chance one of those might find their way into Revelations in light of this?

**Comment by Feikovandijk** [comment]
Well revelation has flux networks, I haven't figured out how to convert to MJ but RF to EU is possible, then feed the EU into an EU engine and you have MJ. There might be a better way to do this but I couldnt get flux networks to export power into buildcraft pipes

**Comment by Sakata-MC** [comment]
Buildcraft devs haven't really gotten too far along wth BC yet.  Also, the one I spoke to said they aren't wanting to accept other power forms like before because it breaks the progression of BC.  Kidna agree honestly, after talking for a bit -- stupidly fast quarries and such.
