### ISSUE TITLE
Can't craft Void Thaumaturge Robe and Leggings

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Revelation-2#325]
* **Modpack Version**: 3.2.0

* **Issue**: Can't craft the Void Thaumaturge Robe and Leggings (Helmet works fine)

![image](https://user-images.githubusercontent.com/30607152/67096913-5f340800-f1b9-11e9-8f4c-f6937ebca6a8.png)

Can't start the process. Tried right after the helmet (which worked). Tried rebuilding the whole matrix. Tried different recipes (like the helmet and the recipes from different wikis). Tried making a Causality collapser which works

* **Is it Repeatable?**: Yes. I can click as many times as I want on the matrix without anything happening

* **Mod/s Affected**: Thaumcraft 6

**Comment by HonzaTich09** [comment]
I dont know if you still need help, but you need to repair your thaumaturges robes for it to function. I had the same problem and found this as answer, works for me. The recipe is wrong

**Comment by ghost** [comment]
Thanks, Havent been playing for a long time now tho.

**Comment by ghost** [comment]
There has not been a patch, how can it be fixed?

**Comment by 016Nojr** [comment]
I thought the issue was that you tried crafting with damaged robes and leggings? 

Thaumcraft isnt being worked on anymore either, so if it's a mod issue I'm not able to fix that.

**Comment by ghost** [comment]
It was not damaged, but fair enough
