### ISSUE TITLE
game crashes while teleporting/walking/loading world on server

### ISSUE THREAD

**Issue by KriKri98** [FTBTeam/FTB-Revelation-2#326]
* **Modpack Version**: 3.2.0

* **Issue**: At first the game crashed every now and then, but right now i´m unable to do anything because game crashes very fast. It startet with crashing after teleporting (waystones/home command) and now it´s crashing at joining the server, if i survive that, i can walk slowly around, and after a few hundred blocks it crashes again. Startet at 50h playtime, now at 55h.
Other people crash too, but not as often as I do. We modified only some configs (Astral Sorcery -> more perk levels, AE2 -> no channels).
Some people don´t crashe even once.
Just tried a creative singleplayer world and it seems to work just fine.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e32e0467

* **Is it Repeatable?**: Yes, every time I load onto the server it crashes.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by rjfs22** [comment]
This is happening to me and a friend of mine, same version of the game and server, i fixed for a moment by creating a new server with the same world, but when i exited the server and tried to join again, the client keeps on crashing. Any ideas how to get a fix? Thanks

**Comment by rjfs22** [comment]
You can fix it by editing the p455w0rdslib config and set to false the enableshaders. I have done on the server config and client, but i don't know if it's really needed to be disabled on the server config, what i konw it's without the client config edit, the game will continue to crash.

**Comment by CitiesXL2815** [comment]
shaders for p455w0rdslib and others have been removed in the update so @tfox83 you can update TheRealp455w0rd's mods it removes shaders
