### ISSUE TITLE
Please add Applied Energistics 2 (AE2) addons.

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Revelation-2#327]
I understand having Refined Storage and it's addons already exist. But for servers Refined Storage is a bad news (most of the time). Which resulting in people using AE2. Is it fine to use AE2.. but when you cant use RefinedStorage in servers (most of them) along with it's addons.. kinda feels a bit waste.
My point is.. Give some love to AE2 aswell.
Thank you for creating such a wonderful modpack. Bless you guys!

"Wanted to put a feel free to remove here but who am i to bring such a thing.. you know.. if somebody already addressed this".

**Comment by ghost** [comment]
You could give some concrete examples on what you want. I think that would at least help me understand what you want.

**Comment by Mo3Nox** [comment]
1. AE2 stuff. (Main pick)
2. Extracells. (Main pick)
I think the first 2 are most important, you can ignore the rest if you want.
3. Practical Logistics 2. (Personal pick)
4. Applied Integrations (Personal pick)

**Comment by ghost** [comment]
On second thought

**Comment by ghost** [comment]
First.. Sorry for replying this late.. Life is beautiful.. it makes you
forget about everything.

Extra cells
AE2 Stuff
Some love for Applied Energistics 2 players.
