### ISSUE TITLE
wget Error 403

### ISSUE THREAD

**Issue by QMon23** [FTBTeam/FTB-Revelation-2#328]
* **Verision** FTBRevelationServer_3.2.0.zip

* **Issue**: When trying to wget the download link it returns "error 403 forbidden"
command line:

`wget https://www.curseforge.com/minecraft/modpacks/ftb-revelation/download/2778975`

It returns error 403 each time.

I do no know how to get around this error.

Thank you,
-Q

Edit:

**Solved:**

URL would redirect and cause error 403.

```
Here is a download link: https://media.forgecdn.net/files/2516/474/FTBRevelation-1.2.0-1.12.2.zip

The way I retrieved it was simple:

Download the file on your PC
Depending on your browser: In Firefox, RMB on downloaded file -> Copy Download Link
When using cURL, it works for me.
```

**Comment by kereis** [comment]
This is due to Cloudflare. Whenever you try to curl or wget your link, it denies your request.
AFAIK, there are currently no other mirrors available. You might need to push your files through SFTP.

If I find something out, I'll try to respon asap.

**Comment by kereis** [comment]
Here is a download link: https://media.forgecdn.net/files/2516/474/FTBRevelation-1.2.0-1.12.2.zip

The way I retrieved it was simple:
1. Download the file on your PC
2. Depending on your browser: In Firefox, **RMB on downloaded file** -> **Copy Download Link**

When using cURL, it works for me.

**Comment by QMon23** [comment]
> Here is a download link: https://media.forgecdn.net/files/2516/474/FTBRevelation-1.2.0-1.12.2.zip
> 
> The way I retrieved it was simple:
> 
> 1. Download the file on your PC
> 2. Depending on your browser: In Firefox, **RMB on downloaded file** -> **Copy Download Link**
> 
> When using cURL, it works for me.

I see! Thank you :)

-Q
