### ISSUE TITLE
Flux item unobtainable

### ISSUE THREAD

**Issue by ExecuteOrd66** [FTBTeam/FTB-Revelation-2#329]
* **Modpack Version**:  3.2.1

* **Issue**:  Flux is an unobtainable item in this modpack. This makes Flux Networks a redundant mod. Throwing Redstone in both lava or fire does not let the appropriate Flux item drop. This might be because of an outdated mod version, or a config file that prevents it from dropping. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Throwing Redstone into Fire or Lava to create Flux.

* **Mod/s Affected**: Flux Networks

* **Known Fix**:

**Comment by itsapandaa** [comment]
You can turn on the Flux via fire and lava in the config. Was disabled due to a dupe bug. You should also be able to mine via redstone ore blocks but the base setting makes that incredibly grindy so you would want to change that in the settings

**Comment by VADemon** [comment]
Bump. The mods needs to be updated in the modpack, there's a new recipe without the dupe bug.

**Comment by jarquafelmu** [comment]
The flux is currently a drop chance when mining redstone ore. So it's annoying but it is obtainable.

edit: For more clarity. When you mine redstone ore with a pickaxe. there is a chance that flux will drop as well. that is the way to obtain flux as it is right now.

**Comment by 016Nojr** [comment]
Flux from fire has been enabled and the mod is updated in a new pack update coming in a few days
