### ISSUE TITLE
Marble Bees Don't Spawn

### ISSUE THREAD

**Issue by flamepelt12** [FTBTeam/FTB-Revelation-2#33]
* **Modpack Version**: 2.0.0

* **Issue**: Marble Hives from Binnie's Extra Bees don't seem to spawn anywhere, in any dimension. I looked for quite awhile, they are listed as spawning in JEI but when looking at the suggested Y level I found nothing 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Binnie's Extra bees
* **Known Fix**: none

**Comment by Boomflex** [comment]
I have re-posted this on the Binnie's issue tracker as I can see there is an active issue with Marble Hives spawning.

https://github.com/ForestryMC/Binnie/issues/274

Our configs dictate they SHOULD be spawning with worldgen, but looks like a mod issue.

**Comment by flamepelt12** [comment]
Perhaps the issue is that marble hives can only spawn at y 22 whilst the marble from chisel spawns at y 29 at the lowest

**Comment by tfox83** [comment]
Do they look for marble to spawn around? I wasn't aware of that if so, we can bump Y level of the hives to like 32

**Comment by flamepelt12** [comment]
As far as I know they do indeed look for marble to spawn in/around

**Comment by tfox83** [comment]
Ok at this time I do not have an easy fix for this as adjusting marble inst the safest with pre-existing worlds and there is no config option for adjusting level of marble hives, on the amount.  We will see if that option gets added in.

**Comment by tfox83** [comment]
Closing issue as nothing I can do with a released pack without running the risk of a retrogen as I am not going to do.  If the dev fixes this or adds a config for me to raise Y level of hives I will get that in, but you will have to either regen or go to new chunks.
