### ISSUE TITLE
changelog 3.2.0 > 3.2.1 and server pack

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Revelation-2#330]
title says:
missing changelog 3.2.0 > 3.2.1
missing server pack for 3.2.1
pls fix

**Comment by ghost** [comment]
so - as no one replied in a week i downloaded both zips from curseforge unzipped them and diffed the directories
the differences seems only client side:
the manifest only has the different version from 3.2.0 to 3.2.1 - but otherwise all other is same (so same mods with same versions)
but 3.2.1 has additional mod:
3.2.1/overrides/mods: FTBLauncherNotifier-1.0.1.jar
so - as google didnt got me anything i quickly decompiled it
only one have usefull stuff in it is GuiLauncherChange
wich just informs about the change comming in november
so - if one consider to setup a server - you can use the 3.2.0 server pack and decide to either use 3.2.0 client pack without the info - or 3.2.1 with the info

was it really that much to put into the changelog?

**Comment by JeNaiKe** [comment]
Thank you!

**Comment by tamasgal** [comment]
How do I actually make it work with 3.2.0 on the server side? The clients cannot join with the current FTB Revelation mod, they only get a message that tons tiny version conflicts.

The error on the server list shows "Incompatible FML modded server"

**Comment by ghost** [comment]
You seem not to use same version (or even pack) on server and client. Please check that you use the same pack and the same version of it on both server and client.

**Comment by tamasgal** [comment]
Ah my bad, I mixed up the instances. It was indeed the old version... sorry, and thanks for the rapid answer!
