### ISSUE TITLE
Advanced Solar Panels Stone Slab can't be made

### ISSUE THREAD

**Issue by gricey432** [FTBTeam/FTB-Revelation-2#332]
* **Modpack Version**: 3.2.0

* **Issue**: The recipe in JEI for the Stone Slab turns into normal stone

![Screenshot 2019-11-09 17 21 16](https://user-images.githubusercontent.com/1611345/68524717-bc812c00-0315-11ea-8e33-08e1ec04d005.png)

![Screenshot 2019-11-09 17 21 22](https://user-images.githubusercontent.com/1611345/68524719-c014b300-0315-11ea-96bd-42a29ac55a33.png)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Advanced Solar Panels

**Comment by ghost** [comment]
uhm - either a recipe conflict (wouldn't surprise me if consider bad quality of ftb-packs) - or this has to be mined in-world instead of crafting

**Comment by ghost** [comment]
ok - just checked in 3.2.0 - it's a recipe conflict: adding two stone slabs together and get a stone back is
1) according to JEI it seems adding two slabs to a stone block to be a vanilla recipe - but it isn't listed on minecraftwiki
2) is additional overriden by EnderCore
3) AdvancedSolar conflicts with this - so it's either a recipe fault in AdvancedSolar or in the pack not handling these correctly - also, you can't sliktouch mine in-world block
also - there's no use of this double-slab block - all whats listed like covers and facades are auto-generated - if the mods removed generating them this block wouldnt had any use ... so: it just doesn't matter

**Comment by gricey432** [comment]
Re: point 3, the reason I wanted this is to make facades, since there's otherwise no way to make facades for a wall made of stone slabs

**Comment by ghost** [comment]
setup vanilla with advanced solar only and see if it works - if so - add endercore to see if its override - if so its a recipe conflict not solved by pack author (most likely as in the tweaker scripts theres no mention of those two mods) - so report to endercore/enderIO and/or advanced solar for recipe conflict with another

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
