### ISSUE TITLE
keeps crashinng whenever i launch my world https://pastebin.com/Qb1ztsDk

### ISSUE THREAD

**Issue by MisaLv** [FTBTeam/FTB-Revelation-2#333]
* **Modpack Version**: 3.2.1-1.12.2zip

* **Issue**: When i try to launch the world it just crashes.

* **Link to Log or Crash File Paste**: https://pastebin.com/Qb1ztsDk

* **Is it Repeatable?**: Tried to launch it 4 times and in every try it crashed.

* **Mod/s Affected**: The game crashed whilst exception in server tick loop Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)

* **Known Fix**: I have not found a fix for this yet.

**Comment by ghost** [comment]
Caught exception from MineTogetherServer (minetogetherserver)

your issue is some fault with the MineTogether mod - if you dont use it just disable it
or: check in <minecraft>/config/minetogether if you have other files than gdpr.txt
if so: delete it - should fix the issue

**Comment by MisaLv** [comment]
> Caught exception from MineTogetherServer (minetogetherserver)
> 
> your issue is some fault with the MineTogether mod - if you dont use it just disable it
> or: check in /config/minetogether if you have other files than gdpr.txt
> if so: delete it - should fix the issue

Yep that fixed it. Thanks

**Comment by ghost** [comment]
so - for others it would help to tell what you did so we could try to figure out the issue - and then maybe you it happend
