### ISSUE TITLE
Thermal Expansion Fluid Transposer getting stuck filling glass bottles until one removed

### ISSUE THREAD

**Issue by ar1a** [FTBTeam/FTB-Revelation-2#334]
Steps to reproduce

1) Fill fluid transposer with glass bottles
2) Fill fluid transposer with 1.5b of strength 4 potion
3) Observe that it fills up the glass bottles (you need to remove the result every time)
4) Once empty, fill fluid transposer with 1.5b more of strength 4 potion
5) Observe the fluid transposer is stuck, with empty glass bottle(s) in the input slot and enough fluid to fill them up
6) Observe that removing the "current" glass bottle from the fluid spot will resume filling up the bottles

Clip: https://streamable.com/exxpy

* **Modpack Version**: 3.2.1
* **Issue**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Expansion, COFH Core

**Comment by rendragnet** [comment]
Oh good, it's not just me.  Has anyone figured out a nice workaround for this? Some kind of observer to see when the Transposer has liquid in it, and start inserting bottles? I've been at this for a few hours, and am losing my mind trying to get brewing nicely automated with AE2 in FTB Revelation :(  I have to walk over to my brewing area and pull the first bottle out of the transposer and drop it back in.

**Comment by chi-bat** [comment]
I've been automating Rich Phyto-Gro using Sap and Phyto-Gro and have had the same issue :(

**Comment by plasmarob** [comment]
I've got the same exact problem and steps as the OP.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
