### ISSUE TITLE
need an update please

### ISSUE THREAD

**Issue by Dalienx** [FTBTeam/FTB-Revelation-2#335]
Hi, not sure this is the right place to post this but i couldn't find anywhere else.
we really need a server pack update, i see in this forum several issues marked as "fixed in the next update" but that was back in October and its nearly December now.
im running a server for my friends and we are stuck on 3.2.0
id also love to see a couple mods added to the pack, (ae2 stuff and dires gadgets) i know i can add them manually but that makes updating my players a pain.

**Comment by KySoto** [comment]
to add to this, flux networks has been refactored fixing the bug with how the flux material is being generated (it uses a block of obsidian and bedrock to convert redstone now)

**Comment by Desertphoenix74** [comment]
I'm having issues launching Revelations. Here's a screenshot and error report. 
![Screenshot (6)](https://user-images.githubusercontent.com/58096334/69471391-a898e980-0d5b-11ea-96b7-d915e03ae5a2.png)
[crash-2019-11-22_18.58.50-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/3882058/crash-2019-11-22_18.58.50-client.txt)

**Comment by jinkhya** [comment]
Just adding I would love to see an update for the pack. We're hosting it in our community as well and there are many bugs that were fixed in more recent mod updates (including the dank null mod being rather useless at the moment).

**Comment by CitiesXL2815** [comment]
@Desertphoenix74 pls open new issue and use gitgist or pastebin for the crashes people do not like downloading stuff

**Comment by CitiesXL2815** [comment]
so just let you guys know great suggestion but you may not see an update until FTB website is up and running again and other one is Building gadgets may not get added bc of exchangers and better buildings wands is in the pack so don't get to excited that it might happen depends on Tfox if he wants it in there okay. plus AE2 stuff may got removed for some reason due to bug in the pack
