### ISSUE TITLE
Game crashed when right clicking chisel on architecturecraft window with Window pane

### ISSUE THREAD

**Issue by timmit99** [FTBTeam/FTB-Revelation-2#337]
* **Modpack Version**: 3.2.1

* **Issue**: When right clicking a chisel (architecturecraft) onto a windowpane with glass (also from architecturecraft) the game crashed.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/20701cfb

* **Is it Repeatable?**: Yes, repeated 3 times
* **Mod/s Affected**:  Occurs with architecturecraft (ArchitectureCraft - TridentMC Version architecturecraft-1.12-3.98.jar)

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
