### ISSUE TITLE
ProjectRed gem issue with Dank Null

### ISSUE THREAD

**Issue by timmit99** [FTBTeam/FTB-Revelation-2#339]
* **Modpack Version**: 3.2.1

* **Issue**: upon placing a ProjectRed gem (Ruby, Saphire, Peridot) into Dank/Null they are replaced with 4 Circuit Plates from project Red

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes
![ProjectRed Bug](https://user-images.githubusercontent.com/8399317/70488918-284ae600-1ac8-11ea-9225-d3d2320e6dfe.gif)

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by CitiesXL2815** [comment]
report it to TheRealp455w0rd

**Comment by timmit99** [comment]
Already been posted there. Just posting here as a heads up to anyone else who has this issue and comes here to report it

**Comment by nickalbrecht** [comment]
This is also an issue with Thermal Foundation items it seems. Most resource I have tried (ingots, rods) gets converted to pulverized iron, or to an invalid item altogether. Some were added as "Invalid Item (Destroy)"

https://github.com/p455w0rd/DankNull/issues/239

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
