### ISSUE TITLE
Mod Suggestion - NuclearCraft

### ISSUE THREAD

**Issue by hammurabi1337** [FTBTeam/FTB-Revelation-2#34]
Why was NuclearCraft removed in Revelations 2.0? I've used it extensively in Rev 1.8.0 on a multiplayer server and had no issues, neither personally nor inflicted on the server as a whole.

I really was excited for 2.0 with the additions of Thaumcraft, Twilight Forest, Project Red, and so on but... dropping NuclearCraft is a huge dealbreaker for me. The dev is solely working on the 1.12 version now and Rev was the only popular pack that had included it.

Please bring it back in the next release.

**Comment by tfox83** [comment]
Nuclear Craft will be making another appearance in a modpack soon.  It just wasn't a good fit for such a large modpack like Revelations due to the server demand from the mod.

**Comment by 6rKbS6grBM7Q** [comment]
I've started trying NuclearCraft version 2.10p with FTB Revelation 2.2 (just by dropping their 2.10p jar file in the 'mods' folder).  I've just discovered that all the recipes to make Basic/Advanced/Elite plating are gone.  Is this an FTB Revelation issue or a NuclearCraft issue?  Have you see this?

**Comment by 6rKbS6grBM7Q** [comment]
Just tested Vanilla Minecraft 1.12.2 + Forge 14.23.4.2730 + NuclearCraft 2.10p... it works.  Must be something with the FTB Revelation 2.2 modpack.

**Comment by 6rKbS6grBM7Q** [comment]
Figured it out...

FTB Revelation 2.x modpacks have a line ('mods.unidict.removalByKind.get("Crafting").remove("plate");') which removes all plate recipes during startup, including NuclearCraft plate recipes.

If you comment out that line in the file 'scripts/01_unification.zs' in their modpack, the NuclearCraft plate recipes come back.

Anyone that is adding NuclearCraft mod manually to the mod pack will need to comment out that line.

Not sure if this is the best fix, so I'm hoping the dev's will review...
