### ISSUE TITLE
Running a server with Revelations now having issues

### ISSUE THREAD

**Issue by SacredBob88** [FTBTeam/FTB-Revelation-2#342]
FTB Revelations 3.2.0-1.12.2 (revised, please see my comment)

The server was working for a while it did crash at times. Only recently did the server start doing this. Upon start when the world is loaded the Overworlds TPS drops to 2-1 then the server goes down. I had roughly 3-4 players per week. It was only a local friend's server. The players do have a lot of machines running and storage systems. Also using different laser drills and void drills. We have also chunkloaders going and have explored multiple dimensions.

[https://paste.feed-the-beast.com/view/8bc6c991](url)
[https://paste.feed-the-beast.com/view/49e00152](url)

Easily Repeatable - Just try to start the server 👎 
Unknown Mods affected - I don't know
No known fix.

I was running it with 12gb of dedicated ram and 4 threads. I have a Xeon X5670 based system using MineOS. It was running fine. Not sure why it crashes. Any help would be appreciated
The server does not go above 4gb of ram usage when booting. TPS in the Overworld just dips will the server crashes 😐 

![Screen Shot 2019-12-16 at 11 25 02 am](https://user-images.githubusercontent.com/32085427/70877028-c4a84780-1ff6-11ea-93e3-7d68a2121c62.png)

**Comment by CitiesXL2815** [comment]
paste us actual log and crash if there is one those links lead no were

Also install sampler on the server see what causing the issue

**Comment by SacredBob88** [comment]
[crash-2020-02-17_05.48.48-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/4212050/crash-2020-02-17_05.48.48-server.txt)
I really need some assistance. I don't know why it crashes. Send help.
[2020-02-17-1.log.gz](https://github.com/FTBTeam/FTB-Revelation-2/files/4212054/2020-02-17-1.log.gz)
![Screen Shot 2020-02-17 at 2 03 07 pm](https://user-images.githubusercontent.com/32085427/74627569-4569f800-518e-11ea-8037-ae98cac020c2.png)
Additional Java Arguments:  -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=8 -XX:+AggressiveOpts

![Screen Shot 2020-02-17 at 2 04 39 pm](https://user-images.githubusercontent.com/32085427/74627634-7a764a80-518e-11ea-8557-2a2ad69ec278.png)
Just chucking a bunch of information out there. Not sure if it helps. Would like to restore my beloved server. (i took a small holiday)

**Comment by rune-san** [comment]
@CitiesXL2815 already provided a good suggestion of using sampler to find out why your server is exhausting itself: https://www.curseforge.com/minecraft/mc-mods/sampler

That said, I would also move your Java Arguments back to default for the purpose of troubleshooting.

Lastly, why do you have 12G of RAM dedicated to your OS but 20,000MB assigned to your Java Machine? Either your system has more RAM than 12GB, or you have way more RAM assigned to your Java VM than you have RAM available. That should be brought down to much more reasonable numbers to prevent high latency and judder when garbage collection is occurring. You also should be leaving room for your OS to function. Giving it all to just the Minecraft process isn't a good idea.

**Comment by SacredBob88** [comment]
![Screen Shot 2020-02-18 at 8 05 08 am](https://user-images.githubusercontent.com/32085427/74693104-4863f780-5225-11ea-829d-2873dd2fcab8.png)
There's my ram. 43.8gb (Closer to 44gb) total memory. So there's plenty there for the OS. Being a Linux based system means it does not need much ram in itself to run. 
The server itself uses 8+gb of ram just during startup if given 20gb  
I did use sampler. (bellow are the results moments before the server crashed).
![Screen Shot 2020-02-18 at 8 23 37 am](https://user-images.githubusercontent.com/32085427/74693740-07b9ad80-5228-11ea-9fcc-e80cffca9e33.png)

Java arguments made little to no difference. Even without them. The server starts up, loads world then TPS drops immediately. And the server stops. More than enough system resources are being used.

![Screen Shot 2020-02-18 at 8 38 45 am](https://user-images.githubusercontent.com/32085427/74694214-346ec480-522a-11ea-8cab-f4ad4f4ba420.png)
Server loads worlds (seen above) and then there is a decline in TPS leading to a crash. (bellow) 
![Screen Shot 2020-02-18 at 8 39 12 am](https://user-images.githubusercontent.com/32085427/74694223-46e8fe00-522a-11ea-8301-8f5de0faad61.png)
Exact same crash error as previous.

**Comment by 016Nojr** [comment]
Pack update coming in a few days, hopefully this fixes that bug. If it still exists, please report it to the new bug tracker with fresh logs.
