### ISSUE TITLE
Server not working like single player game -> graphite not smelting into liquifacted coal

### ISSUE THREAD

**Issue by haddow777** [FTBTeam/FTB-Revelation-2#343]
* **Modpack Version**: 3.2.1 for 1.12.2

* **Issue**: 
Hello, I started playing FTB Revelation in single player mode and built a power gen system that relied on the Tinker's smelter to smelt graphite ingots into liquifacted coal. This worked fine. Then I wanted to use a hosted server, so I set one up and used the save game from my single player world. The smelter now doesn't smelt graphite at all. It says it graphite doesn't melt. I can go into JEI and the recipe is still listed, though I should mention the temperature listed for melting graphite is 0 degrees. If I go back to my single player game, it works fine. 
Of course, I've thought about just trashing that power gen system and moving on, but I'm worried that graphite isn't the only thing affected. There doesn't seem to be a good reason why it's happening.
I've tried copying config files over and it did nothing.

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/f252a988

* **Is it Repeatable?**: 
I first had the host site do an automated install of the 3.2.0 server and this issue happened. They didn't have an option to install 3.2.1, so I manually installed that version and this issue persisted. Each was a completely separate server. So it seems to have repeated.

* **Mod/s Affected**: Not sure. Graphite is supplied by Nuclearcraft (I added this to follow Direwolf20s lets play) and extreme reactors. Thermal foundation supplies the liquifacted coal. Also, the recipe requires the Tinker's smeltery. I have no idea which mod creates the recipe or where it would be defined. I searched through the logs and configs to see if I could find it, but couldn't.

**Comment by haddow777** [comment]
I went back into my single player game, which is smelting graphite like a champ, and checked the JEI recipe. It's also listed as having a melting temperature of 0 degrees there. So that didn't change with the server.
Also, after looking into things for a bit, It seems Thermal Foundation is behind the recipet.

**Comment by haddow777** [comment]
Okay, did a little more testing. In single player, I removed the lava and replaced it with pyrotheum. It didn't seem to recognize it. It showed the fuel meter as being empty and when I hovered the mouse over the fuel meter, it still showed lava. In the server version though, it showed the pyrotheum in the fuel meter, but said that it wasn't a valid fuel. So it appears that the connection between Thermal Foundation and Tinkers isn't working on the server.
But to complicate things further, AE2 isn't working. I was able to pull a bucket out of it, but I couldn't put a bucket back in. Also, it wouldn't autocraft items. I said it was, but it just sat there not crafting them, and I have a massive autocrafting tree where every interface has a molecular assembler filled with acceleration cards for every side.
I'm thinking the installation must be fubar.

**Comment by haddow777** [comment]
Okay, so I installed a new 3.2.0 on my own machine. Did the FTBinstall.bat and the ServerStart.bat. Installed a few extra mods (which all work in my single player game), and made some minor config changes. This is basically the setup my single player game has.
I started it and managed to get it and the client running. Logged in, and all the same issues are happening. No idea why. How can the server be different from the single player version?

**Comment by CitiesXL2815** [comment]
dude do not report this issue to FTB revelation bc NuclearCraft is not in the pack so pls report it to Dev of NuclearCraft

**Comment by haddow777** [comment]
Did you read it? Ya, I had Nuclearcraft, but what does that have to do with
it? The pack works in single player and not in server mode. Nothing that
has gone wrong is even related to Nuclearcraft.

**Comment by rune-san** [comment]
As far as what it has to do with anything, I believe you mentioned if yourself in your original post. The material you're having issue with, graphite ingots, are indeed 100% solely related to Nuclearcraft. This all seems to stem from Nuclearcraft's use of graphite being derived from coal in their Manufactory. I'd assume this is more to do with Tinker's Smeltery and the use of it's recipe generation system, and yes, these things can behave differently between Single Player, and Multiplayer configurations.

The summary of it is that the pack works just fine in Single and Multiplayer. The addition of Nuclearcraft, which brings the graphite aspect to the table, is the thing that behaves inconsistently.

A way to validate the behavior of each together is to create a 1.12 Minecraft pack with just Tinkers Construct and Nuclearcraft installed. See how those materials behave without all the other FTB Interaction involved.

**Comment by 016Nojr** [comment]
We dont support modified versions of the packs
