### ISSUE TITLE
Game crashes upon starting without further notice.

### ISSUE THREAD

**Issue by lineargraph** [FTBTeam/FTB-Revelation-2#346]
* **Modpack Version**: 3.2.1

* **Issue**: Upon starting the modpack via the CurseForge/Twitch launcher it crashes in with this message:

![Game crash](https://i.imgur.com/Ja8IEVe.png)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5471212c

* **Is it Repeatable?**: Yes, it happens every time.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by CitiesXL2815** [comment]
send us full log with Debug activated

**Comment by lineargraph** [comment]
I sent you the full log from the log folder. Otherwise this is the popout log: https://paste.feed-the-beast.com/view/3d5f615b This is what confused me the most. There is none of that usual debug with a mod list, etc.

**Comment by lineargraph** [comment]
Okay to follow up on this: I had a corrupt vanilla JAR file (for whatever reason). To fix it, simply delete `Twitch\Minecraft\Install\versions\YOURMCVERSIONHERE` where `YOURMCVERSIONHERE` is `1.12.2` for revelations.
