### ISSUE TITLE
Botania mana pool CTD

### ISSUE THREAD

**Issue by dvdmcwilliams** [FTBTeam/FTB-Revelation-2#347]
* **Modpack Version**: 3.2.0
* **Issue**: My game crashes whenever i teleport to someone with mana pools around, or randomly in my base, i cant use botania mod, when i want to fill the pools they remain with the initial load and stay as is, tried gourmarillys, and endoflames, they are linked to the spreader and it to the pool, but it wont fill, the admin of the server i play daily made a fix to my botania jar, it prevents me to crash with botania stuff around, but as i said mana pools wont fill which makes the mod totally unusable, if i come back to the unedited botania jar the game crash everytime as stated above.
I could avoid the CTD by adding vanillafix to the mods folder, at least wont have to reload the game everytime it crash, altought the problem persists.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b6d51fd8

* **Is it Repeatable?**: it's random, sometimes occur sometimes wont

* **Mod/s Affected**: <!-- optional; botania r.1.10-361

* **Known Fix**: sadly dont know how to fix this.

**Comment by CitiesXL2815** [comment]
try again without Optifine see if it still a problem

**Comment by dvdmcwilliams** [comment]
> try again without Optifine see if it still a problem

I could solve the problem, it was voxelmap, as many other players told me they had the same problem.
