### ISSUE TITLE
Blood Magic Gathering of Forsaken Souls working without Demon Will in Aura

### ISSUE THREAD

**Issue by Hazmatik** [FTBTeam/FTB-Revelation-2#348]
* **Modpack Version**: 3.2.1

* **Issue**: Blood Magic's Gathering of Forsaken Souls ritual is growing demon will crystals without any demon will in the chunk's aura. The ritual is supposed to grow the crystals by using the demon will in the chunks aura and shouldn't be growing them without it.

* **Link to Log or Crash File Paste**: no log but here is a GIF that shows the crystal growing without will in the chunk (aura gauge in top left) https://gyazo.com/ee8a82623d3cb1d3cd378d71bcd1b1bd

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Blood Magic 2.4.1-103

* **Known Fix**: None known

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
