### ISSUE TITLE
Cant light fires???

### ISSUE THREAD

**Issue by oChuckk** [FTBTeam/FTB-Revelation-2#349]
Version 1.12.2

As of a few days ago i can no longer light fires on blocks, this stops me from creating grains of infinity etc. tried using flint and steel and fire lighter block. fire appears for less than a second before going away. This worked fine around a week or so ago. this is on my single player world so no moderator stopping the use of fire.

I have repeated this issue in both my single player world and in my multiplayer server where i am the owner.

**Comment by CitiesXL2815** [comment]
Needs more information like FTBRev version and mods affected

**Comment by oChuckk** [comment]
FTBRev 3.2.0

Mods affected are none in specific which is why i left it out, i cant set fire to blocks so it kind of affects all and none?

**Comment by 016Nojr** [comment]
I can light fires fine
