### ISSUE TITLE
Dank null dupp

### ISSUE THREAD

**Issue by OmegaDarkMatter** [FTBTeam/FTB-Revelation-2#35]
* **Modpack Version**: 2.0

* **Issue**: item dupp

* **Is it Repeatable?**: yep

* **Mod/s Affected**: /dank/null and any mod with moveable storage items that keep there inventory

* **Known Fix**: there is a blacklist for items that cant be put into the /dank/null, just add like all the iron backpacts and Wooden Storage Crates

**Comment by tfox83** [comment]
added these items to the blacklist.
