### ISSUE TITLE
MineTogether caused IndexOutOfBoundsException when changing Friend list hotkey

### ISSUE THREAD

**Issue by jarquafelmu** [FTBTeam/FTB-Revelation-2#350]
* **Modpack Version**: v3.2.1

* **Issue**: MineTogether caused IndexOutOfBoundsException when changing Friend list hotkey. Reference to issue on their gist https://github.com/CreeperHost/CreeperHostGui/issues/156

* **Link to Log or Crash File Paste**: https://gist.github.com/jarquafelmu/8bca5a26025aa64a1f80aa8087e01a25

* **Is it Repeatable?**: Yes. Changing volume levels now reliably crashes my game.

* **Mod/s Affected**: 
MineTogether v1.10.2-2.2.0

* **Known Fix**: 
Edit: According to the MineTogether team, upgrading to mod version 2.2.1 will fix this issue

**Comment by jarquafelmu** [comment]
According to the MineTogether team, this issue has been resolved in the latest patch https://github.com/CreeperHost/CreeperHostGui/issues/156 The modpack is one patch behind this latest one. the mod pack is at version 2.2.0 when it needs to be at version 2.2.1

**Comment by 016Nojr** [comment]
Updated in pack version coming in a few days
