### ISSUE TITLE
[Crash] Mod interaction crash involving Simply Jetpacks 2 and Wireless Crafting Terminal

### ISSUE THREAD

**Issue by jarquafelmu** [FTBTeam/FTB-Revelation-2#351]
## Modpack Version
v3.2.1

## Issue: 
Using a Wireless Crafting Terminal bauble and a Simply Jetpacks 2 jetpack or Jetplate will cause only the user wearing the two to crash and will prevent them from logging back in.

## Link to Log or Crash File Paste

It has happened in my game and this is a known issue by the Simply Jetpack 2 devs and has been fixed but this server is using an out of date version.

Reference to issue: https://github.com/Tomson124/SimplyJetpacks-2/issues/143

## Is it Repeatable?
Yes

## Mod/s Affected
**Simply Jetpacks 2** v1.12.2-2.213.66

## Known Fix
Update Simply Jetpacks 2 mod version **v1.12.2-2.213.66** -> **v1.12.2-2.214.67** (or latest).

Once that is done on the server and the users the the affected user will be able to log back into the server and will not have any issues using the two items.

We manually updated to this latest version on our server and it resolved the issue. So the modpack itself just needs to incorporate this fix so that it works for everyone.

**Comment by felixKroni** [comment]
I have the same issue after i crafted the JetPlate. Im playing on FTB Revelation 3.2.0.
About 1-2 minutes after i log in my whole game crashes. 
[crash-2020-04-15_22.03.04-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/4483509/crash-2020-04-15_22.03.04-client.txt)

**Comment by jarquafelmu** [comment]
If you are on a private server you can fix it by manually updating the version of Simply Jetpacks you use. You are on a public server then SOL

**Comment by felixKroni** [comment]
i have version 2.2.13.66 on my private server.
Version 2.2.14.67 should work ?
just changing the .jar file should be enough right

**Comment by jarquafelmu** [comment]
Yeah

**Comment by 016Nojr** [comment]
Updated in new pack version coming in a few days
