### ISSUE TITLE
Unable to connect to the server.

### ISSUE THREAD

**Issue by Gluptak** [FTBTeam/FTB-Revelation-2#352]
FTB Continum 1.6.0 / server files for FTB Continum 1.6.0

Disconnects after joining the server, this happens for 3/4 players, only on this package.
There are 12 players on the server, parameters are
RAM 7680 MB
Processor Power 7.6 GHz
And fast ssd NVMe disk

https://paste.feed-the-beast.com/view/c6a56906

Yes, every time someone tries to join.

**Comment by Gluptak** [comment]
Ehh, I'm sorry I just noticed that the link on the curseforge leads here :/
I will change the forum

**Comment by CitiesXL2815** [comment]
dude wrong issue this is FTB Revelation Issue Tracker not Continuum pls report to FTB Continuum Issue Tracker Github

**Comment by Gluptak** [comment]
I know but the ftb continuum page on curseforge links to this forum.

**Comment by Gluptak** [comment]
I have fixed the bug and I think you can close this thread.
