### ISSUE TITLE
Revelation 3.2.0 crash on teleport or walk to base

### ISSUE THREAD

**Issue by Jerryedw** [FTBTeam/FTB-Revelation-2#353]
* **Modpack Version**: FTB Revelation 3.2.0

* **Issue**:  I have had an issue with crashing to desktop.   Happens randomly but always when either teleporting to my base or ever walking to it.  The base area is chunkloaded.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/266a98c6

* **Is it Repeatable?**: Yes but timing is random

* **Known Fix**: All I've tried so far is making sure 8gb of memory is dedicated to minecraft and removing/reinstalling Java x64

**Comment by rune-san** [comment]
This is caused by the p455w0rdsLib mod, which has its own shader stuff going on. Future versions of the mod disable the shaders since it's caused some grief with other mods. I would recommend simply going into p455w0rdsLib.cfg on the client-side config to disable the shader bits.

```
"colored light shader options" {
    # Enables shader support in dependant mods [default: true]
    B:EnableShaders=false
	
    # If true, then colored lighting effects will be added to vanilla items, blocks, and tile entities. [default: true]
    B:EnableVanillaLightingEffects=false

    # Maximum Number of lights to be rendered on the screen at once [range: 4 ~ 256, default: 64]
    I:MaxLights=64

    # Maximum Distance to render a colored light [range: 4.0 ~ 128.0, default: 128.0]
    S:MaxRenderDist=128.0

    # Skips sending light updates to the card some frames. This can speed up fps greatly when bandwidth is a problem. 0 always sends data. [range: 0 ~ 160, default: 10]
    I:NumFramesToSkipWhenRenderingShaders=10
}
```

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
