### ISSUE TITLE
Industrial Wires Multiblock

### ISSUE THREAD

**Issue by tgibbscase501x** [FTBTeam/FTB-Revelation-2#354]
* **3.2.0**: 

Industrial Wires Multi block will not convert RF to EU and kinetic Generator {IC2} appears as invalid in the manual for immersive engineering, in the multi block section {Commutator}.

Yes it is repeatable

Mods Involved IC2, Industrial Wires, Immersive enginnering

Known fix is updating IC2 to a newer version

**Comment by furtabs** [comment]
You have to report this to the Industrial Wires Dev, nothing FTB can do

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
