### ISSUE TITLE
Broken crafting recipes after updating

### ISSUE THREAD

**Issue by niklas2233** [FTBTeam/FTB-Revelation-2#356]
* **Modpack Version**: 
1.6.0
* **Issue**: 
After updating extreme reactors every crafting recipe is broken
* **Is it Repeatable?**: 
yes just update extreme reactors
* **Known Fix**: 
change the scripts to the new materials

**Comment by MacChuck** [comment]
The pack is at version 3.2.0, are you running a way out of date update?

**Comment by niklas2233** [comment]
My bad wrong GitHub, got sent here from curseforge.
