### ISSUE TITLE
Dedicated server crashing when we try to go in the mining world.

### ISSUE THREAD

**Issue by TaawZ** [FTBTeam/FTB-Revelation-2#358]
Hello guys, some friends and I are playing Revelation 3.2.0
Things were going well until this morning when the server started to crash because we'were trying to go in the mining world from "aroma1997sdimension".
Going in regular world and the nether cause no issues. We built everything farming related in the mining world so we're trying to find a workaround to not lose everything.
The server didn't crashed the day before, it only started to happen after a daily restart. We don't have backups. I will provide the log files, hoping there's a fix without resetting that dimension.

https://pastebin.com/hksmDhy6

Thank you for your time

**Comment by CitiesXL2815** [comment]
so FTB has backup system called FTB Backups and can be found either in the server .minecraft folder called backups

**Comment by CitiesXL2815** [comment]
so can roleback

**Comment by 016Nojr** [comment]
This is a completely new issue . Try deleting the mining dim file, and rejoin it.
