### ISSUE TITLE
Thaumcraft

### ISSUE THREAD

**Issue by Winter0The0Mage** [FTBTeam/FTB-Revelation-2#36]
Hello I'm Winter the Apprentice mage
* **Modpack Version**:  2.0

* **Issue**:  goggles of  revealing dont work

* **Is it Repeatable?**: yes

* **Mod/s Affected**: idk

* **Known Fix**: idk

**Comment by Boomflex** [comment]
Please report this to the relevant Mod Developer.

Not fixable on a pack level.
