### ISSUE TITLE
Launch Crashes

### ISSUE THREAD

**Issue by TheUnknowBoy** [FTBTeam/FTB-Revelation-2#360]
* **Modpack Version**: 3.2.1 & 3.2.0

* **Issue**: When ever I try to play Revelation 1.12 version, it crashes at around the end of 2/7. Up to date java 8 version and It kind of works with the downgraded version but I'm missing 9 mods then.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6b2e3171

* **Is it Repeatable?**: Yes, happens when i try to launch it.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by rune-san** [comment]
I see two things off the bat:

JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)

Problematic frame:
C  [ig4icd64.dll+0xd083a]

So I don't know what Java version you're downgrading to, but it looks like you're using the "bundled" version of Java 8 Update 51, which is from 2015 and very old. I'd highly recommend updating to the latest / greatest Java 8 (Update 241 as of this post), and launching the game with that.

The second thing regarding the Problematic Frame refers to a DLL file used by your Intel Integrated Graphics. Have you updated your Intel GPU Drivers in a while? If you haven't, I'd recommend giving those an upgrade as well.

Once those two above are done, give launching the game a try again.

**Comment by 016Nojr** [comment]
Try updating your Java and drivers which was mentioned above
