### ISSUE TITLE
Mob spawning at ridiculous rates

### ISSUE THREAD

**Issue by Chaise91** [FTBTeam/FTB-Revelation-2#361]
* **Modpack Version**: 3.2.1. This is a server which I am connecting to to play locally.

* **Issue**: As I normally play through the world, aggressive mobs are spawning at insane rates. It almost appears to trigger a massive surge whenever one shows up, several are immediately behind it, as if it were being mutliplied. The difficulty is set to easy.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: I've added a few plug-ins/mods to the server side. Luckperms, griefprevention, world edit, nucleus and commandsigns.

* **Known Fix**: Not yet!

**Comment by 016Nojr** [comment]
We're not changing mob spawn rates, so this is nothing I can change. Nobody else has reported this issue
