### ISSUE TITLE
Foxhound

### ISSUE THREAD

**Issue by jamthief** [FTBTeam/FTB-Revelation-2#362]
* **Modpack Version**: 3.2.1

* **Issue**: Spawning of the Quark Foxhound in the Nether is flawed. The mob slowly fills up the Nether but they never despawn, because of the way they have been implemented. Eventually the hostile mob cap is reached and nothing in the Nether will spawn.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Quark-r1.6-177

* **Known Fix**: disable Foxhound spawn, by setting `world { B:Foxhounds=false }` in the quark config.

**Comment by BlackQuests** [comment]
This bug was also fixed in Quark-r1.6-178

**Comment by 016Nojr** [comment]
Quark is updated in the pack update coming in a few days
