### ISSUE TITLE
Inconsistent Dynamo Behaviour

### ISSUE THREAD

**Issue by connorlurring** [FTBTeam/FTB-Revelation-2#363]
* **Modpack Version**: 3.2.0 (running on the server downloaded from the launcher)

* **Issue**: After breaking a dynamo, when the dynamo is replaced it is no longer able to output power. The dynamo only begins to transfer power again after more fuel is placed in it, updating the block.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thermal Expansion

* **Known Fix**: None known

**Comment by CitiesXL2815** [comment]
That's not bug it needs fuel to output power to the machine or energy cell it's been like that for years if you don't like it go and complain to King Lemming at there discord lol

**Comment by CitiesXL2815** [comment]
but i do believe there is option tweak in the .cfg don't remember which one
