### ISSUE TITLE
Building Sticks in Minecraft with the FTP Revelations Mod Ver. 1.12.2

### ISSUE THREAD

**Issue by Maekshyft** [FTBTeam/FTB-Revelation-2#364]
* **Modpack Version**: 1.12.2 is the version 

* **Issue**: the issue is when creating sticks in Minecraft. The way it's shown to create sticks in the game is to have one wood plank in the center of the 9 squares and another wood plank in the top left corner of the 9 squares. The ACTUAL way you create sticks is by having wood planks in the top left corner and the middle left square.

* **Link to Log or Crash File Paste**: No Crash file.

* **Is it Repeatable?**: Yes, it is repeatable.

* **Mod/s Affected**: the FTB Revelations version 1.12.2

* **Known Fix**: No known fix
![Actual build](https://user-images.githubusercontent.com/62820503/78320498-9e6fce80-7537-11ea-811a-651145219fd8.png)
![Demonstrated build](https://user-images.githubusercontent.com/62820503/78320500-9f086500-7537-11ea-9889-310c4c547d66.png)

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
