### ISSUE TITLE
MineTogether's Privacy Policy is set TRUE by default

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-Revelation-2#365]
https://dist.modpacks.ch/modpacks/2/FTB%20Revelation-3.2.0/config/minetogether/gdpr.txt is the current file for 3.2.0.

Should be set false by default.

**Comment by Jake-E** [comment]
Newer versions of the mod don't store that file in the config folder, they're stored in local which does not get shipped.
This is a non-issue if the modpack gets updated.

**Comment by Jake-E** [comment]
That's a point... Have you actually launched the pack and checked that this is the actual file used? Because this may just be left-over files.

**Comment by jamierocks** [comment]
Looks like its a lingering file.
