### ISSUE TITLE
JEI crashes minecraft when I try to use search

### ISSUE THREAD

**Issue by spaceshooter** [FTBTeam/FTB-Revelation-2#369]
* **Modpack Version**: 3.2.0

* **Issue**: If I try to search something in JEI it immediately crashes my minecraft process (even FTB console) and damages my save so I can't use it anymore. Although I still can load broken save, 
every time I try to open inventory - it crashes again. Deleting NEI folders in save folder does not help.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3069367c

* **Is it Repeatable?**: yes

* **Mod/s Affected**: jei_1.12.2-4.15.0.268

* **Known Fix**:

**Comment by 016Nojr** [comment]
I cant replicate this issue. If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
