### ISSUE TITLE
Thermal Expansion Induction Smelter not working

### ISSUE THREAD

**Issue by LotsofSpace** [FTBTeam/FTB-Revelation-2#370]
**Modpack Version**: 3.2.0

* **Issue**: Suddenly, Induction Smelter from Thermal Expansion no longer allows me to make steel ingots using 4 pulverized coal and one iron ingot/pulverized iron, it always consumes all the ingredients and outputs nothing, wasting my coal and iron. It used to work before suddenly it stopped working.

* **Is it Repeatable?**: Yes it keeps happening every time I try

* **Mod/s Affected**: Thermal Expansion 5.5.4.43

**Comment by ghost** [comment]
Just tested this in 3.4.0, works fine. If possible, try updating? :)
