### ISSUE TITLE
FTB Revelations Server Crash on Startup

### ISSUE THREAD

**Issue by tweedjt** [FTBTeam/FTB-Revelation-2#371]
Modpack Version: 3.2.0

Issue: Server crash on startup after many attempts of downloading from FTB client and changing permissions on CentOS

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/69088d1d

Is it Repeatable?: yes

**Comment by 016Nojr** [comment]
I need more logs than this, please resubmit the issue to the new bug tracker
