### ISSUE TITLE
WindowsStreamPump Error

### ISSUE THREAD

**Issue by makadus** [FTBTeam/FTB-Revelation-2#372]
* **Modpack Version**: Server 3.2.0

* **Issue**: WindowsStreamPump Error on Server Load

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/53234763

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Woot? Seems to happen on Woot load, but may be red herring. 

The issue does not prevent the server from loading though it does stop the CMD window from updating pass the error which means I have to kill the process in order to get the server stop.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
