### ISSUE TITLE
very low fps

### ISSUE THREAD

**Issue by atreyu0107** [FTBTeam/FTB-Revelation-2#375]
I've been experiencing extreme loss of fps. I have optifine installed, all settings on low, and 7gb of ram given to it, I have 15 GB all together. 
it says that this mod pack has "optimal fps" yet this mod pack has the least fps out of all the modpacks I've tried
does anyone know of why this is and anyway for me to gain fps?

thanks,
atreyu

**Comment by 016Nojr** [comment]
We dont provide support when Optifine is present. I'll need more details about this if you want me to help. If this issue still persists, please report it to the new bug tracker with logs.
