### ISSUE TITLE
Game crash when entering world.

### ISSUE THREAD

**Issue by daviidxestrada** [FTBTeam/FTB-Revelation-2#376]
I was playing last night and everything went well, and I stopped playing so I closed the game, today I entered to play but theres a crash report and It puts something about minetogether I dont know how to fix it, hope you can help, Ill attach the latest log and the crash report to see if you can help me
[latest.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4638166/latest.log)
[crash-2020-05-16_11.49.32-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/4638167/crash-2020-05-16_11.49.32-server.txt)

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
