### ISSUE TITLE
Dirt Nether

### ISSUE THREAD

**Issue by phantom745** [FTBTeam/FTB-Revelation-2#377]
I'm not sure if this is the fault of someone on my server or the modpack itself, but the Nether has slowly turned to dirt
![2020-05-15_11 35 28](https://user-images.githubusercontent.com/4897085/82136778-ac6f6b00-97d6-11ea-8673-4e621967e186.png)

**Comment by rune-san** [comment]
I don't believe this is a mod doing this, especially because it's all been flattened.

**Comment by phantom745** [comment]
Thats the lava lakes being turned to dirt, also the netherrack is turning to dirt as well, the only thing not turning to dirt is the bone blocks

**Comment by phantom745** [comment]
The only thing similar to this is the Extra Utilities 2 pump, but that should only replace the lava. It should not replace netherrack or the ores.

**Comment by 016Nojr** [comment]
My guess is that it's a combination of both the quarry and the pump from ExUtils
