### ISSUE TITLE
Server update issue while connecting

### ISSUE THREAD

**Issue by xmashaa** [FTBTeam/FTB-Revelation-2#379]
* **Modpack Version**:  FTB Continuum 1.6.0 

* **Issue**: yesterday i managed to get acces on my server, but today i can't and i got a message while trying to connect which says "server mod rejections: FTB Ultimine tic: requires version 1.0.1 but mod is not found on client". I already got a problem like this and all i had to do was update the modpack. But i'm looking on twitch launcher and there's no update for this modpack

* **Link to Log or Crash File Paste**: server mod rejections: FTB Ultimine tic: requires version 1.0.1 but mod is not found on client

* **Is it Repeatable?**:  everytime i try to log in my server

* **Mod/s Affected**: FTB Ultimine TIC version 1.0.1

* **Known Fix**: update the modpack, but there's no update available

**Comment by TJeo00** [comment]
me too, add the new version 1.6.1 on twitch please... else we can't play =(

**Comment by thenoobofthewest** [comment]
I realise this isn't overly helpful but you can get the mod pack up to date on the FTB Launcher. The download link for it is on their website.

**Comment by Sunekaer** [comment]
Wrong issue tracker
