### ISSUE TITLE
So... I accidentally erased the custom main menu...

### ISSUE THREAD

**Issue by whatsapp2** [FTBTeam/FTB-Revelation-2#380]
* **Modpack Version**: 3.2.1

* **Issue**: I erased the custom main menu files and now the menu shows a missing texture

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: custom main menu

* **Known Fix**: Anyone who can provide me the image files? I can't reload the modpack because I'm afraid I would corrupt my minecraft worlds

**Comment by thenoobofthewest** [comment]
reinstall it as a new instance then copy the worlds to that. You'll be fine.

**Comment by Sunekaer** [comment]
reinstall the pack.
