### ISSUE TITLE
Game crashes upon launch

### ISSUE THREAD

**Issue by Thothore** [FTBTeam/FTB-Revelation-2#381]
* **Modpack Version**: 3.2.0

* **Issue**: When I launch the game from FTBApp which redirects me to the official MC launcher it starts loading but around initialisation phase (2 of 7) Minecraft stops and the launcher says that an error occurred and the game crashed

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b3419c6b

* **Is it Repeatable?**: Every time I try to launch Revelation

* **Mod/s Affected**: Not sure but in the logs it mentions some error with Snad

* **Known Fix**:

**Comment by 016Nojr** [comment]
If this bug still persists after the new pack update coming in a few days I'll need a new report on the new bug tracker with logs provided
