### ISSUE TITLE
Crashing when logging on. Constantly.

### ISSUE THREAD

**Issue by fdarnell82** [FTBTeam/FTB-Revelation-2#382]
-->

* **Modpack Version**: 3.2.1

* **Issue**: 90 percent of the time when I try to log on, It generates a crash error and log report.

[hs_err_pid4736.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727746/hs_err_pid4736.log)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: <N/a
* **Known Fix**: N/a

**Comment by fdarnell82** [comment]
[hs_err_pid14280.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727751/hs_err_pid14280.log)
[hs_err_pid13676.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727752/hs_err_pid13676.log)
[hs_err_pid12948.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727753/hs_err_pid12948.log)
[hs_err_pid12696.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727754/hs_err_pid12696.log)
[hs_err_pid12552.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727755/hs_err_pid12552.log)
[hs_err_pid12256.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727756/hs_err_pid12256.log)
[hs_err_pid12236.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727757/hs_err_pid12236.log)
[hs_err_pid11688.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727758/hs_err_pid11688.log)
[hs_err_pid11484.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727759/hs_err_pid11484.log)
[hs_err_pid11280.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727760/hs_err_pid11280.log)
[hs_err_pid11180.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727762/hs_err_pid11180.log)
[hs_err_pid10912.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727763/hs_err_pid10912.log)
[hs_err_pid10840.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727764/hs_err_pid10840.log)
[hs_err_pid9744.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727766/hs_err_pid9744.log)
[hs_err_pid9280.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727767/hs_err_pid9280.log)
[hs_err_pid8696.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727770/hs_err_pid8696.log)
[hs_err_pid8572.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727771/hs_err_pid8572.log)
[hs_err_pid8272.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727772/hs_err_pid8272.log)
[hs_err_pid6880.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727773/hs_err_pid6880.log)
[hs_err_pid6200.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727774/hs_err_pid6200.log)
[hs_err_pid5432.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727775/hs_err_pid5432.log)
[hs_err_pid4784.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727776/hs_err_pid4784.log)
[hs_err_pid4744.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727777/hs_err_pid4744.log)
[hs_err_pid4736.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727778/hs_err_pid4736.log)
[hs_err_pid4620.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727779/hs_err_pid4620.log)
[hs_err_pid4252.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727780/hs_err_pid4252.log)
[hs_err_pid2700.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727781/hs_err_pid2700.log)
[hs_err_pid2500.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727782/hs_err_pid2500.log)
[hs_err_pid172.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4727784/hs_err_pid172.log)

**Comment by thenoobofthewest** [comment]
Not a lot to go off in the log as it's not a mini dump. I believe it's corrupt heap memory in your java application. Try fully uninstalling java and reinstalling.
