### ISSUE TITLE
Keeps crashing while loading up mod pack

### ISSUE THREAD

**Issue by jslang04** [FTBTeam/FTB-Revelation-2#383]
* **Modpack Version**: 3.1.0

* **Issue**: Whenever I am loading the modpack, it will eventually crash and give me pretty much the same thing, I've tried different versions of java, different methods of using the modpack (Twitch and MultiMC) and different amounts of RAM. There's still no luck

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/bbf08628

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: None

* **Known Fix**: None

**Comment by 016Nojr** [comment]
Pack update coming in a few days, hopefully this fixes that bug. If it still exists, please report it to the new bug tracker with fresh logs.
