### ISSUE TITLE
Quest "Cyber Storage" Impossible To complete

### ISSUE THREAD

**Issue by bicepraptor** [FTBTeam/FTB-Revelation-2#384]
* 1.6.0

* The first quest that starts the player into refined storage titled "Cyber Storage" is impossible to complete, due to the quest requiring the solderer. An item that was removed in the new version of the mod. Specifically, the solderer existed in 1.5 and was removed in 1.6, the version the modpack uses

* N/A no crash occurred

* Yes, the issue occurs every time the game is loaded

* refined storage

* remove the solderer as an item that needs to be obtained in the quest titled "Cyber Storage"

**Comment by Sunekaer** [comment]
This pack doesnt have quest, did you make the issue on the right repo?
