### ISSUE TITLE
Brycensd Crash won't load world 

### ISSUE THREAD

**Issue by Brycensd** [FTBTeam/FTB-Revelation-2#385]
* **Mod pack Version**: 
revaluation v3.2.0

* **Issue**: < 
[46b49e39.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/4807351/46b49e39.txt)
  My game crashed and now I can not access my world it continues to crash while trying to load the world.

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/46b49e39

* **Is it Repeatable?**: 
It still doesn't work.

* **Mod/s Affected**: 
Idk
* **Known Fix**:

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
