### ISSUE TITLE
Immersive Engineering Assembler will not create conveyor belt

### ISSUE THREAD

**Issue by B-Villatoro** [FTBTeam/FTB-Revelation-2#386]
* **Modpack Version**: FTBContinuum-1.6.0

* **Issue**: Using an assembler in continuum multiplayer will create conveyor built 

* **Is it Repeatable?**: Yes, Issue was recreated by making different assemblers by different users with the same result 

* **Mod/s Affected**: Immersive Engineering

**Comment by Sunekaer** [comment]
Wrong issue tracker
