### ISSUE TITLE
Crash on login, probably Industrial-Foregoing Inverted Lenses

### ISSUE THREAD

**Issue by christiangeissler** [FTBTeam/FTB-Revelation-2#389]
* **Modpack Version**: 3.2.0

* **Issue**: The first time the game crashed was shortly after working on the laser drills from industrial foregoing. Afterwards, I was not able to login to the game any longer and it crashed every time sometime after I clicked on my safegame to load it. After looking through the crash-log and some googling, I found an explaination that could be right, since I just added inverted lenses to my laser drill before the crash happended the first time (right in the game) (see known fix section below)

The crash should therefore be solved when Industrial-Foregoing with the related fix is updated into the pack.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d7ddabb5

* **Is it Repeatable?**: yes.

* **Mod/s Affected**: Probably: Industrial-Foregoing

* **Known Fix**: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/595

**Comment by thenoobofthewest** [comment]
Looks like a structure of block is struggling to render/chunk load. 
Looks like you need to assign more memory to the pack. From the log you only have 4.7gb of ram assigned.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
