### ISSUE TITLE
game crashing bug

### ISSUE THREAD

**Issue by gtgman1233** [FTBTeam/FTB-Revelation-2#39]
* **Modpack : ftb revelation 2.1 beta

* **Issue : Crashing when pressing u while hovering over endstone

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/aa4dc800

* **Is it Repeatable?**: yes

* **Mod/s Affected**: not sure

* **Known Fix**: no

**Comment by tfox83** [comment]
Submitted to Dev:  https://github.com/mezz/JustEnoughItems/issues/1278

**Comment by tfox83** [comment]
Maybe a ExU issue however I was not able to reproduce in latest update.
