### ISSUE TITLE
[Question] How is the modpack optimized? Does that include for servers?

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [FTBTeam/FTB-Revelation-2#390]
The template is not applicable as I have a question not an issue and it said to go here instead of a Discord server or something.

The pack explains it aims to provide maximum optimization and high FPS but has minimal config changes. What, exactly, did you do to optimize the modpack? I know you can add mods & startup flags that optimize the server but from my understanding a lot of optimization comes from banning items that cause extreme TPS drops etc, especially on multiplayer servers.

When the pack says it is highly optimized does that include multiplayer servers with 20 players online at once?

I appreciate you taking the time to read and respond to this. Thank you!

**Comment by 016Nojr** [comment]
I am new to maintaining the back-end of Revelations, but as far as I know the pack contains Foam Fix and Phosphor which both improves pack performance, we also provide server arguments. At the moment I'm not aware of any other things that's changed from our side.
