### ISSUE TITLE
Playing on Lan server, Keep disconnecting when using Draconic evolution stuff. (FTB Revelations)

### ISSUE THREAD

**Issue by shadowsence** [FTBTeam/FTB-Revelation-2#393]
* **I am playing with my roommate on lan. He is the host. When ever im around the stabilized spawner or if i try to access the mob grinder or if i try to use the fusion crafter, or the celestial manipulator i get disconnected from the server. There is no error or code or log or anything it just kicks me to main menu. All of these things work in single player. There might be more things but these are the ones soo far and all from the same mod. i don't have any issues with other mods in the pack
-->**: 

* **There a'rent any as far as i can see. it just disconects and thats the end**: 

* **Is it Repeatable? Yes i can repeat it over and over as often as i want**: 

* **Draconic Evolution 1.12.2-2.3.24.349**: 

* **Known Fix**: 

Update if i host the lan and he joins me the same issues happen just in reverse

**Comment by shadowsence** [comment]
Update if i host the lan and he joins me the same issues happen just in reverse

**Comment by thenoobofthewest** [comment]
Since there is no error log It's hard to diagnose. I can only suggest making sure you both have a good amount of ram assigned to the pack, the minimum is 4gb. Maybe try increasing this.

**Comment by rsprenne** [comment]
I had the same issue in my world. I had placed a stabilized spawner, and whenever my friends tried to join they were disconnected. I removed the spawner and they were able to connect again. Changing the amount of ram assigned to the pack didn't help.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
