### ISSUE TITLE
Game crashes before even hitting the title screen

### ISSUE THREAD

**Issue by BatmanJesus4444** [FTBTeam/FTB-Revelation-2#394]
* **Modpack Version**: Version: 3.2.1

* **Issue**: Crashes before even hitting the title screen

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a3011cf8

* **Is it Repeatable?**: It happens every time, I can't even get in

**Comment by thenoobofthewest** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceede

Out of memory. Make sure you have 64bit java and if you're still getting problems increase assigned ram to the pack.

**Comment by rune-san** [comment]
You only have the default <3GB of RAM assigned. Pack page states 4GB minimum dedicated to the pack. Increase RAM dedicated to the pack to between 4-6GB and test again. Should resolve your issue.
