### ISSUE TITLE
Missing Mod? Mob Grinding Utilities

### ISSUE THREAD

**Issue by Schnee404** [FTBTeam/FTB-Revelation-2#395]
* **Modpack Version**: <Version: 3.1.0>

* **Issue**: <I cant find or use the mod pack Mob Grinding Utilities, I looked up a how to make a mob farm in revelations and i cant find the needed mob pack to make the farm. I found the items and started to create the framework of the farm. When i got on the server after a bit of a break i could not find the mod. I originally looked up the items in the game and then they where not to be found. If i need to update my world, i would like to know how to update a server and keep the world i play on with friends>

* **Is it Repeatable?**: <yes, cant find it>

* **Mod/s Affected**: <Mob grinding utilities>

**Comment by 016Nojr** [comment]
Mob Grinding Utils is not in the pack
