### ISSUE TITLE
Astral Sorcery shrines do not generate in some world types

### ISSUE THREAD

**Issue by snydej** [FTBTeam/FTB-Revelation-2#396]
* **Modpack Version**: FTBRevelation-3.2.1-1.12.2

* **Issue**: Astral Sorcery shrines do not generate in some world types. For instance I chose the Lost Cities "biosphere" as my world type. There is no biome in my overworld in which an ancient shrine or a desert shrine will generate. I am locked out of Astral Sorcery until this is fixed.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Astral Sorcery, The Lost Cities

* **Known Fix**: Whitelist Astral Sorcery world gen in other dimensions or add more biomes to the whitelist for shrines (for instance adding either dead forest or wasteland would fix the biosphere type.

**Comment by 016Nojr** [comment]
Added Astral Sorcery world gen to Lost Cities
