### ISSUE TITLE
Multiplayer server error

### ISSUE THREAD

**Issue by EstefanoTerenghiGoy** [FTBTeam/FTB-Revelation-2#398]
Hello, i'm having a problem with multiplayer servers

* **Modpack Version**: 3.2.1

* **Issue**: When i join any server, it automatically gives this error: Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: Java.lang.IllegalStateException: Recipe minecraft:crafting:table (net.minecraft.item.crafting.ShapedRecipes@5d01a2eb) produces unregistered item minecraft:crafting:table (net.minecraft.item.ItemBlock@53432aef)

* **Link to Log or Crash File Paste**: I guess i don't crash, i mean it's an error

* **Is it Repeatable?**: Yes, it happens everytime

* **Mod/s Affected**: I don't know

* **Known Fix**: I dunno :(

**Comment by thenoobofthewest** [comment]
One or more of your configs don't match the servers. You can try downloading the server configs and using them. 

If not try reinstalling the pack.

**Comment by 016Nojr** [comment]
I recommend trying this, please post a new issue with complete logs if it doesnt work
