### ISSUE TITLE
Multiplayer server crash

### ISSUE THREAD

**Issue by strutman12345** [FTBTeam/FTB-Revelation-2#399]
Modpack version: FTB Revelation 3.2.0

My issue is that my server is repeatedly crashing, I was advised to seek the mod author's help to diagnose the issue.

Crash log URL:  https://paste.feed-the-beast.com/view/7e96342b

The issue is repeatable within minutes of restarting the server when players are online.

I do not know any details regarding mods causing the issue, but I should note that I have added ICBM-classic-1.12.2-3.3.0b63 to the server. However, it is not clear that this is causing the problem.

Thank you for your help in advance.

**Comment by thenoobofthewest** [comment]
Go into server properties and increase max tick time.
Add a few zeros. It looks like a structure on Exegol is struggling to generate properly

**Comment by 016Nojr** [comment]
We're not supporting a modified version of the pack
