### ISSUE TITLE
Steven's Cart 2 BUG

### ISSUE THREAD

**Issue by VoDAyToN** [FTBTeam/FTB-Revelation-2#40]
* **Modpack Version**: FTB REVELATION (V2.0.0)
* **Issue**:
the problem is in the fashion StevesCarts-1.12.2-2.4.20.99
the problem is that the machine digging after the correct creation of the car, the machine did not put tracks in the height of the height of 61, the machine removed the block below which the machine could not dig further.

* **Link to Log or Crash File Paste**: I do not have logs or Crash because they did not occur

* **Is it Repeatable?**: 
create a digging machine here is a basic list of excavators
-Standard Hull
-Coal Engine
-Iron Drill
-Railer
-Torch Placer
-Bridge Builder
-Internal Storage x3
-Top Chest
-Liquid Sensors
-Height Controller (set below 50)

* **Mod/s Affected**: other modules do not interfere

* **Known Fix**: confusion versions StevesCarts-1.12.2-2.4.20.99 on StevesCarts-1.12.2-2.4.21.105

and my question is when I will update ;D ?

**Comment by tfox83** [comment]
Fixed in next version.

**Comment by VoDAyToN** [comment]
and when can you expect it?
