### ISSUE TITLE
Update SimplyJetpacks 2

### ISSUE THREAD

**Issue by ThomasAunvik** [FTBTeam/FTB-Revelation-2#400]
* **Modpack Version**: 3.2.0

* **Issue**:

Update SimplyJetpacks 2 Mod from version, 2.2.13.66, to a newer version (atleast 2.2.14.67).
Cause: "Crash when RedstoneRepository isn't installed"
Related Issue: https://github.com/Tomson124/SimplyJetpacks-2/issues/142

* **Link to Log or Crash File Paste**: [Crash Log](https://paste.feed-the-beast.com/view/29266714)

* **Is it Repeatable?**: Yes, and crashes every time

* **Mod/s Affected**: Simply Jetpacks 2

* **Known Fix**: Update SimplyJetpacks 2 to at least version 2.2.14.67.

**Comment by ThomasAunvik** [comment]
It does look like updating to the latest version do bring some breaking changes.
My Flux-Infused JetPlate turned into a Reinforced Jetpack.
![buggedrf](https://thaun.dev/img/6q64m.png)
![buggedrf2](https://thaun.dev/img/9liap.png)

**Comment by Darinth** [comment]
Breaking changes that might downgrade jetpacks are preferable to crashes that prevent players from being able to log in without manual intervention to either delete the character or using an nbt editor to to un-equip the jetpack. This would be appreciated for the next revelations update. <3

**Comment by 016Nojr** [comment]
Updated in new pack update coming in a few days. Even if it might have some issues with old worlds, we still decide to push this update
