### ISSUE TITLE
Missing item Cyclic assembler in JEI

### ISSUE THREAD

**Issue by racinmat** [FTBTeam/FTB-Revelation-2#401]
* **Modpack Version**: FTB Revelation 3.2.1

* **Issue**: Cyclic assembler which is part of Thermal Expansion and thus should be present, is not found in JEI.

* **Link to Log or Crash File Paste**: attached file contains logs from startup of the FTB Revelation minectaft, hope it helps.
[tl console.log](https://github.com/FTBTeam/FTB-Revelation-2/files/5286615/tl.console.log)

* **Is it Repeatable?**: I hope so, if not, I'll close the issue.

* **Mod/s Affected**: Thermal Expansion

* **Known Fix**: I don't know, sorry.

**Comment by 016Nojr** [comment]
The machine is called "Sequential Fabricator"

**Comment by racinmat** [comment]
Oh, that explains it, thanks.
