### ISSUE TITLE
Placing wooden post crashes the game.

### ISSUE THREAD

**Issue by racinmat** [FTBTeam/FTB-Revelation-2#402]
* **Modpack Version**: 3.2.1

* **Issue**: After placing wooden post, whole game crashes.
* **Link to Log or Crash File Paste**: Log file attached
[hs_err_pid27216.log](https://github.com/FTBTeam/FTB-Revelation-2/files/5286751/hs_err_pid27216.log)

* **Is it Repeatable?**: No, it crashed once, but after startingthe game again, it worked.

* **Mod/s Affected**: Immersive engineering

* **Known Fix**: I don't know

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
