### ISSUE TITLE
Items not stacking in Extra Utilities 2 generators

### ISSUE THREAD

**Issue by SlowlyJoel** [FTBTeam/FTB-Revelation-2#404]
* **Modpack Version**: Revelation 3.2

* **Issue**: Items won't stack within Extra Utilities 2 generators, occurs in both the furnace and culinary generators. They will accept one item, immediately start burning it, and accept one more in the slot ready to be burned. Any more items placed in simply disappear.

* **Is it Repeatable?**: Yes, reinstalled the pack and the issue persisted across multiple worlds

* **Mod/s Affected**: Extra Utilities 2 v1.0

**Comment by Sunekaer** [comment]
Have you used the generators?
Because then they might have power stored in them and there for they are different blocks and wont stack
