### ISSUE TITLE
Major FPS issues.

### ISSUE THREAD

**Issue by ObscuredVisions** [FTBTeam/FTB-Revelation-2#405]
I'm running the newest version of this pack, and it's my first time playing this pack. Downloaded it through the Twitch launcher and am having huge FPS issues. 
I average 3-15 fps, unless i do not move my mouse for 30 seconds, then it will spike to 30 fps, and immediately drop upon moving. I even turned the setting to lowest quality everything and even 4 render distance. 
I run a 1070 gtx FTW, I5-9700k (i think), and 32gb. I know ram is overkill, but I had extras of same type. I tried allocating 10gb of ram instead of the 6 that's predone. It does not effect my fps.

**Comment by ObscuredVisions** [comment]
Should also add, resources in task managers show nothing topping 44% usage. Here's the pie chart as well.
https://gyazo.com/dc14d9c74b783680fdbb9d6416fa1c70

**Comment by 0rt0** [comment]
I'm no expert here but just curious is you java up to date?
Also check the following:
Start menu, type"configure java", go to advanced tab, and scroll to bottom, under "advanced security settings" section check if "enable the operating system's restricted environment (native sandbox)? If it is enabled try disabling it restarting pc and try playing, if it's not enabled then try enabling it restarting pc then try and play

**Comment by ObscuredVisions** [comment]
I do have Java updated. I ended up deleting twitch launcher, Minecraft, and the modpack. I've stabilized to 150fps lowest settings though.
