### ISSUE TITLE
FTB Rev 3.3.0 Server causing clients to crash

### ISSUE THREAD

**Issue by 0rt0** [FTBTeam/FTB-Revelation-2#406]
* **Modpack Version**: 3.3.0 & 3.2.0

* **Issue**:  Client games are crashing from my server with exception remote host forcibly closed connection... This has happened on 5 different PCs to include the running server (for troubleshooting) so far I have tried moving server to SSD, allocating more ram, move it completely to another computer with NVMe, also tried using server with GUI enabled but that was dumb. ATM operating on 10000RPM HDDs with 32 GBs of RAM @ 3000 on an i7-6700k OCed to 4.3 (the other system was same but i7-10700k @ 5.0) also running server with -d64 augment (potentially the problem?)

* **Link to Log or Crash File Paste**: client - https://paste.feed-the-beast.com/view/5b8b8af0
Server - https://paste.feed-the-beast.com/view/519303c3

* **Is it Repeatable?**:  it’s random and primarily when teleporting as Admin or through portals, primarily around home base in overworld

* **Mod/s Affected**:  unknown

* **Known Fix**:

**Comment by 016Nojr** [comment]
Pack update coming in a few days, hopefully this fixes that bug. If it still exists, please report it to the new bug tracker with fresh logs.
