### ISSUE TITLE
Server Keeps Crashing on Startup FTB Revelation 3.3.0

### ISSUE THREAD

**Issue by Taquios** [FTBTeam/FTB-Revelation-2#409]
* **Modpack Version**: 3.3.0

* **Issue**: Every Time I start the server with the server start it crashes due to missing mods. If I knew which mods they were I would Install them. I made a brand new folder for the server and started fresh and still get the same issue.

* **Link to Log or Crash File Paste**:  http://paste.feed-the-beast.com/
[crash-2020-11-11_16.17.52-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/5526827/crash-2020-11-11_16.17.52-server.txt)

* **Is it Repeatable?**: Yes Every time I have tried to launch.

* **Mod/s Affected**: 4 I believe, however it does not say what mods they are

* **Known Fix**: I believe installing the missing mods may fix the server issue

**Comment by Taquios** [comment]
I was able to fix the issue by deleting all the mods in the mod server with ones from the client side of things. Still unsure which mods were bad so I will leave this open.

**Comment by Jawright9182** [comment]
i cant seem to download this mod without using twitch... so i cant edit what im trying to install. installer crashes on a JEI install

**Comment by 016Nojr** [comment]
Try reinstalling the server files
