### ISSUE TITLE
Fluxnetworks bug

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Revelation-2#41]
* **Modpack Version**: 2.1.0

* **Issue**: Fluxnetworks loses connection, keeps saying unloaded chunk. happens when you go out of the chunk for a long time/logout(server) when chunk is chunkloaded.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Fluxnetworks

* **Known Fix**: Replace the items, then it will work again for sometime

**Comment by tfox83** [comment]
Yes, you will need to use FTBU to load your chunks where you want to have flux networks if you want them to work all the time.
