### ISSUE TITLE
Impossible Villager trade

### ISSUE THREAD

**Issue by ENDvious** [FTBTeam/FTB-Revelation-2#410]
* **Modpack Version**: 3.3.0

* **Issue**: Invalid villager trade, machinist uses the Immersive engineering copper and aluminum ingots and doesnt accept Thermal Foundation copper

* **Is it Repeatable?**: Yes, spawn machinist villager and unlock trades.

* **Mod/s Affected**: Immersive Engineering
![image](https://user-images.githubusercontent.com/48038837/99202879-ac005e80-277e-11eb-90b4-a4b72893958a.png)

**Comment by 016Nojr** [comment]
Changed a config option in IE that hopefully fixes this. Pack update coming in a few days
