### ISSUE TITLE
[MOD ADDITION REQUEST] Buildcraft Fuels for IC2

### ISSUE THREAD

**Issue by FuyuzuKii** [FTBTeam/FTB-Revelation-2#411]
General request thread posted here as well as the forums for FTB Revelations; adding Buildcraft Fuels for IC2. It was recently updated to 1.12.2 in October 2020 and it's sorely lacking in regards to making the Semifluid Generator for IC2 far more versatile. 

It's a simple bridging mod and being an oldschool 1.7 Infinity player I expected it to be present in 1.12 Revelation, and was surprised that it wasn't there, but I found it it's only recently been updated to be compatible with 1.12 Revelation runs on.

Link to the mod's curseforge page attached: https://www.curseforge.com/minecraft/mc-mods/buildcraft-fuels-for-ic2/files

**Comment by 016Nojr** [comment]
Will not be added
