### ISSUE TITLE
Crashing everytime I try to join

### ISSUE THREAD

**Issue by Kvazten** [FTBTeam/FTB-Revelation-2#415]
* **Modpack Version** FTB revelation 3.3.0

* **Issue**: My game is crashing everytime I try to join my server/single player world, ¨unexpected error¨

* **Link to Log or Crash File Paste** https://paste.feed-the-beast.com/view/afb31781

* **Is it Repeatable?** Yes it crashes every time

* **Mod/s Affected**

* **Known Fix**

**Comment by 016Nojr** [comment]
Looks like Inventory Tweaks is bugging out. If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore.
