### ISSUE TITLE
minecraft keeps lagging every 5=10 sec and stops for 5 sec

### ISSUE THREAD

**Issue by DMGSielnt** [FTBTeam/FTB-Revelation-2#416]
So my minecraft keeps lagging every 5-10 sec and then stops for 5 sec and it is making me really angry bc I want to play FTB Revelation bc it is a fun modpack and I enjoy it so much

**Comment by DreagleDaMan** [comment]
Same here.

**Comment by DMGSielnt** [comment]
STILL NOT FIXED!!!!!!!!!!!!!!!!!

**Comment by Sunekaer** [comment]
How much ram do you have assigned?

**Comment by jarlols** [comment]
how do I assign ram YouTube videos' tell me to go to twitch and do it there but it hasn't worked because the "mods" section isn't there for me!! plz help me

**Comment by rune-san** [comment]
Twitch sold CurseForge to Overwolf. Twitch has been throwing up warning banners that as of November 30th, the Mods section would be going away, as everything under that section is now owned by Overwolf. Installing the Overwolf application should automatically detect your old Twitch-based Minecraft instances, and give you access to them again.

https://curseforge.overwolf.com/

**Comment by jarlols** [comment]
thanks but when i download it it stops and says fatal error and stops downloading

**Comment by rune-san** [comment]
I'm not sure what you mean, whether it's the Curseforge app, or something else, and what is saying Fatal Error. You'll need to be more specific. That said, I was able to download the Curseforge app off the website without issue and install it. It automatically found my old Twitch Minecraft instances.

**Comment by jarlols** [comment]
When I download forge straight from the sight it shows the downloading process in the bottom and it usually just says fatal error downloading or failed scanning for viruses

**Comment by jarlols** [comment]
I was able to download forge finally but how do I change my ram in settings or what?

**Comment by braxtondb** [comment]
I have 4 GB assigned but I have the same problem... sometimes, it works perfectly fine, but other times it will do this (for example, it was working fine earlier and then I paused it and put my computer into sleep mode, but when I turned it back on to play it again it's doing this now). All of the graphics settings are at the lowest and render distance is set at 2 chunks.

**Comment by 016Nojr** [comment]
Ram can be changed in the settings on the Overwolf Launcher/FTB App.

Keeping the instance running for too long causes Java's garbage collection to hiccup, so when you start getting regular spikes, try restarting your client.
