### ISSUE TITLE
Game stops responding and freezes on Forge Mod Loader

### ISSUE THREAD

**Issue by terrcorey** [FTBTeam/FTB-Revelation-2#417]
* **Modpack Version**: FTB-Revelation-3.3.0.zip

* **Issue**: I use the Overwolf platform to use CurseForge, and when I launch the game the minecraft window freezes everytime when it reaches Loading - Constructing Mods 1/7 Construction - Forge Mod Loader 3/233

* **Link to Log or Crash File Paste**: I have the logs during the launch, it seems that after it stops responding the log just stops [link](https://pastebin.com/dZdbxEHK)

* **Is it Repeatable?**: yes

* **Known Fix**: N/A

I've tried multiple fixes, by including more ram, loading different forge versions, update java, repairing the profile, but none of them worked. The current amount of ram I'm allocating to this modpack is 10GB. (Surely that's not the problem here right?)

This is the first time for me trying to play FTB Revelation, but it is not the first time I'm playing modpacks. I have played SkyFactory 4 before, but when I tried to launch it now it also freezes during load, although not on Forge Mod Loader. I think it froze on somewhere around Loading 6/7.

Here's a screenshot on the frozen game window
![image](https://user-images.githubusercontent.com/75107193/100410580-25b31900-30aa-11eb-841a-a7a01b0ebe34.png)

**Comment by Sunekaer** [comment]
Could you try with 6gb of ram?
And if that doesnt work provide the latest log

**Comment by terrcorey** [comment]
I've tried with 6gb ram (setting the allocated ram to 6912mb) and the same situation happens
![image](https://user-images.githubusercontent.com/75107193/101238244-dc9e3d00-3719-11eb-887c-37af476da8a6.png)
Also I've discovered another problem, when I try to launch the game for the first time after I turn on my computer, it doesn't even open the minecraft window. But when I try to launch the game again it says game already running. Log is included here: https://pastebin.com/QBtX7tER

When I force quit the java application running in the background, and retry launching the game it is still stuck on the same place.  Log is included here: https://pastebin.com/w9hs4WQR
![image](https://user-images.githubusercontent.com/75107193/101238353-972e3f80-371a-11eb-92fc-76c0714249f3.png)

**Comment by terrcorey** [comment]
After a few tries I got the loading screen to go past forge mod loader, but it got stuck later on Ender IO Applied Energistics Conduits instead. Here's the link to the log: https://pastebin.com/1mHH3skm
And a screenshot of the game window: 
![image](https://user-images.githubusercontent.com/75107193/101239189-939db700-3720-11eb-94be-1ccf3fa7f8f5.png)

**Comment by rune-san** [comment]
I'd also like to hear about the time spent on this Not Responding phase? Because of the nature of several of these Java applications, the actual game showing "Not Responding" in both Windows and Mac is normal to some extent, especially on slower computers. In the case of playing FTB Revelation on an old 2011 Macbook Pro, it can take nearly about 8 minutes for the game to load, and during that time the application itself is relatively unresponsive, making jumps in progress from time to time and otherwise presenting the "spinny wheel" in MacOS.

If the window shows not responding, have you tried just letting it set for 10 minutes to see if it resolves itself?

**Comment by terrcorey** [comment]
Yeah I have tried simply leaving the not responding screen on there for more than 15 minutes and it still doesn't work, also, my device is a predator helios 300, which shouldn't be too slow to launch this game.

**Comment by 016Nojr** [comment]
Pack update coming in a few days, hopefully this fixes that bug. If it still exists, please report it to the new bug tracker with fresh logs.
