### ISSUE TITLE
Loading modpack stuck at JEI ItemStack Aspect Checking

### ISSUE THREAD

**Issue by flleeppyy** [FTBTeam/FTB-Revelation-2#419]
* **Modpack Version**: 
3.2.0
* **Issue**: 
Modpack loading stuck at JEI on "ItemStack Aspect checking at 0%"

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/00a3ac2f

* **Is it Repeatable?**: 
Yes, it repeats every time I run the game

* **Mod/s Affected**: 
Just Enough Items (JEI)

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
