### ISSUE TITLE
Mod suggestion - Mekanism

### ISSUE THREAD

**Issue by CuriousHP** [FTBTeam/FTB-Revelation-2#42]
As being on of the bigger kitchensink style of pack for 1.12.2 versions of minecraft, I believe that a tech mod - Mekanism, would be a nice addition to the pack, as firstly it's little less used (great for people to learn about the mod), second it has x5 ore processing that's aimed towards middle-end game, third thing being that just like draconic evolution, mekanism has a mass-energy storage which could be an alternative to draconic orb.

**Comment by tfox83** [comment]
No, that mod causes nothing but issues with updating, it relies on so much when things update and that mod doesn't, it locks us out of updates.  We experienced this with Beyond and finally had to lock the pack because of it.
