### ISSUE TITLE
Trying to obtain flux for Flux Networks mod

### ISSUE THREAD

**Issue by bwmccue** [FTBTeam/FTB-Revelation-2#421]
* **Modpack Version**: 3.3.0

* **Issue**: When trying to obtain flux for the Flux Networks mod, JEI tells me to throw redstone in lava. This did not work so I consulted the Flux Networks github and it shows that this has been updated so all you have to do is place redstone under obsidian and above bedrock. This also did not work. I noticed the version of Flux Networks included in the pack is not the most updated version so this may be an issue but I am not a programmer so I have no idea. 

* **Link to Log or Crash File Paste**: No Crash File

* **Is it Repeatable?**: Yes no matter what I do I cannot seem to create Flux.

* **Mod/s Affected**: Flux Networks

* **Known Fix**: I was messing around mining redstone near lava and I created flux but I have no idea how I did it.

**Comment by Sunekaer** [comment]
Hi bwmccue,

The dropping Redstone in the lava recipe is disabled, but the chance of flux dropping from Redstone Ores has been increased.
I will add a tooltip

**Comment by bwmccue** [comment]
Hi Sunekaer,

I fixed this issue by manually updating Flux Networks to the latest version
before it updates past 1.12.2 which is the version that my FTB Revelation
is set to. By manually upgrading, the recipe changed to placing redstone
under obsidian and above bedrock.

Thank you,

bwmccue
