### ISSUE TITLE
Dank Null update in 3.4 voids storage

### ISSUE THREAD

**Issue by 04Slash** [FTBTeam/FTB-Revelation-2#424]
* **Modpack Version**:  3.3 -> 3.4

* **Issue**: Dank null was updated in 3.4. In v1.7.95 of Dank Null there was a breaking change that fixed a dupe bug. This resulted in all dank nulls inventories being emptied.

* **Link to Log or Crash File Paste**:  [Curseforge link to changelog](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2935200).

* **Is it Repeatable?**:  Updating from an existing world will result in the issue.

* **Mod/s Affected**:  DankNull-1.12.2-1.6.77.jar -> DankNull-1.12.2-1.7.101.jar

* **Known Fix**:  Can't really "fix" it. I'd imagine the options are to either roll with it or downgrade back to DankNull-1.12.2-1.7.94.jar, the last version before the breaking change. If the version is to be kept then a warning should be given. Though this won't prevent people from reporting it, it will at least be seen by some.

**Comment by tuanle99** [comment]
Damn I lost thousands of common blocks like cobblestone, stone, sand, etc.

**Comment by blairwilson** [comment]
a warning for this would have been great

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore. The mod wont be backported.
