### ISSUE TITLE
Can't use Greatwood logs to make a hopper

### ISSUE THREAD

**Issue by flleeppyy** [FTBTeam/FTB-Revelation-2#426]
* **Modpack Version**: 
3.2.0

* **Issue**: 
There is a recipe for the hopper which says it will take 2 of any type of log. When using Greatwood, it doesn't work.
![image](https://user-images.githubusercontent.com/18307183/100970765-6d8ed180-34ea-11eb-833e-f14f0cdcb79b.png)
![image](https://user-images.githubusercontent.com/18307183/100970781-767fa300-34ea-11eb-9797-82f82900c9cb.png)

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
JustEnoughItems
Thaumcraft

**Comment by 016Nojr** [comment]
Not sure what's the cause of it, but I've got a bad feeling it's related to TC's research tree which blocks some crafting recipes. I cant fix that, and the mod isnt being worked on anymore
