### ISSUE TITLE
Can't join any servers

### ISSUE THREAD

**Issue by tuckerb77** [FTBTeam/FTB-Revelation-2#427]
* **Modpack Version**: 
Revelations 3.4.0
* **Issue**: 
I can't join my friend on his server keeps on saying I have the wrong version, even though he has the same modpack downloaded
![image]https://user-images.githubusercontent.com/75443171/101064347-bf664480-3548-11eb-930a-c82eb7c6c380.png

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes the issue keeps on repeating
* **Mod/s Affected**: 
Dank/null
AE2 Wireless terminals
Refined Storage addons
Wireless Crafting Terminal p455w0rd's Library
* **Known Fix**:

**Comment by SmallerGaia** [comment]
I just reinstalled the modpack on the FTB launcher and it seems to have fixed for me..
