### ISSUE TITLE
My game crashes every time I try to load it

### ISSUE THREAD

**Issue by Flame438** [FTBTeam/FTB-Revelation-2#428]
Modpack: Version: FTB Revelation 3.3.0

Issue: every time i try to launch the modpack at 2/7 once it hits Aroma1997's Dimensional World mod it crashes instantly and I have deleted and reinstalled the modpack and it didn't fix it.

Link to Log or Crash File Paste: Link to the crash report is [here](https://pastebin.com/JkUVRsQf)

Is it Repeatable?: It happens every time I try to run the modpack

Mod/s Affected: I believe its only Aroma1997's Dimensional World version: 1.12.2-2.0.0.2.b89

I was exploring in my world when i came upon a chunk that kept crashing me so I lowered my render distance to 2 chunks and before I could get close enough to load it my game crashed and gave me this error.

**Comment by rune-san** [comment]
Did you edit your aroma1997sdimension_gen.json file? Should be located under config/aroma1997. What's the contents of it? It sounds like it's been modified or malformed so it's no longer a valid JSON file.

As far as reinstalling and reinstalling, did you make sure to delete your instance folder in between deleting and re-downloading so that you're not running the same corrupted file?

**Comment by Flame438** [comment]
I just tried opening the JSON file and there was nothing in it.  I don't know if it was because I used notepad and word but there wasn't anything in the file. As for the reinstalling part, I copied the world to my documents folder and deleted it from the modpack and put it back in after the saves file after I finished reinstalling the modpack.

**Comment by rune-san** [comment]
That's likely the crux of your issue. You should have a fully populated JSON file after your first run. This config should be getting injected when you install the FTB Instance. Below is the contents of that JSON file, though if you're having trouble with that 1 file, I'm definitely concerned there may be other issues elsewhere in the configs:

```json
[
	{
		"type": "_comment",
		"identifier": "Comment#1",
		"01": "You can add or modify entries here. Enabled blocks will be applied only in the Mining World.",
		"02": "Changes will be applied when restarting the game or using the command /dimensionalworld reloadconfig",
		"03": "All blocks need to have a type and a identifier field and can have a enabled field",
		"04": "The identifier can be freely chosen, but needs to be unique",
		"05": "All block specifications have the format modid:blockname:metadata",
		"06": "Look at the examples given below to get more information on how to use this file."
	},
	{
		"type": "oreGen",
		"identifier": "clay_ore",
		"enabled": true,
		"amount": 0.5,
		"size": 20,
		"minHeight": 60,
		"maxHeight": 80,
		"ore": "aroma1997sdimension:miningore:1"
	},
	{
		"type": "oreGen",
		"identifier": "emerald_ore",
		"enabled": true,
		"amount": 6.0,
		"size": 2,
		"minHeight": 4,
		"maxHeight": 28,
		"ore": "minecraft:emerald_ore"
	},
	{
		"type": "oreGen",
		"identifier": "sticky_ore",
		"enabled": false,
		"amount": 2.0,
		"size": 4,
		"minHeight": 30,
		"maxHeight": 80,
		"ore": "aroma1997sdimension:miningore"
	},
	{
		"type": "lakes",
		"identifier": "lava_lake",
		"enabled": false,
		"targetBlock": "minecraft:lava"
	},
	{
		"type": "lakes",
		"identifier": "water_lake",
		"enabled": false,
		"targetBlock": "minecraft:water"
	},
	{
		"type": "oreReplace",
		"identifier": "removeDiamonds",
		"enabled": false,
		"targetBlock": "minecraft:stone",
		"originalBlock": [
			"minecraft:diamond_ore"
		]
	},
	{
		"type": "grass",
		"identifier": "grass",
		"enabled": false
	},
	{
		"type": "oreReplace",
		"identifier": "oreGenDebug",
		"_comment": "If you want this to work properly, this needs to be the last block in the json file.",
		"enabled": false,
		"targetBlock": "minecraft:air",
		"originalBlock": [
			"minecraft:stone",
			"minecraft:stone:1",
			"minecraft:stone:2",
			"minecraft:stone:3",
			"minecraft:stone:4",
			"minecraft:stone:5",
			"minecraft:stone:6",
			"minecraft:dirt",
			"minecraft:grass",
			"minecraft:gravel"
		]
	}
]
```

**Comment by Flame438** [comment]
So, I was able to actually open the modpack but my world got stuck loading at the loading terrain part and I don't know how to fix that other then lowering my render distance

**Comment by 016Nojr** [comment]
Try reinstalling the pack, if the issue is still there, send it to a new bug tracker with logs. New bug tracker can be found in the main menu after the pack update coming in a few days, or in the pinned issue
