### ISSUE TITLE
Binnie's Botany entirely unusable.

### ISSUE THREAD

**Issue by ironedge0** [FTBTeam/FTB-Revelation-2#429]
* **FTB Revelations Version 3.30**

* **When breeding flowers with Binnies Botany, even if only using pure tulips of the same color the resulting combinations will create higher tier flowers of random color combinations. Achieving different colors of flowers with any certainty is impossibly as well as it being impossible to reproduce generic breeds of plants. (even when next to only exact duplicates.) **

* **Repeatable? Yes. I have tested both on a server where i discovered the bug and in a fresh single player void world** 

* **Mod? Binnie's Botany**: 

* **Fix? i have no idea haha sorry**

https://imgur.com/a/bdG2hdH

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
