### ISSUE TITLE
The /dank/null/ ingot into pulverized iron bug :)

### ISSUE THREAD

**Issue by KidKova** [FTBTeam/FTB-Revelation-2#430]
* **Modpack Version**: 3.4.0

* **Issue**: My /dank/null/ randomly started turning certain ingots into a full stack of pulverized iron. I've restarted several times and the issue persists. Also concerning that I've seen posts similar to the issue I'm having and they just get closed with no support. Do I need to reinstall?

![cringe](https://user-images.githubusercontent.com/39764270/101118779-68e02100-35af-11eb-8171-c5dda189f01d.gif)

* **Link to Log or Crash File Paste**: No crash, just an unwanted dupe bug.

* **Is it Repeatable?**: Yep, I can turn lead ingots into pulverized iron

* **Mod/s Affected**: All em.

* **Known Fix**: Lol.

**Comment by DSbrickMC** [comment]
LOL, these things are so broken. 
I have the same issue and others. They also turn ProjectRed Core crystals into circuit plates and Destabilized Cathrate into destroyed item

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
