### ISSUE TITLE
Recurrent ConcurrentModificationException from p455w0rdslib

### ISSUE THREAD

**Issue by machineonamission** [FTBTeam/FTB-Revelation-2#431]
* **Modpack Version**: 
3.3.0
* **Issue**: 
Random repeated crash that often happens when teleporting/dying

* **Link to Log or Crash File Paste**: 
[crash-2020-12-04_10.07.50-client (1).txt](https://github.com/FTBTeam/FTB-Revelation-2/files/5644043/crash-2020-12-04_10.07.50-client.1.txt) (friend's crash report on macos)
[crash-2020-12-04_01.46.04-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/5644057/crash-2020-12-04_01.46.04-client.txt) (my crash report from windows)

* **Is it Repeatable?**: 
Not on command but both me on windows and my friend on macos experience the same crash

* **Mod/s Affected**: 
p455w0rdslib
AE2TLib
WirelessCraftingTerminal
DankNull
* **Known Fix**: 
https://github.com/p455w0rd/p455w0rds-Library/issues/68
simply updating p455w0rd's mods should do the trick.

**Comment by rune-san** [comment]
See #353 which I'm fairly certain is the exact issue you're facing. Disabling the p455w0rdsLib shader stuff should fix your problem. It's disabled by default in later versions of this mod. See p455w0rd/p455w0rds-Library#47 for the mod's issue tracker.

**Comment by machineonamission** [comment]
I was more suggesting to get the mods updated in a later version of FTB Revelation due to this glitch

**Comment by rune-san** [comment]
It is. Version 3.4.0 is out with p455w0rdslib-1.12.2-2.3.161.jar.

**Comment by machineonamission** [comment]
oops
