### ISSUE TITLE
Client crashed when putting on Dark Soularium Jetplate

### ISSUE THREAD

**Issue by LevyWilson** [FTBTeam/FTB-Revelation-2#432]
* **Modpack Version**: 3.3.0

* **Issue**: I just finished crafting a Dark Soularium Jetplate. I put it on my chest and I immediately crashed. Every time I try to log onto the server, I crash.

* **Link to Log or Crash File Paste**: https://pastebin.com/SHGZSntR

* **Is it Repeatable?**: Happens every time I log onto the server.

* **Mod/s Affected**: Simply Jetpacks

* **Known Fix**:

**Comment by LevyWilson** [comment]
This problem might be related to issue #400

**Comment by 016Nojr** [comment]
Pack update coming in a few days which has the new version of Simply Jetpacks included
