### ISSUE TITLE
3.4.0 Server Crashes on Startup

### ISSUE THREAD

**Issue by jackytsz** [FTBTeam/FTB-Revelation-2#433]
* **Modpack Version**: 3.4.0

* **Issue**: I ran the bat file and it kept crashing. Not sure why it happened, I was able run 3.3.0 server before.

* **Link to Log or Crash File Paste**: 
Log: https://paste.feed-the-beast.com/view/b38ec149
Crash File: https://paste.feed-the-beast.com/view/90ca0359

* **Is it Repeatable?**: Yes, it happened every time I start the server

**Comment by rune-san** [comment]
It looks like you don't have a functioning install. Files are missing. I would re-deploy the .EXE and have it re-download the server pack, then try again.

**Comment by jackytsz** [comment]
> It looks like you don't have a functioning install. Files are missing. I would re-deploy the .EXE and have it re-download the server pack, then try again.

Thank you very much, this solution does work! Simply re-deployed the .EXE.
(Strangely enough, I did try to re-deploy multiple time before I post the issue, if people had similar issue, you may wish to re-deploy a few time and/or at a different time.)
