### ISSUE TITLE
SUGGESTION: Plethora mod

### ISSUE THREAD

**Issue by R93950X** [FTBTeam/FTB-Revelation-2#435]
I suggest adding an addon for CC: Tweaked called Plethora by the same developer as CC: Tweaked

It adds:
- Support for almost every tile entity as a peripheral
- A neural interface item, which allows a computer to interact with entities and players who have it equipped
- Scanners for nearby blocks and entities
- And some modules for computers to use such as lasers

**Comment by 016Nojr** [comment]
Added in new pack update coming in a few days
