### ISSUE TITLE
Flux bore randomly turns into polished diorite

### ISSUE THREAD

**Issue by loneztar** [FTBTeam/FTB-Revelation-2#438]
* **Modpack Version**: FTB Revelation 3.4.0

* **Issue**: Flux bore (hardened upgrade + some enchant) located in hotbar slot 1 will randomly turn into a stack of polished diorite. Have not been able to pin this down to a specific action. Has happened several times.

* **Link to Log or Crash File Paste**: No crash log/does not crash client

* **Is it Repeatable?**: Has happened more than once but unable to recreate at will

* **Mod/s Affected**: RFTools?

* **Known Fix**: None

**Comment by 016Nojr** [comment]
The mod isnt supporting 1.12 anymore, so I am unable to fix this bug if it still exists after the pack update that's being released within a few days.
