### ISSUE TITLE
Crashing When opening Inventory

### ISSUE THREAD

**Issue by bames14** [FTBTeam/FTB-Revelation-2#44]
* **Modpack Version**:  2.0.0

* **Issue**:  Whenever I press E to open inventory the game crashes. I did install optifine but then I deleted it and it still crashed.

* **Link to Log or Crash File Paste**:  The game crashed whilst rendering ingredient
The game crashed whilst rendering ingredient
Error: java.lang.NullPointerException: Rendering ingredient

* **Is it Repeatable?**:  YES

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
I am not able to reproduce this and I will need full logs to look into this deeper.  I would try a fresh install without Optifine and see if the problem remains.  That mod really messes up alot of mods that do not support it.
