### ISSUE TITLE
SUGGESTION: Energy converters modpack

### ISSUE THREAD

**Issue by hi8000** [FTBTeam/FTB-Revelation-2#442]
Hello, 
I didn't know where else to put a suggestion for mods so I hope this gets seen. I am a big fan of the mod pack and enjoy playing it. In some other packs however, there was a mod called energy converters. Basically you can change eu to rf or rf to mj and so on. The main thing I use it for is to power quarries and make them much more efficient. If its possible to add I would appreciate it.
Thanks,
Hi8000

**Comment by R93950X** [comment]
Personally, with Buildcraft being in development right now I don't find this to be a good idea, even with just 3 redstone engines a pump can tank server performance when it has no fluid because very time it's powered it checks for fluid..
RF to EU can be done via Flux Networks and vice versa.

**Comment by 016Nojr** [comment]
Will not be added
