### ISSUE TITLE
[mod change/addition]OpenComputers

### ISSUE THREAD

**Issue by FurryJack0420** [FTBTeam/FTB-Revelation-2#443]
I was just wanting the pack to either use opencomputers instead of computercraft or add opencomputers to it. I feel that it adds more content with computers, and that it's harder to make them and work them, but also has a better(imo) api for lua and better user experience. Also I feel the addition of lua 5.2 and 5.3 would be helpful, and the functionality between it and other mods is better with the use of the adapter, which I believe would be great for things like reactor controls, power management, and especially managing the draconic reactor, being there is a script meant for draconic reactors that run on opencomputers computers.

**Comment by Anti27** [comment]
I want this changed as well.

**Comment by BadBoyJH** [comment]
Second this. Or at least something like Plethora to give the option for tile entity interaction.

**Comment by 016Nojr** [comment]
Mod List is locked atm
