### ISSUE TITLE
Continue uploading server zips to curseforge so users that dont want to use your shell installer can grab the zip...

### ISSUE THREAD

**Issue by backlands** [FTBTeam/FTB-Revelation-2#444]
* **Modpack Version**: 3.3+

* **Issue**: It appears that server file packs are no longer being uploaded to Curseforge which has now broken my server management tools so I can no longer update this pack past 3.2 without manual intervention. Which I won't be bothering with and will likely no longer support this modpack or any others from FTB that go the same route.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Entire pack.

* **Known Fix**: Upload server files to curseforge so that users don't have to use your installer script and can continue using existing automated management tools.

**Comment by imle** [comment]
Even if you wanted to manually update. the latest server packs are broken
