### ISSUE TITLE
Playing on a tlauncher server with my friends and keeps getting disconnected whenever I interact with certain mods

### ISSUE THREAD

**Issue by LeonardYap** [FTBTeam/FTB-Revelation-2#445]
- FTB Revelations 3.3.0
- Disconnect whenever I interact with Draconic Evolutions/Ender Storage Mod
- Can't find my crash file
- Always happens
- As of now, draconic evolutions and ender storage

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
