### ISSUE TITLE
Modpack will use all allocated RAM, no matter how much is allocated, causing freezes

### ISSUE THREAD

**Issue by Dixon-L** [FTBTeam/FTB-Revelation-2#446]
* **Version:** FTB Revelation-3.4.0 (I have just used the curseforge install and changed nothing about the pack other than to allocate more RAM than the 4g it defaults to.) 

* **Problem:** Every time I have opened the Modpack it has eventually frozen repeatedly, although it has happened a lot more of the last 2 days I played. The game will open up fine, and I can play for about an hour (when I allocate 10 gigs of RAM), and at the beginning of the session the f3 screen will tell me I'm using between 40-50% of allocated RAM, but by the time the freezes start, it is going to 96%, freezing, and then after about 4 seconds it unfreezes and returns to 75%, before rising back to max. This was happening when I had allocated 6 gigs, and I originally thought that more RAM would fix it since I know its a large pack, but I'm now unsure and would like a second opinion. I played with the task manager open on a second monitor yesterday and found that in addition to (what I believe are) memory related crashes, minecraft will max out the CPU from time to time, leading to another crash, but that happens far less frequently, and am able to deal with it. However, the memory problem is harder to deal with, because the only way I have found to play is to just restart the client about every hour to reset the memory. 

* **Latest Log: ** https://paste.feed-the-beast.com/view/21a77fa3: 

* **Repeatable?:** This problem is definitely repeatable, as it happened twice tonight, and repeatedly last night. It takes about an hour, but it's pretty consistent. 

* **Specific Mod?:** As far as any mods go, a cursory glance at the log suggests to me that it might be a problem with the buildcraft mod in this pack, but I don't know enough about reading the log or the pack itself to know. EDIT: Feels like the same problem as this person had with buildcraft, but on a more recent version of the mod. Although it could be a completely different problem as well. 

* **Known Fix**: Some further exploration revealed that curseforge default installed an outdated version of buildcraft, so now to update that and see if that was the source of the problem. **Later** That slowed it down, but it still used all 10g eventually. Newest log: https://paste.feed-the-beast.com/view/3ada53b9

**Comment by DR4GON-47** [comment]
I have the exact same issue, no idea how to fix it. it only started happening to me after I updated to the overwolf launcher

**Comment by R93950X** [comment]
This is a memory leak issue within the JVM, a mod is using some memory and not indicating that it's done with it and instead of reusing that space it's writing to a new space, the best I can recommend is updating FoamFix.

**Comment by 016Nojr** [comment]
Pack update coming in a few days, hopefully that helps with this issue.
