### ISSUE TITLE
the minetogether mod just stoped working 

### ISSUE THREAD

**Issue by idanmoalem** [FTBTeam/FTB-Revelation-2#448]
i loaded the modpack like 3 days ago and the mod worked fine then i answerd on of the questions that people asked there and the mod just stoped working next day i loaded the modpack again and the mod didnt worked from th begining. now its just never working. does anyone have a fix for this?

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
