### ISSUE TITLE
Gadgetry distiller crash

### ISSUE THREAD

**Issue by Mechanical-Marvel** [FTBTeam/FTB-Revelation-2#45]
* **Modpack Version**: 2.0.0

* **Issue**: If extra utilities 2 pipes are used to transfer biomass from a gadgetry distiller to a gadgetry furnace generator minecraft crashes while loading another dimension/entering a dimension

* **Link to Log or Crash File Paste**: 
First crash:https://paste.feed-the-beast.com/view/87d90e6b
Deliberate Repeat:https://paste.feed-the-beast.com/view/b0875324

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 
Gadgetry Machines 0.2.1
Extra Utilities 2

**Comment by tfox83** [comment]
Was not able to reproduce in 2.2.0
