### ISSUE TITLE
Cant Update server

### ISSUE THREAD

**Issue by SLordB** [FTBTeam/FTB-Revelation-2#450]
* **Modpack Version**: 
3.4.0
* **Issue**: 
The server files are not on curse forge so I cant make a server.

**Comment by KilRol** [comment]
https://feed-the-beast.com/modpack/ftb_revelation

**Comment by rednaz1337** [comment]
Is there no place where one can download a simple zip file? The installer doesn't work on ARM.

**Comment by CrystalMare** [comment]
Download URLs on the link provided by @KilRol provide a downloadable executable. Where is the ZIP ?

**Comment by Quetzi** [comment]
Zips are not provided for technical reasons. The executable installer already linked will download everything you need.

**Comment by CrystalMare** [comment]
Is there any source available of said installer?

**Comment by Quetzi** [comment]
Source is available here: https://github.com/CreeperHost/modpacksch-serverdownloader
