### ISSUE TITLE
Can't install from CurseForge - missing dependencies

### ISSUE THREAD

**Issue by ZizzyZizzy** [FTBTeam/FTB-Revelation-2#451]
![image](https://user-images.githubusercontent.com/5203624/103321432-d50b4480-49f6-11eb-8341-ccc3532e7a97.png)

Fresh install of the CurseForge launcher. Trying to install 3.4.0. No idea what addon has ID 253449.

Is this pack available in any other launchers?

**Comment by 016Nojr** [comment]
https://feed-the-beast.com/
