### ISSUE TITLE
Update CC: Tweaked to fix dupe

### ISSUE THREAD

**Issue by Jorgen1040** [FTBTeam/FTB-Revelation-2#455]
* **Modpack Version**: 3.4.0

* **Issue**: Dupe/destroy bug in CC: Tweaked. The inventory of a turtle is not updated when it moves, thus allowing items to be duped or deleted.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, just wait for the turtle to move before interacting with the inventory and it will not update.

* **Mod/s Affected**: CC: Tweaked 1.84.0

* **Known Fix**: It has been [fixed](https://github.com/SquidDev-CC/CC-Tweaked/commit/418420523ac0474a811a6a6fba0c4bfacbefd65b) in newer versions of CC: Tweaked, (Fixed in version 1.85.0) but it might be worth just to update to the latest version (1.89.2) since they also seem to have major bug fixes.

**Comment by 016Nojr** [comment]
Updated in new pack version coming in a few days
