### ISSUE TITLE
Fatally missing registry entries when connecting to server

### ISSUE THREAD

**Issue by Psychicbear** [FTBTeam/FTB-Revelation-2#456]
* **Modpack Version**: 3.3.0 & 3.4.0

* **Issue**: When attempting to connect to my server, users are first met with the error "Fatally missing registry entries" and disconnected immediately. When attempting to connect again, they are met with a more detailed error that is elaborated in the provided log. In the server console I can see:
  [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
before the user is disconnected with no error within the server console. Interestingly I could connect to the server before midnight of new years, however after it had hit new years and I restarted my game, this error started to occur. Additionally, one specific person is able to connect to the server without errors, whereas everyone else cannot

* **What I've Tried**:  
 - Manually syncing client configs with server config files
 - Changing server and clients between versions of the modpack
 - Hosting server on multiple linux machines, including local and cloud machines
 - Redownloading client files from 3 different modpack launchers (FTB, SourceForge, TLauncher)
 - Redownloading server files and running different instances of the server
 - Copying the FastWorkbench mod from server to client files
 - Attempting to connect to the server using the same files as the one guy who is able to connect
 - Removing crafting table related mods from the pack 
 - Changing the date and time of my server hosting machine due to strange issue noted here: https://forum.feed-the-beast.com/threads/fatally-missing-registry-entries.301327/
 - Hammering my head at the issue for 6 hours straight
 
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/454b54e0

* **Is it Repeatable?**: Occurs for all but one of my friends who try to connect to the server 100% of the time. 

* **Mod/s Affected**: I have found one single occurrence of this specific error message online linking the error to the FastWorkbench mod

* **Known Fix**: Running the server on my local windows machine (same machine I use to play the server) allows me to connect, however strangely if I connect to the linux hosted server first, I am unable to connect to the windows hosted server due to the same error. Not really a fix but a rough workaround for the time being.

**Comment by madpim** [comment]
I have the same problem indeed..

**Comment by potaske** [comment]
Me and my friends all got the same problem too and we made the servers 5 days ago

**Comment by RambonL** [comment]
Same problem here. Happened right after 00:00:01 1.1.2021. Found a thread that I believe is related. Happened around the same time last year (https://forum.feed-the-beast.com/threads/fatally-missing-registry-entries.301327/). So I think this is because of the Entity called Santa from StevesCarts. Couldnt find a fix. I really wanna play again

**Comment by SirJimmethy** [comment]
I am having the exact same issue and created the server less than 48 hours ago

**Comment by tmbreidenbach** [comment]
> Same problem here. Happened right after 00:00:01 1.1.2021. Found a thread that I believe is related. Happened around the same time last year (https://forum.feed-the-beast.com/threads/fatally-missing-registry-entries.301327/). So I think this is because of the Entity called Santa from StevesCarts. Couldnt find a fix. I really wanna play again

We're in the same boat in our server. I remember this happening last year too.. I was actually kicked from the server at midnight this morning and haven't been able to get back in.

**Comment by DamienKatzenberg** [comment]
The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue

**Comment by RambonL** [comment]
> 
> 
> The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue

hmm that fixed it. Nice

**Comment by tmbreidenbach** [comment]
> > The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue
> 
> hmm that fixed it. Nice

This might be a silly question, but do either of you used CurseForge? If so, did you delete your profiles and redownload the entire mod pack?

**Comment by RambonL** [comment]
> 
> 
> > > The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue
> > 
> > 
> > hmm that fixed it. Nice
> 
> This might be a silly question, but do either of you used CurseForge? If so, did you delete your profiles and redownload the entire mod pack?

I use the FTB App over Overwolf. After deleting the Modpack and reinstalling it everything worked finde. Didnt even do anything server-side except removing Santa Enitity at Server Start

**Comment by tmbreidenbach** [comment]
> > > > The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue
> > > 
> > > 
> > > hmm that fixed it. Nice
> > 
> > 
> > This might be a silly question, but do either of you used CurseForge? If so, did you delete your profiles and redownload the entire mod pack?
> 
> I use the FTB App over Overwolf. After deleting the Modpack and reinstalling it everything worked finde. Didnt even do anything server-side except removing Santa Enitity at Server Start

OK - I'm going to try and launch through FTB app rather than CurseForge.

**Comment by tmbreidenbach** [comment]
> > > > > The same thing happened to me. I reinstalled my client-side pack and it seemed to fix the issue
> > > > 
> > > > 
> > > > hmm that fixed it. Nice
> > > 
> > > 
> > > This might be a silly question, but do either of you used CurseForge? If so, did you delete your profiles and redownload the entire mod pack?
> > 
> > 
> > I use the FTB App over Overwolf. After deleting the Modpack and reinstalling it everything worked finde. Didnt even do anything server-side except removing Santa Enitity at Server Start
> 
> OK - I'm going to try and launch through FTB app rather than CurseForge.

Launched through the FTB App perfectly. Thanks!

**Comment by krakah** [comment]
I renamed the config folder in my local instance and could connect to my server after this.
