### ISSUE TITLE
Magma Slime Cores Tinkers construct 

### ISSUE THREAD

**Issue by CaveAkuma** [FTBTeam/FTB-Revelation-2#457]
* **Modpack Version**: 1.12.2 (Latest)

* **Issue**: When trying to melt Magma slime Crystals to make a Magma Slime Core through the smelter it will not smelt. I’m not sure if I’m doing something wrong or it’s broken. Thanks for any help

**Comment by 016Nojr** [comment]
Magma Slime Core doesnt exist?
