### ISSUE TITLE
Recipe for Mossy Stone Brick Stairs produces non-mossy stone brick stairs.

### ISSUE THREAD

**Issue by krakah** [FTBTeam/FTB-Revelation-2#458]
* **3.4**: 

* **Recipe for Mossy Stone Brick Stairs produces non-mossy stone brick stairs.  JEI shows quark mossy stone brick stair has having the typical stair recipe shape using vanilla mossy stone bricks.  However the recipe in game produces non-mossy stairs**: 

* **N/A**: 

* **Yes, every time.**: 

* **Quark**: 

* **I've tried some craftweak changes, but honestly I'm not very good.  I was able to get it to a point that the aforementioned recipe produces the 8 nonmossy stairs.  Upon moving the non-mossy stairs out of the crafting grid its replaced with 64 diamonds.  Removing the 64 diamonds does give the 8 mossy stairs.  But this is doubling the resource output.  The recipie in its current config in my craftweaker script does produce a "ERROR: Could not resolve <minecraft:mossy_stone_bricks>" in chat when logging in.  I'm likely using the wrong block ID's**:

**Comment by 016Nojr** [comment]
There is a big mess caused by Quark I guess, so I added a new recipe for mossy stone brick stairs, 3 bricks gives 4 stairs, instead of 6 bricks to 8 stairs.
