### ISSUE TITLE
Enderio conduit sort of dupe

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Revelation-2#46]
* **Modpack Version**: 2.1.0

* **Issue**: Replace a conduit with a new 1 will not take the upgraded out of your inv

* **Is it Repeatable?**: Yes https://youtu.be/rXyVSZq04Mg

* **Mod/s Affected**: EnderIO

* **Known Fix**: No fix atm..

**Comment by tfox83** [comment]
Seems to be fixed in 2.2.0
