### ISSUE TITLE
LAN disconnects other players in certain situations - Ender Chest, most draconic evolution GUI's

### ISSUE THREAD

**Issue by alex732135** [FTBTeam/FTB-Revelation-2#460]
My brother and I have only recently gotten into modded minecraft, and ftb revelation was our first experience. We play over LAN, where I have the world on my computer that I open to LAN for him to join. When we made a quarry and added an Ender Chest to it (I think from the Ender Storage mod), whenever either of us would open the chest he would always get instantly disconnected, but would be able to rejoin afterwards. A little later, I built an energy core from draconic evolution, and if either of us interacted with it he would also get disconnected. Fusion crafting and the energy infuser from draconic also had the same interaction. We were doing everything in the mining dimension (Aroma 1997's Dimensional World) for additional information.

* **Modpack Version**: 1.12.2

* **Issue**: On LAN, when opening certain things would always disconnect the other player.

* **Link to Log or Crash File Paste**: I'm not sure if it creates a crash file, as it isn't crashing the game and just disconnecting. If someone can let me know where to check if its creating crash logs that would be appreciated.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: As far as we've seen, Ender Storage and Draconic Evolution,

* **Known Fix**: We found that if he was in a different dimension we could get the draconic evolution stuff to not disconnect him, but it kinda sucks that he can't interact with anything from draconic evolution and it has to lock off a dimension for him.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
