### ISSUE TITLE
Pack update - Flux Networks wireless charging not working - fixed in updated flux networks version 

### ISSUE THREAD

**Issue by froob956** [FTBTeam/FTB-Revelation-2#461]
* **Modpack Version**: 3.4.0 
* **Issue**: Flux Networks wireless charging not working, fixed in updated version of flux networks. Please update pack to include updated version of flux networks
* **Link to Log or Crash File Paste**:  n/a 
* **Is it Repeatable?**: Yes, use flux networks. Attempt wireless charging. It is not useable/is bugged. 
* **Mod/s Affected**: Flux networks 1.12.2- 3.0.19-21

* **Known Fix**: issue resolved in later version of flux networks known working version is - 4.0.8 may have been resolved earlier than that. 

Thank you for your time :).

**Comment by Shadowner83** [comment]
Updating the pack solves a lot of bugs and stuff. Also the recipe for creating Flux is solved in an update.

**Comment by froob956** [comment]
Any idea if this is even a possibility of it happening anytime in the near future?

**Comment by 016Nojr** [comment]
Pack update coming in a few days, Flux Networks is updated.
