### ISSUE TITLE
Game crash while crafting Reinforced Large Drum

### ISSUE THREAD

**Issue by dawnFirefly** [FTBTeam/FTB-Revelation-2#462]
* **Modpack Version**: 3.4.0
* **Issue**: Game crash while crafting Reinforced Large Drum(Extra Utilities 2) using Crafting Station (tinker construct) connect to Medium Storage Crate (Actually Additions) 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/579a1035
* **Is it Repeatable?**: No (I am playing on server, and it happen randomly while crafting)

* **Mod/s Affected**: JEI, Tinker Construct, Extra Utilities 2

* **Known Fix**:

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
