### ISSUE TITLE
Dark Steel "Apiarist" Upgrades have no effect

### ISSUE THREAD

**Issue by mkitza** [FTBTeam/FTB-Revelation-2#463]
* **Modpack Version**: 3.4.0

* **Issue**: Wearing full Dark Steel or End Steel Armor, with activated Apiarist Upgrades socketed, does not protect from bee damage or harmful effects.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: To be determined

* **Known Fix**: Remove most mods.

I tested the issue in a stripped down version of the pack:
* First using only EnderIO and Forestry. In this case the issue is solved.
  * EnderIO-1.12.2-5.1.51.jar
  * EnderStorage-1.12.2-2.4.6.137-universal.jar
  * forestry_1.12.2-5.8.2.394.jar
* Secondly adding to my knowledge all bee related mods. In this case the issue is sill solved.
  * bdlib-1.14.3.12-mc1.12.2.jar
  * binnie-mods-1.12.2-2.5.1.188.jar
  * careerbees-0.4.0.jar
  * CodeChickenLib-1.12.2-3.2.3.357-universal.jar
  * EnderCore-1.12.2-0.5.68.jar
  * EnderIO-1.12.2-5.1.51.jar
  * EnderStorage-1.12.2-2.4.6.137-universal.jar
  * forestry_1.12.2-5.8.2.394.jar
  * gendustry-1.6.5.8-mc1.12.2.jar
  * jei_1.12.2-4.15.0.268.jar
  * jeibees-0.9.0.5-mc1.12.2.jar
  * jeiintegration_1.12.2-1.5.1.36.jar
  * MagicBees-1.12.2-3.1.10.jar

Does anybody have a idea which mods could also interact with this bug?

**Comment by CitiesXL2815** [comment]
it's known Bug in EnderIO we already know about it https://github.com/SleepyTrousers/EnderIO/issues/5505

**Comment by 016Nojr** [comment]
Closing this since we're waiting on a fix in the issue mentioned above. We cant do anything with this.
