### ISSUE TITLE
Woot Ender Dragon Farm not dropping dragon scales.

### ISSUE THREAD

**Issue by OrionPaxeus** [FTBTeam/FTB-Revelation-2#464]
* **Modpack Version**: 3.4.0

* **Issue**: The tier four woot farm, when being used to farm the Ender Dragon, does not drop dragon scales.(from quark) I have run a few dozen cycles with it, and it has not output any dragon scales. The dragon scale does not show up as a possible drop in the UI either. 

I see no reason it should not drop, as the dragon scale has a 100% drop rate.

Im assuming this is a bug with the loot registry woot uses not being updated to drop the dragon scales.

* **Link to Log or Crash File Paste**: no crash involved

* **Is it Repeatable?**: yes, several dozen cycles, and still no dragon scales from the woot farm.

* **Mod/s Affected**: Woot, Draconic Evolution, Quark

* **Known Fix**: update loot drops for ender dragon in Loot.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore.

Loot tables are generated on world gen, so it's nothing I can affect (as far as I know)
