### ISSUE TITLE
FTB Revelations crash

### ISSUE THREAD

**Issue by LazyWeebOfNetflix2570** [FTBTeam/FTB-Revelation-2#466]
* **3.4.0**: 

* ** Whenever loading FTB Revelations from the FTB windows app,it comes up with this crash file**: 

* ** https://paste.feed-the-beast.com/view/e38d4ff7**: 

* **Yes**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by rune-san** [comment]
This kind of reads like a corrupted installation. Have you tried deleting the profile (and deleting all the files from that Minecraft Instance), and try downloading / deploying again? Your RAM assignment to the instance is also a bit light. It should be closer to 4GB (4096MB) vs. the 3641MB currently assigned.

**Comment by 016Nojr** [comment]
Try reinstalling the pack. As rune-san said, this is probably an install that failed
