### ISSUE TITLE
YABBA/Not Enough Wands Barrel Duplication

### ISSUE THREAD

**Issue by oliverbaumbach** [FTBTeam/FTB-Revelation-2#468]
* **Modpack Version**:  v3.2.0

* **Issue**: Attempting to pick up a YABBA Barrel with the moving wand from Not Enough Wands both picks up the Barrel with its contents, as well as dropping an empty Barrel item. I guess it is a method for turning XP into Barrels, but it seems unintentional. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Works reliably each time the Barrel is picked up. 

* **Mod/s Affected**: YABBA 1.1.2.53, Not Enough Wands 1.12-1.8.1

* **Known Fix**:

**Comment by 016Nojr** [comment]
Tile entities is blocked in Not Enough Wands from the next pack update
