### ISSUE TITLE
Transfer Node to Frame Chest Crash

### ISSUE THREAD

**Issue by oliverbaumbach** [FTBTeam/FTB-Revelation-2#469]
* **Modpack Version**: Revalation 3.2.0 

* **Issue**: Using an Extra Utilities Transfer Node to pipe items into a Bibliocraft Framed Chest causes crash, world becomes unrecoverable. Thermal Expansion Itemducts insert correctly, EnderIO item conduits do not connect, so the Issue seems to be between Extra Utilities and Bibliocraft. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5d96301f

* **Is it Repeatable?**: Yes, consistently, with 2 different survival worlds of mine, and a creative test world I just created. 

* **Mod/s Affected**: Extra Utilities, Bibliocraft

* **Known Fix**:

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
