### ISSUE TITLE
Mod Suggestion - Solar Flux Reborn

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Revelation-2#47]
Would love to see this mod, compact solars would be nice.
Now you need to make big things to get good amount of RF.
https://minecraft.curseforge.com/projects/solar-flux-reborn

**Comment by tfox83** [comment]
At this time we are not using this mod, thank you for the suggestion.  There is really power solar powers available via Env Tech.

**Comment by djoey123** [comment]
Sadly, that solars are taking a huge space for getting power.
