### ISSUE TITLE
3.4.0 low TPS and Loottable "tried to over-fill a container"

### ISSUE THREAD

**Issue by Sockyx** [FTBTeam/FTB-Revelation-2#470]
Wanted to host a FTB Revelation Server (Version 3.4.0) for around 10 People. Still in the test-phase (just me online), the server has a super low TPS-rate and is constantly skipping ticks. 
The only things that that helped to reduce the LAG was setting the view-distance from 10 to 9
But because I want the players to have good experience I want to get it up to 15. Possible? 

Also the console is getting spammed with the Warning                                
"[minecraft/LootTable] : tried to over-fill a container"
can this Message be ignored?

[latest.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/5836121/latest.txt)

Server Specs:
Windows Server 2019
24 GB RAM
Intel Xeon CPU E5-2650 v2 @ 2,6 Ghz
60GB SSD
Java 8
hosted at: ZAP-HOSTING

Java Arguments for the start.bat (also tried the standard Arguments)
-Xms12G -Xmx16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -jar forge-1.12.2-14.23.5.2846-universal.jar nogui

**Comment by rune-san** [comment]
While those loot tables can be annoying (they cause a bunch of item generation that has to despawn), you should generally be able to handle them fine on the server without them crushing it. You show a lot of general skip ticks that are usually a sign of world generation slowing things down. Minecraft is still largely single threaded, and a 2.6Ghz Ivy Bridge generation CPU is not that fast anymore (I have a E5-2650 v1 and see the struggle with this).

Keep an eye on your CPU usage while you're moving around, and make sure you're looking at it from an individual core level. If you see one core constantly hitting 100% when the "skipping" starts, that's pretty much your tell that the server is choking on chunk generation. Also, I would go back to the regular FTB arguments. Perhaps come down to 8GB of RAM minimum and maximum and test to see if you actually need more than that. The more RAM you have, the more the garbage cleanup process will choke your game. You have a GC Pause timeout of 200ms, but all that means is that it will keep trying if you get so much RAM that it can't properly run GC across the full RAM footprint within the time threshold.

**Comment by 016Nojr** [comment]
Read what rune-san said in his comment, use the default arguments provided by FTB, and follow the recommendations for the server setup, if it still lags, try profile the server, and send in the report.

I am closing this issue since we've got a new place to handle issues. A pack update coming in a few days will have the new issue tracker available from the main menu.
