### ISSUE TITLE
Game crash/lost world

### ISSUE THREAD

**Issue by Kayragda** [FTBTeam/FTB-Revelation-2#471]
I have been play Revelation 2 for a few weeks now, and had a lot of progress. When i booted it up today, it had to be reinstalled, and world was no where to be found. This has happened to me on other FTB modpacks too, and im getting a little frustrated with getting ready for AE and full blown automation, just to have the whole thing crash and disappear. Is there anything I can do? I have been assigning lots of RAM and doing everything I can to get this to not do this.

**Comment by 016Nojr** [comment]
There is nothing in the modpack that can cause a world to diseappear.
