### ISSUE TITLE
Fluid cells are glitched.

### ISSUE THREAD

**Issue by tapeman99** [FTBTeam/FTB-Revelation-2#472]
* **Modpack Version**: 3.4.0

* **Issue**: fluid cells are bugging, its almost impossible to pick up lava unless its a corner block that is one block deep. 

* **Link to Log or Crash File Paste**: I don't have one

* **Is it Repeatable?**: yes every time I try to pick up lava with a universal fluid cell

* **Mod/s Affected**: Industrialcraft 2 (idk which version but it's the one downloaded with 3.4.0)

* **Known Fix**: <!-- optional; none :(

Also another question, I understand if you don't know the answer. But I can't put biofuel into combustion engines. Is Industrial foregoing not compatible with the buildcraft engines?

Thanks in advance!

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
