### ISSUE TITLE
Construct's Armory not loading in FTB Revelations.

### ISSUE THREAD

**Issue by MrRamenn** [FTBTeam/FTB-Revelation-2#475]
* **FTB Revelation 3.4.0**: 

* **Issue**: Construct's Armory is not loading in. Game still starts fine. Is completely playable. We cant find any of the armory in the jei and it looks like theres an empty book spot in akasik tome (the one with all the books). Did try to download another copy of the server files but that one crashed right away.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/2b6d01da
* **Is it Repeatable?**: happens every start.

* **Mod/s Affected**: Construct's Armory

* **Known Fix**:

**Comment by 016Nojr** [comment]
Loading for me in a pack update being released in a few days
