### ISSUE TITLE
cant join my account 

### ISSUE THREAD

**Issue by ASDST** [FTBTeam/FTB-Revelation-2#476]
Hi, i had a problem with my account,the problem is that I was playing ftb revelation in a server, after that i changed my mojang account name and tried to join the server, I joined the server and suddenly they made me join as new player without all my stuff, so what should i do to get all my stuff back.

**Comment by rune-san** [comment]
Your Mojang account represents your Character. If you want all your stuff, sign in with your other Mojang Account.

**Comment by 016Nojr** [comment]
This is not an issue related to the modpack, this is most likely on the server side.
