### ISSUE TITLE
Infinite Loading Guides

### ISSUE THREAD

**Issue by Hamsterrhino** [FTBTeam/FTB-Revelation-2#477]
* **Modpack Version**: FTB Revelation 3.4.0

* **Issue**: After starting a world, i try to open guides. Problem is it infinitely loads, and to be exact "sidebar buttons"

* **Link to Log or Crash File Paste**: Not a crash

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Mod that loads guides

* **Known Fix**: No clue
![image](https://user-images.githubusercontent.com/25804014/108598524-18eb4c00-739f-11eb-89b6-43e31898086e.png)

**Comment by 016Nojr** [comment]
FTB Guides has been removed as it wasnt needed in Revelation.
