### ISSUE TITLE
Energy bee not working 

### ISSUE THREAD

**Issue by Bladerkeks** [FTBTeam/FTB-Revelation-2#478]
* **Modpack Version**: 3.4.0

* **Issue**: Energy bee do not produce any engery. 

* **Link to Log or Crash File Paste**: Not nesseceray 

* **Is it Repeatable?**: Yes Single and Multiplayer

* **Mod/s Affected**: careerbees and foresty 

* **Known Fix**:

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
