### ISSUE TITLE
Cursed Earth not spawning mobs 

### ISSUE THREAD

**Issue by Josh19922008** [FTBTeam/FTB-Revelation-2#479]
* **Modpack Version**: 3.4.0

* **Issue**: Cursed earth not spawning mobs in server i have tried all known fixes and nothing seams to work any help would be appreciated 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra utilities 2

* **Known Fix**:

**Comment by 016Nojr** [comment]
Please provide logs, and check if your server is on peaceful mode, the place cant be lit either, that stops mob spawning.

Any replies can be sent to the new bug tracker: https://www.feed-the-beast.com/support
