### ISSUE TITLE
Embers Tyrfing Alchemy Recipe is Broken

### ISSUE THREAD

**Issue by cmmgaming** [FTBTeam/FTB-Revelation-2#48]
* **Modpack Version**: 2.1.0

* **Issue**: Embers alchemy not working to make the Tyrfing sword due to embers alchemy is expecting it's own leadstone sword

* **Is it Repeatable?**: Absolutely

* **Mod/s Affected**: Embers and Thermal Foundation conflict

* **Known Fix**:   None I could see unless you make setting mats on an alchemy table use embers tags or keep embers generation and embers ore gen?

**Comment by tfox83** [comment]
This will need to be fixed on embers end

**Comment by cmmgaming** [comment]
Since you added soot in 2.3 that will resolve this issue.  I'll test it when 2.3 is a stable release.

**Comment by tfox83** [comment]
Closing for now as Soot has sorted.  Thanks
