### ISSUE TITLE
Server download outdated

### ISSUE THREAD

**Issue by Technoguyfication** [FTBTeam/FTB-Revelation-2#480]
* **Modpack Version**: 
3.4.0

* **Issue**: 
There are no server packs available for download on CurseForge for FTB Rev 3.4.0, the latest server download available is for 3.2.0

Where can I find updated server downloads?

**Comment by Sunekaer** [comment]
The server installer is available on our website.
https://www.feed-the-beast.com/modpack/ftb_revelation
Has been available since the version was released.
