### ISSUE TITLE
Blood Magic No Reaction Chamber

### ISSUE THREAD

**Issue by EmsSquad** [FTBTeam/FTB-Revelation-2#484]
* **Modpack Version**: 3.4.0

* **Issue**: There is no Reaction Chamber for blood magic making it not be able to go to higher stages of the mod pack.

* **Is it Repeatable?**: Yes, It dose not exist.

* **Mod/s Affected**: Blood Magic 1.12.2-2.4.1-103

**Comment by 016Nojr** [comment]
The Reaction Chamber isnt a feature in 1.12. It's not needed for higher stages
