### ISSUE TITLE
Search did not work anymore after change of language (and back)

### ISSUE THREAD

**Issue by Splushy0301** [FTBTeam/FTB-Revelation-2#485]
* **Modpack Version**: 3.4.0 

* **Issue**: After I changed the language to German I haven't found some things in the JustEnoughItems menu. I changed it back to English but the problem was still there. I tried it with some machines or "uranium". On my Laptop everything works fine (I did not change the language)

* **Mod/s Affected**: "JustEnoughItems"

**Comment by 016Nojr** [comment]
Can you list some of the things you can find again? This issue tracker will be closed, so I would appreciate if you could send in a report here instead: https://www.feed-the-beast.com/support
