### ISSUE TITLE
Mod Suggestion that will Fix Embers Bugs with the Mixer

### ISSUE THREAD

**Issue by cmmgaming** [FTBTeam/FTB-Revelation-2#49]
* **Modpack Version**: 2.1.0

* **Issue**: Mixer is buggy and has loss on the pipes author is working on a fix

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Embers

* **Known Fix**:  Soot Mod sorta fixes all the embers bugs with the Mixer so it unofficially is sorta the bug patch for Embers.

**Comment by tfox83** [comment]
I would rather wait for the official fix from the dev.  Thanks for the suggestions
