### ISSUE TITLE
Simple void world config changes

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-Revelation-2#50]
There are some configs in simple void world I suggest changing:

1. `B:CreatureSpawn=false` to `true` (Allows mobs to spawn in the dimension)
2. `B:"Its High Noon"=false` to `true` (Enables eternal day in the dimension, I think having one eternal day dimension is nice so you dont have loads of celestial manipulators causing overworld to always be daytime)

**Comment by tfox83** [comment]
1. I will change in next update
2. Its set to false to discourage mass solar farms/bee farms.  I set it the same in the mining DIM for this reason also

**Comment by 016Nojr** [comment]
Fair enough

**Comment by tfox83** [comment]
in next update
