### ISSUE TITLE
Thaumcraft Stabalizer causes a server crash on use

### ISSUE THREAD

**Issue by hobnob11** [FTBTeam/FTB-Revelation-2#51]
* **Modpack Version**: 2.1.0

* **Issue**: Thaumcraft Stabalizer causes a crash on use, this is a confirmed issue in the beta version 16 of thaumcraft. https://github.com/Azanor/thaumcraft-beta/issues/969

* **Link to Log or Crash File Paste**: dont have, but there is one in that thaumcraft issue. 

* **Is it Repeatable?**: 100% of the time, as soon as someone loads the area with the stabalizer it crashes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Please update thaumcraft to B17 as soon as possible, only solution currently is to ban the item and rollback the server.

**Comment by tfox83** [comment]
B17 will be in next update due out as beta then end of this week.
