### ISSUE TITLE
Re-open Fix for many Embers bugs that exist including alchemy recipes that use more than 64 of any given piles of ash between recipes....until new version of Embers is out that should fix most of the bugs

### ISSUE THREAD

**Issue by cmmgaming** [FTBTeam/FTB-Revelation-2#53]
* **Modpack Version**: 2.1.0

* **Issue**: Mixer is buggy and has loss on the pipes author is working on a fix

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Embers

* **Known Fix**:  Soot Mod sorta fixes all the embers bugs with the Mixer so it unofficially is sorta the bug patch for Embers.

Fix will be coming with new update of embers until then mod dev has suggested people install Soot.

If you use more than 64 of any aspectus for alchemy recipes if the number happens to be the same it can just not work this impacts the Tyrfing issue as well.

**Comment by tfox83** [comment]
Added in 2.3.0
