### ISSUE TITLE
Refined Storage causes major lag when crafting 1000+ items

### ISSUE THREAD

**Issue by anthonysan95** [FTBTeam/FTB-Revelation-2#54]
* **Modpack Version**: 2.1.0

* **Issue**: With the addition of refined storage, my server is having major lag problems whenever someone makes a crafting request of 1000+ items. raoulvdberge/refinedstorage#838

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: RefinedStorage-1.5.34

* **Known Fix**: With 1.6, large crafting requests will not be executed. No idea of the release date.

**Comment by tfox83** [comment]
Fixed in mod update, will get in as soon as it is released and revelations updates next
