### ISSUE TITLE
IC2 Coolant cell recipe eats Thermal Expansion Tank and all remaining fluid in tank

### ISSUE THREAD

**Issue by random51** [FTBTeam/FTB-Revelation-2#58]
* **Modpack Version**: 2.2.0

* **Issue**: When using TE tank in crafting recipe for coolant cell---instead of a single cell or bucket---it consumes everything in the tank and the tank itself, instead of just one bucket/cell of fluid. Same behavior regardless of crafting bench used(tried vanilla and rs crafting grid).

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: IC2/Thermal Expansion

* **Known Fix**: Don't use TE tanks in IC2 recipes.

**Comment by tfox83** [comment]
Its a known issues and the response was to use buckets, that the tank isn't intended to be used in such crafting recipes.
