### ISSUE TITLE
Gadgetry Machines Sprinklers will not break

### ISSUE THREAD

**Issue by memyselfandcj** [FTBTeam/FTB-Revelation-2#59]
* **Modpack Version**: 2.0.0

* **Issue**: Placed Down Gadgetry Sprinkler when I look at them it says waiting on server. When I try to break it just reappears. If I use a drill or other 3 by 3 mining means new ones will appear if I try to place a block down next to original. Doesn't crash server. Will try to include what pictures I can. Have reset server and still same.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: I have tried to repeat in a single player world works just fine. Made another on server and went out a few chunks and still had same issue.

* **Mod/s Affected**: Gadgetry Machines0.2.1

* **Known Fix**: 

![2018-07-08_20 10 53](https://user-images.githubusercontent.com/40968814/42425643-157d6de0-82ee-11e8-971d-3f8b0cb951e1.png)

![2018-07-08_20 11 03](https://user-images.githubusercontent.com/40968814/42425650-20b9c6cc-82ee-11e8-954e-45255bf8198e.png)

![2018-07-08_20 33 26](https://user-images.githubusercontent.com/40968814/42425655-2b4aba9c-82ee-11e8-8436-4c5fd66caf44.png)
![2018-07-08_20 34 13](https://user-images.githubusercontent.com/40968814/42425667-4e470afa-82ee-11e8-8e61-db7cf756f76d.png)

![2018-07-08_20 34 14](https://user-images.githubusercontent.com/40968814/42425669-52e34f2e-82ee-11e8-8444-d7a2e5f3e8dc.png)

![2018-07-08_20 34 17](https://user-images.githubusercontent.com/40968814/42425671-57f320f2-82ee-11e8-9e5b-5832f503be9d.png)

**Comment by dirtbys** [comment]
we had this issue but it crashed our server

**Comment by Articdive** [comment]
same issue except with the Drill from Gadgetry

**Comment by memyselfandcj** [comment]
I have updated the pack to the newest beta version and still has the same issue.

**Comment by Mordaii** [comment]
I've had this issue on my servers as well.  

To fix it: I made the server offline, then rebooted the server without the modpack and replaced the blocks to stone(or something else).  Then shut down the server, add the mod back in, make it public again.

**Comment by tfox83** [comment]
Can break them fine in 2.3.0 beta which will be out later today

**Comment by TangoCheetahs** [comment]
#73 #66 

This issue has been reported to EpicSquid on his Discord Server.
