### ISSUE TITLE
Mod suggestion: Mob Grinding Utils

### ISSUE THREAD

**Issue by TNTUP** [FTBTeam/FTB-Revelation-2#60]
I'm aware when FTB Rev 2.0 was out, that mod got removed in favor of OpenBlocks^^ I've noticed that I couldn't apply/set enchants on OB's spikes^^ I haven't tried its Hopper Vaccum, should do the same way as MGU's hopper. 

What I've liked in FTB Rev 1.0, was this mod, made awesome mob farming with no losses (all items was going into my ME system) and caused nearly no lag at my base. **I do expect this being declined :(**, just in case if you plan adding it back, that would make me go back to this modpack, had ideas for that purpose, but with openblocks you can't apply enchants :(

I've heard that Woot mod got recently added, sadly I haven't played with it, I'd maybe give a try^^

What I like with this mod, you can add upgrades to 10 that gave me a lot of XP and loots for crafting stuffs. 

Let me know if this gets declined or added.

**Comment by tfox83** [comment]
Woot is a great alt to Mob farms as it produces the drops without spawning mobs.  Also you can enchant ExU spikes.  Due to the large amount of content overlap MGU was removed.

**Comment by TNTUP** [comment]
Last time I tried to enchant ExU like you said, I place them and they don't keep enchants if broken but can't say if they still have the enchants while placed down. I'll give a try to Woot, thanks for your time Tfox!
