### ISSUE TITLE
RFTools Power Relay caused a crash

### ISSUE THREAD

**Issue by zefee** [FTBTeam/FTB-Revelation-2#62]
* **Modpack Version**: 2.0

* **Issue**: I placed an RFTools Power Relay on top of an industrial apiary with max rf/t energy bees in it, at which point anyone who looks at the block will crash (Initially this caused a server crash, and if I attempt to reconnect to it, it will crash the server).
Steps taken:
1. Place Power Relay on top of Apiary
2. Break Relay
3. Place Resonant fluxduct on top of Apiary
4. Break fluxduct
5. Replace Power Relay on top of Apiary
At this point it caused a crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3fafb380#L30

* **Is it Repeatable?**: Not sure at the moment, currently trying to get back into the server

* **Mod/s Affected**: RFTools/Gendustry/Career Bees

* **Known Fix**: MCEdit and delete the block the only thing we can currently do

**Comment by tfox83** [comment]
This crash has been reported before to the devs, however I am not able to produce a crash running latest beta of the pack.
