### ISSUE TITLE
Extra Utils 2's Building wand not working with redstone or lapis ore.

### ISSUE THREAD

**Issue by Articdive** [FTBTeam/FTB-Revelation-2#63]
* **2.1.0**: 

* **Extra Utils 2's Building wand not working with redstone or lapis ore.**: Attempting to use the builder's wand from Extra Utils 2 on redstone ore or lapis results in seeing the placement box but then the blocks not being placed.

* **Is it Repeatable?**: Try using the Extra Utils 2 building wand on redstone ore or lapis lazuli ore, it works for diamond emerald e.t.c just not redstone or lapis.

* **Mod/s Affected**: Extra Utils 2.

* **Known Fix**: None

**Comment by tfox83** [comment]
ExU builders wand is disabled, the wands form Better Builders Wands works fine in my testing

![image](https://user-images.githubusercontent.com/4246308/42834015-a62bda44-89aa-11e8-929a-2035f4e3a05a.png)
