### ISSUE TITLE
Client crashes while searching JEI

### ISSUE THREAD

**Issue by wpattison** [FTBTeam/FTB-Revelation-2#65]
* **Modpack Version**: Server: FTBRevelationServer_2.1.0 - Client: forge-14.23.4.2730

* **Issue**: The game crashed whilst rendering item
Error: java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap

* **Link to Log or Crash File Paste**: https://pastebin.com/eApD9ae0

* **Is it Repeatable?**: Seems to be happening more often now.

* **Mod/s Affected**: JEI?

* **Known Fix**: N/A

![client_settings](https://user-images.githubusercontent.com/2924110/42670497-d623fde0-8620-11e8-846b-83b38408cb55.JPG)

**Comment by tfox83** [comment]
I cannot repeat this, what item are you searching for?

**Comment by wpattison** [comment]
Anything - it got to the point of opening to search and typing a key and it crashed.

I saved off the world and started a new one - only about 4hrs in and so far so good.

**Comment by tfox83** [comment]
I am closing this for now as I still have not had this issue nor any other reports, feel free to reopen if you experience this with your new world, thanks for posting.
