### ISSUE TITLE
Gadgetry mod crashes server

### ISSUE THREAD

**Issue by ripzeus** [FTBTeam/FTB-Revelation-2#66]
Playing around with the beta (FTBRevelation-2.2.0-1.12.2.zip +1 Server Pack | 15.58 MB | Jul 5, 2018 | 1.12.2) and came across the Gadgetry mod crashing the server.

Server will crash when any Gadgetry item is placed. World Edit s the only other mod added.

* **Modpack Version**: Beta Modpack

* **Issue**: Gadgetry cashing

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ac4cb1f7

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Gadgetry, lastest version

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/42833809-1894e450-89aa-11e8-96b9-21baf13d0c62.png)

**Comment by tfox83** [comment]
Cannot repeat on 2.3.0

**Comment by ripzeus** [comment]
Was about to repeat on 2.3
https://github.com/FTBTeam/FTB-Revelation-2/issues/73

**Comment by TangoCheetahs** [comment]
Repeated on 2.3.0. See #73
