### ISSUE TITLE
FTB Revelations Items Disappear from view in Iron Chest mod Chests

### ISSUE THREAD

**Issue by peskymrpickles** [FTBTeam/FTB-Revelation-2#67]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by 016Nojr** [comment]
Please provide more information

**Comment by tfox83** [comment]
Closed due to missing info.
