### ISSUE TITLE
Client is Outdated

### ISSUE THREAD

**Issue by lachlanmcnicol** [FTBTeam/FTB-Revelation-2#70]
* **Modpack Version**: 2.1.0

* **Issue**: Client is outdated despite having the same version as the server. I navigated to the CurseForge website and downloaded the server files for version 2.1.0 which matches the version in the Twitch app.

* **Link to Log or Crash File Paste**: No log file to speak of

* **Is it Repeatable?**: Yeah it's pretty repeatable just do it yourself.

* **Mod/s Affected**: ...all of them?

* **Known Fix**:

**Comment by tfox83** [comment]
I suggest a full reinstall of the client and server.
