### ISSUE TITLE
Mod Suggestion - Solar Flux Reborn

### ISSUE THREAD

**Issue by raziel23x** [FTBTeam/FTB-Revelation-2#77]
https://minecraft.curseforge.com/projects/solar-flux-reborn

would be nice to have this added to the modpack for a good power source

**Comment by djoey123** [comment]
I already did a suggestion for the mod, it was not accepted sadly. https://github.com/FTBTeam/FTB-Revelation-2/issues/47

**Comment by tfox83** [comment]
Sorry, the core mod that comes with it breaks alot of things in our early testing.
