### ISSUE TITLE
McMyAdmin compatibility problem

### ISSUE THREAD

**Issue by Localghost2** [FTBTeam/FTB-Revelation-2#78]
* **Modpack Version**: 2.2.0

* **Issue**: The server no longer starts up if "-Dlog4j.configurationFile=log4j.xml" is specified in the McMyAdmin configuration under "Java.CustomOpts", with the "log4j.xml" file being present in the Minecraft root directory. The log4j.xml file was a workaround after ForgeMod changed logging output which caused McMyAdmin to not register the server as started even though it was. Adding the log4j.xml file and the above line to the McMyAdmin configuration file fixed the issue in FTB Revelation 2.1.0, however in 2.2.0 the following is outputted in the console after starting the server with the log4j.xml file present: https://hastebin.com/iyuyanijuh.css

* **Link to Log or Crash File Paste**: Direct copy from console tab in McMyAdmin: https://hastebin.com/iyuyanijuh.css
Copy from console.log: https://hastebin.com/nukedepomi.css

* **Is it Repeatable?**: Yes, happens every time. Cannot start a server with the log4j.xml file present, it starts without it but McMyAdmin will not register it as started then.

* **Mod/s Affected**: -

* **Known Fix**: -

**Comment by tfox83** [comment]
I cannot support MCMyAdmin, sorry.  Please submit an issue to those devs.
