### ISSUE TITLE
Game crash when loading resource pack

### ISSUE THREAD

**Issue by DaveTheAngryJew** [FTBTeam/FTB-Revelation-2#81]
* **Modpack Version**: 2.2.0

* **Issue**: Game throws a java exception (divide by zero) and crashes back out to the launcher every time I try to load a resource pack.  It's definitely the resource pack doing it, because the pack loads all the way through the initializing screen, and then crashes when it attempts to bring up the menu, and when the resource pack is removed the game loads just fine.  

* **Link to Log or Crash File Paste**: doesn't seem to be a crash log, only the divide by zero exception

* **Is it Repeatable?**: happens every time

EDIT:  Turns out its specifically JohnSmith textures.  I've successfully got Soartex to load.

**Comment by tfox83** [comment]
This is a issue with the Texture Pack itself, sorry I cannot support this.  You will need to submit that to the TP author.  I have tested with a few TPs and had no issues, Soartex and Sphax tested fine.
