### ISSUE TITLE
A few options not working in multiplayer

### ISSUE THREAD

**Issue by Hellishrogue** [FTBTeam/FTB-Revelation-2#82]
* **Modpack Version**: 2.3.0

* **Issue**: when using the inventory menu in game the baubles button does not work. also in the upper left hand corner of the screen not all of the icons appear, even though all of the sidebar buttons are enabled. However when playing the game in single player mode all functions fine. Assuming this is a server issue, which i and the administrator for. The mod pack has not been altered in any way, running on mymcadmin 2. While looking at a block it give the name, yet under in red stated "waiting for server"

* **Link to Log or Crash File Paste**: No crashing

* **Is it Repeatable?**: yea

* **Mod/s Affected**:baubles/not sure

* **Known Fix**:

**Comment by tfox83** [comment]
You need to be full OP with highest perms on a server to see all side bar buttons from FTBU.  Also the "waiting for server" on The one Probe indicates a really high ping or your server is low on RAM.  I suggest having at least 4GB of RAM serverside on a VPS or Dedi for this modpack.
