### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Iirion** [FTBTeam/FTB-Revelation-2#83]
* **Modpack Version**: 2.2.0

* **Issue**: When I launch the modpack on the launcher, the game crashs.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7d9ce845

* **Is it Repeatable?**: Every time.

**Comment by flanigomik** [comment]
not a dev but there is no actual crash report in your crash report

**Comment by Iirion** [comment]
I know but i have only this...

**Comment by CrasyFoxBoy** [comment]
i have a sugjeston, in no developer, but thermal expansion, and some forestry expansions prevent my game from launching,
 allocating an extra 1.5 GB also helped launch-speed
below shows some of the mods you might have to remove:

* **Mods Removed:**
* **Thermal Foundation**
* **Thermal Expansion**
* **Thermal Cultavation**
* **Thermal Dynamics**
* **Thermal Innovation**
* **Magic Bees**
* **+2**

i might be wrong, but this has happened tp multiple people

**Comment by tfox83** [comment]
I will need a crash report. Also removing mods is not the solution as we do not have these issues on our side.  If you have to remove mods then you need to allocate more RAM, at least 4GB is required for this modpack.  Or you have a bad download, please do a complete reinstall of the pack and try again.
