### ISSUE TITLE
No Mob Souls after 2.0

### ISSUE THREAD

**Issue by zaqhack** [FTBTeam/FTB-Revelation-2#84]
Currently running 2.2.0 and searched issues and 2.3.0 changelog without finding an update for this.

Simple issue: Draconic Evolution Mob Souls don't seem to drop, anymore. Additionally, I don't seem to see the "Reaper" enchantment, available. I went out of my way to rush a Staff of Power as it has the highest chance to get a soul, but after slaying ludicrous numbers of mobs, still don't have one.

This server was upgraded from pre-2.0 Revelation where I had a mob soul in a spawner. However, I needed to move it, lost the soul, and now can't seem to get another one of any type.

My theory is that the Reaper enchantment isn't working properly for some reason - perhaps a conflict between some other mods?

**Comment by tfox83** [comment]
More than likely a conflict with keeping a pre-2.0.0 revelation world.  I highly suggest fresh worlds with major updates since the pack was completely overhauled in 2.0.0+
