### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Theender2** [FTBTeam/FTB-Revelation-2#85]
I am having an error that says that the version of my computer is not compatible. As the image below shows, but the image is in Portuguese because I live in Brazil
![screenshot_5](https://user-images.githubusercontent.com/41585177/43085856-663f3a76-8e72-11e8-922e-43245aac2941.png)

**Comment by tfox83** [comment]
I have no idea what that is from.  The mod pack will work on any computer with latest JAVA 8.  Please update JAVA and try again.
