### ISSUE TITLE
Mod Glitch Temporaraly Fixed, Removed Bugged Mods

### ISSUE THREAD

**Issue by CrasyFoxBoy** [FTBTeam/FTB-Revelation-2#87]
* **Mods Removed**
Thermal Foundation
Thermal Expansion
Thermal Cultavation
Thermal Dynamics
Thermal Innovation
Magic Bees
+2

* **Currently, these current mods Plus 2 are Currently Glitched:**These mods prevent My game From Launching all the time no matter what i do.

**Mod-pack Version: 2.2.0**
**Client Version: 1.12.2**
**Forge Version: {Release 1.12.2-Forge 1.12.2-14.23.4.2739**}
                                   
                                  **Memory Use/Allocation**
* **Memory Allowed: 6GB**
* **Memory Installed In PC 8GB** 
* **Memory When Launch: 1.6GB-2.4GB**
* **Memory Left In World Launch 1.16GB**

Currently the mod-pack does work without thermal expansion, and some bee mods gone just Fine For Now

**Comment by tfox83** [comment]
No idea what you are trying to report here.  These mods work fine in all of our testing.  I do not see a crash report in your post so I am closing.

**Comment by quindao** [comment]
want a crash report got one here https://pastebin.com/Y6ZEV9F2

**Comment by quindao** [comment]
hey @tfox83

**Comment by quindao** [comment]
ps I'm in 2.30 and 5 GB allocated 4 in pc 8 GB is in paging file info here https://pastebin.com/QdUSvP3X
forge is 1.12.2-14.23.4.2745
