### ISSUE TITLE
Crash FluidLevelEmitter+Darksolarium jetplate hover+Cobalt (speed infused) armor

### ISSUE THREAD

**Issue by arendtjehh** [FTBTeam/FTB-Revelation-2#88]
* **Modpack Version**: 2.3.0

* **Issue**: Title, if i hover (sprint for speed) and the server loads the chunk with my brine platform which contains 1 fluid level emitter, the server immediatly crashes, normal flight does not cause this, i've reproduced the problem 3 times.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b16cef90

* **Is it Repeatable?**: i've tested what the cause was with success 3 times in a row

* **Mod/s Affected**: Tinkers armor+Enderio(SimplyJetpacks)+AppliedEnergistics (extra cells? fluid)

* **Known Fix**: Edit 1.1 blows this theory out of the water. so no known fix

NOTE: Hover dashing in the air is not a problem, so long as the chunk with the fluid level emitter isnt Unloaded, and subsequently Loaded again. the act of Loading the chunk at the speed seems to be the defacto issue

EDIT 1.1
the server now hardcrashes upon me rejoining the server which suggest the speed might not be the issue, but it is everytime generating the same error report, regarding loading in the fluidemitter

EDIT 1.2
i reduced viewdistance in the server cfg, this allowed me to login to the server without causing a crash, backed up that bit, then teleported home, and the server crashes at this point we can 100% rule out velocity, and maybe even the jetpack and armor. However this has not happened be4, and i litteraly just finished the jetpack and started flying around with it when i caused the first crash.

EDIT 1.3
I've now set the server back to a backup, spawned in (for testing, cmon) a dark solarium jetplate. start flying around the base, then far away and return, and the server no longer immediatly crashes (This backup is from be4 i placed the fluidemitter), more testing edits incoming.

EDIT 1.4
Placed the fluid emitter where i had it be4, configured it to detect Hydrogen flew away from the base, and as i was flying off the server hardcrashed again in the same manner as be4.

so the "defined" cause (from testing) is loading/unloading chunks containing a configured fluidemitter set to hydrogen.

Now a solution would be to not use them, so i wont, but there's some info for you guys to play around with.

**Comment by tfox83** [comment]
This should be fixed in 1.5.0
