### ISSUE TITLE
World Load Stuck on 0%

### ISSUE THREAD

**Issue by AmongstOthers** [FTBTeam/FTB-Revelation-2#89]
Modpack Version: Revelation 

Issue: I try to load my singleplayer world and it says " Loading world"... "Building terrain:.. Then pops ups (0%) and stays there. I have tried to restart my computer, lower the render chunks, nothing is working.  -->

Link to Log or Crash File Paste: [00:08:27] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded 

Is it Repeatable?:  Everytime... 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Will need logs to troubleshoot this.

**Comment by tfox83** [comment]
closing due to lack of info.
