### ISSUE TITLE
Limit ways of getting the Infinity Booster Card

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-Revelation-2#9]
Suggested since only one booster card is required that it can only be achieved by killing the ender dragon

A few config changes in `WirelessCraftingTerminal.cfg`

`# Should Withers drop Infinity Booster Card? [default: true]
    B:WitherDropsBooster=true -> false`

`# Will Enderman randomly drop infinity booster cards on death? [default: true]
    B:EndermanDropBoosters=true -> false`

Possibly the crafting recipe too?

`# Should Infinity Booster Card Recipe be disable? [default: false]
    B:DisableBoosterRecipe=false -> true`

**Comment by tfox83** [comment]
changed in next version
