### ISSUE TITLE
Client crash with java.lang.ArrayIndexOutOfBoundsException: -1 caused by Thaumcraft [Beta 17]

### ISSUE THREAD

**Issue by flanigomik** [FTBTeam/FTB-Revelation-2#91]
* **Modpack Version**: 2.3.0

* **Issue**:
 Client crash with java.lang.ArrayIndexOutOfBoundsException: -1 caused by Thaumcraft [Beta 17]
i and my friends are playing FTB Revilation 2.3 (current) on a server which currently uses Beta 17 of thaumcraft. i intentionally burned a few stacks of high Vis items so as to start up a taint infection in the area. just passing by nothing happens but when players AFK in the area minecraft crashes to desktop with the following crash report

we also had the server itself crash once while a player was AFK in this area, that particular crash only occured after three hours, the player was the only one online at the time, the client crashes have been observed between 20 minutes and 5 hours.

Discord integration mod was added on server side only, however this issue occurred well before we added it.

* **Link to Log or Crash File Paste**:
client crash log: https://paste.feed-the-beast.com/view/2a5a77a5
server crash log: https://paste.feed-the-beast.com/view/e5d4d413

* **Is it Repeatable?**: yes, standing around growing taint rifts for extended periods of time causes this issue

* **Mod/s Affected**: Thaumcraft [beta 17]

* **Known Fix**: update thaumcraft as per Thaumcraft dev
https://github.com/Azanor/thaumcraft-beta/issues/1245

**Comment by tfox83** [comment]
I updated to TC beta 22 in Rev 2.4.0 beta, thanks for the report.  Hopefully this resolves your issue.
