### ISSUE TITLE
feed the best revelation client side crash when removing flux with flux cleanup device

### ISSUE THREAD

**Issue by Alaricdragon** [FTBTeam/FTB-Revelation-2#92]
Modpack Version 2.20 (recomended)

client crash on log in to server, crash on log in to single player when removing thaumscraft flux from the chunk with the flux remover device (forgot its name)

crashes from a single player world:
client Log:
[spoiler](only have one log)
attempt to relaunch world attempt 2: https://paste.feed-the-beast.com/view/5e3cc880 [/spoiler]

client crash:
[spoiler]first crash report: https://pastebin.com/7Nyg1Njd
attempt to relaunch world attempt 1: https://pastebin.com/F4ehdnAS
attempt to relaunch world attempt 2 :https://pastebin.com/wnqj3hSX [/spoiler]

Repeatable = true

using essentia from the thumscraft mod-pack to remove flux from a chunk.
note:[spoiler] every-time this has happened (3 times):
1)i had the area with the flux cleaner 'claimed'
2)i had that area set to always run (forgot what it is called. if i'm reading it right, it makes the chunk be loaded when your not there)
3)i had the flux cleaner runing of for a while. i also had the systeam runing off of more then one type of essentia.
4)i left the to the chunk when it crashed[/spoiler]

other things to note:
[spoiler]
1) if you try to rejoin the server \ world, your client will crash. you will see the world for about one second but it will be frozen
2)there is always a debuff in the top right coner of the screen that is at one second. (don't know what that is)
3) if its a server the server dose not crash. the clients do. also the first crash is not at the same time. (and sometimes one or 2 people dont crash until they log out)[/spoiler]

i dont know of any fix

**Comment by tfox83** [comment]
I am not able to reproduce this crash with latest TC beta 22, which is in 2.4.0 beta of revelations.  Please reopen if you still crash after update, thanks.
