### ISSUE TITLE
Games crashes when powering a "Powered Rail"

### ISSUE THREAD

**Issue by LTNightshade** [FTBTeam/FTB-Revelation-2#93]
* **Modpack Version**: 2.2.0

* **Issue**: When i power a "Powered Rail" the game often crashes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8d2dfa36

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Signals (https://github.com/MineMaarten/Signals/issues/79)

* **Known Fix**: None.

**Comment by tfox83** [comment]
Fixed in 2.4.0 beta with update to signals.
