### ISSUE TITLE
similer to https://github.com/FTBTeam/FTB-Revelation-2/issues/87 but with info

### ISSUE THREAD

**Issue by quindao** [FTBTeam/FTB-Revelation-2#94]
* **Modpack Version**: 2.2.0

* **Issue**: crashed on startup supposedly due to the thermal group of mods

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/139688a3

* **Is it Repeatable?**: yes every time 

* **Mod/s Affected**: thermal mods

* **Known Fix**: none, you got one?

also thanks for the

**Comment by tfox83** [comment]
I am not able to repeat this on any of my test systems but am told for the few people that had this issue it has been resolved with 2.4.0 beta.  Thanks
