### ISSUE TITLE
Overlapping Barley Recipe

### ISSUE THREAD

**Issue by FaiThiX** [FTBTeam/FTB-Revelation-2#95]
* **Modpack Version**: 2.2.0

* **Issue**: There is a Overlapping recipe of Barley from Pam's Harvestcraft
Version 1: 1 Barley Seed (Pam's Harvestcraft) from 1 Barley
Version 2: 1 Barley Flour (Natura) from 1 Barley

* **Link to Log or Crash File Paste**: na

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Pam's Harvestcraft, Natura

* **Known Fix**: maybe change one recipe

**Comment by tfox83** [comment]
Fixed by adding custom recipe to Harvestcraft Barley to HC Barley Seed.
`	#Fix barley seed overlap
recipes.remove(<harvestcraft:barleyitem>);
recipes.addShapeless(<harvestcraft:barleyseeditem>,
	[<harvestcraft:barleyitem>]
);`

**Comment by tfox83** [comment]
After more testing Natura kept overriding this work around.  So as a fix I added two HC Barley shapeless crafting gives you 2 HC barley seeds.
