### ISSUE TITLE
Spam in Server Console following 2.4.0 update.

### ISSUE THREAD

**Issue by jjhhgg100123** [FTBTeam/FTB-Revelation-2#98]
**Modpack Version**: 2.4.0

**Issue**: Console Spam on server from ThutTech

**Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/558345b0

**Is it Repeatable?**: Yes, it repeats even after server restarts.

**Mod/s Affected**: Thutstech.

I saw that debug mode was enabled in ThutsCore, and tried disabling it, didn't seem to help. Not sure if this is just something that has to be done after an update or what.

**Comment by HcgRandon** [comment]
Same here!

**Comment by ayan4m1** [comment]
I am also having this issue. It causes the server to refuse connections and makes the server unusable.

https://pastebin.com/raw/D8Y6WjD7

**Comment by jjhhgg100123** [comment]
> It causes the server to refuse connections and makes the server unusable.

The author noted it was just debug spam, if you're having problems with your server refusing connections you have a bigger issue. This is just a minor annoyance for people who like to watch console a bit, as it fills it up.

**Comment by tfox83** [comment]
Can confirm it will not refuse connections.  The spam should be reduced next udpate
