### ISSUE TITLE
Over Powered XP Gain from XReliquary's Infernal Tear

### ISSUE THREAD

**Issue by jjhhgg100123** [FTBTeam/FTB-Revelation-2#99]
**Modpack Version**: 2.4.0

**Issue**: The Infernal Tear from XReliquary gives XP and ignores the exponential growth it takes to continue to level up. Leveling up from from 400 to 401 is as easy as 10 to 11 according to my players.

**Is it Repeatable?**: Yes, just throw some iron at an infernal tear.

**Mod/s Affected**: XReliquary

**Known Fix**: I just removed the recipe.

**Comment by tfox83** [comment]
This has been reported to the dev, if it is fixed I will get it in next update. Thanks for the report
